# 拆分数据

In [8]:
import os
import pandas as pd
import sys
import builtins
import types

# ==== 第二部分：保存原始sys.exit函数 ====
original_exit = sys.exit

# ==== 第三部分：创建安全的替代函数 ====
def safe_print_only_exit(code=0):
    """
    打印消息但不退出的安全函数
    在IPython中使用这个替代sys.exit
    """
    print("hello")
    # 故意不调用原始的sys.exit，确保在IPython中继续执行
    return

# ==== 第四部分：猴子补丁sys模块 ====
# 直接替换sys.exit函数，这是最关键的部分
sys.exit = safe_print_only_exit

# 同时替换builtins.exit（如果存在）
if hasattr(builtins, 'exit'):
    builtins.exit = safe_print_only_exit
else:
    builtins.exit = safe_print_only_exit
import pandas as pd
import os
from onekey_algo import get_param_in_cwd

bagsize = get_param_in_cwd('bagsize')
all_features = pd.read_csv(get_param_in_cwd('feature_file'), dtype={'ID': str})
all_features

,ID,intra_exponential_firstorder_10Percentile,intra_exponential_firstorder_90Percentile,intra_exponential_firstorder_Energy,intra_exponential_firstorder_Entropy,intra_exponential_firstorder_InterquartileRange,intra_exponential_firstorder_Kurtosis,intra_exponential_firstorder_Maximum,intra_exponential_firstorder_Mean,intra_exponential_firstorder_MeanAbsoluteDeviation,...,intra_wavelet_LLL_glszm_SmallAreaHighGrayLevelEmphasis,intra_wavelet_LLL_glszm_SmallAreaLowGrayLevelEmphasis,intra_wavelet_LLL_glszm_ZoneEntropy,intra_wavelet_LLL_glszm_ZonePercentage,intra_wavelet_LLL_glszm_ZoneVariance,intra_wavelet_LLL_ngtdm_Busyness,intra_wavelet_LLL_ngtdm_Coarseness,intra_wavelet_LLL_ngtdm_Complexity,intra_wavelet_LLL_ngtdm_Contrast,intra_wavelet_LLL_ngtdm_Strength
0,1.nii.gz,0.813,8.519,1.311e+07,1.239,4.774,2.110,10.447,4.230,2.701,...,23105.923,0.077,3.700,1.000,0.000,0.061,0.017,6.614e+04,3182.467,303.085
1,100.nii.gz,0.249,377.974,1.141e+08,2.861,37.883,13.004,1188.399,101.987,151.214,...,138288.685,0.011,6.391,0.989,0.011,0.006,0.009,2.032e+06,1002.133,1433.413
2,1001.nii.gz,17.002,388.457,7.964e+07,4.094,337.029,1.684,388.457,172.959,127.756,...,112662.991,0.019,5.681,0.947,0.052,0.012,0.007,1.186e+06,2090.688,719.686
3,1002.nii.gz,13.568,1245.252,5.215e+08,4.372,1103.974,1.350,1245.252,724.883,479.009,...,244804.434,0.007,7.160,0.963,0.037,0.003,0.008,4.300e+06,486.756,1548.125
4,1003.nii.gz,9.516,1464.170,3.509e+08,5.926,827.461,2.364,1635.476,489.325,481.595,...,312394.574,0.007,6.923,0.971,0.029,0.004,0.007,3.818e+06,632.816,1356.471
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,86.nii.gz,1.245,184.454,3.340e+07,2.988,49.779,6.527,349.172,51.411,62.014,...,77969.033,0.034,4.907,1.000,0.000,0.020,0.010,5.502e+05,4362.518,813.610
441,87.nii.gz,3.685,424.152,2.272e+07,3.375,160.080,7.278,1049.764,159.966,198.933,...,108435.500,0.063,4.000,1.000,0.000,0.033,0.012,2.717e+05,13565.048,947.031
442,90.nii.gz,0.821,1324.227,2.343e+08,4.320,805.198,2.236,1414.604,397.119,460.350,...,234602.615,0.010,6.604,0.990,0.010,0.006,0.006,4.681e+06,1942.629,1561.544
443,98.nii.gz,0.068,11.235,4.123e+08,1.061,1.411,40.529,1094.979,32.104,56.583,...,91086.897,0.003,7.940,0.960,0.040,0.002,0.010,3.042e+06,35.189,1054.273
444,99.nii.gz,1.046,15.109,1.620e+07,1.497,6.729,3.740,22.521,6.056,5.113,...,18857.312,0.078,4.000,1.000,0.000,0.049,0.014,1.181e+05,4066.921,372.727

In [9]:
order_by_col = get_param_in_cwd('order_by_col', None)

if order_by_col is None:
    sel_features = []
    for sid in set(all_features['ID']):
        sample_features = all_features[all_features['ID'] == sid]
        if sample_features.shape[0] > bagsize:
            sample_features = sample_features.sample(n=bagsize)
        sel_features.append(sample_features)
    sel_features = pd.concat(sel_features, axis=0)
else:
    sel_features = all_features.sort_values(order_by_col).groupby('ID').head(bagsize).sort_values(['ID', order_by_col])
    sel_features = sel_features.drop(order_by_col, axis=1)
sel_features

,ID,intra_exponential_firstorder_10Percentile,intra_exponential_firstorder_90Percentile,intra_exponential_firstorder_Energy,intra_exponential_firstorder_Entropy,intra_exponential_firstorder_InterquartileRange,intra_exponential_firstorder_Kurtosis,intra_exponential_firstorder_Maximum,intra_exponential_firstorder_Mean,intra_exponential_firstorder_MeanAbsoluteDeviation,...,intra_wavelet_LLL_glszm_SmallAreaHighGrayLevelEmphasis,intra_wavelet_LLL_glszm_SmallAreaLowGrayLevelEmphasis,intra_wavelet_LLL_glszm_ZoneEntropy,intra_wavelet_LLL_glszm_ZonePercentage,intra_wavelet_LLL_glszm_ZoneVariance,intra_wavelet_LLL_ngtdm_Busyness,intra_wavelet_LLL_ngtdm_Coarseness,intra_wavelet_LLL_ngtdm_Complexity,intra_wavelet_LLL_ngtdm_Contrast,intra_wavelet_LLL_ngtdm_Strength
354,675.nii.gz,0.605,2.751,4.117e+07,0.445,1.129,24.225,20.459,2.091,1.609,...,19102.356,0.025,5.272,0.976,0.024,0.017,0.021,1.539e+05,266.365,389.300
110,357.nii.gz,0.707,108.208,4.351e+07,2.645,36.406,16.970,1457.179,93.222,137.414,...,70911.500,0.029,4.970,1.000,0.000,0.026,0.009,5.193e+05,3283.398,641.007
90,263.nii.gz,0.424,30.764,4.414e+07,1.470,3.692,32.988,517.059,21.983,33.901,...,60445.782,0.026,5.285,0.929,0.071,0.022,0.009,5.341e+05,1810.960,609.251
149,435.nii.gz,4.206,840.916,2.978e+07,3.640,371.764,5.527,1607.140,342.380,304.942,...,90235.200,0.067,3.907,1.000,0.000,0.062,0.006,4.636e+05,32384.293,559.081
368,689.nii.gz,0.198,1282.362,4.937e+08,3.237,160.292,4.043,1282.362,243.477,346.170,...,143796.575,0.004,7.761,0.986,0.014,0.002,0.007,5.495e+06,134.262,1415.547
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,622.nii.gz,0.312,1269.205,4.823e+08,4.774,1019.415,1.583,1269.205,459.898,475.948,...,319167.399,0.005,7.431,0.975,0.025,0.003,0.006,6.930e+06,449.854,1494.945
359,680.nii.gz,0.724,1468.311,7.849e+08,4.303,321.287,3.982,1468.311,292.602,382.620,...,247778.302,0.003,8.264,0.995,0.005,0.001,0.007,1.119e+07,118.577,1989.107
347,668.nii.gz,0.706,1445.536,6.620e+08,4.466,746.468,2.511,1445.536,383.601,468.149,...,260862.584,0.004,7.949,0.970,0.030,0.002,0.006,9.971e+06,237.506,1780.105
310,629.nii.gz,0.490,184.346,1.789e+08,3.175,27.129,25.961,1326.986,71.350,101.891,...,128321.708,0.007,7.007,0.980,0.020,0.003,0.010,2.451e+06,273.168,1353.234
123,408.nii.gz,0.846,6.779,8.661e+07,0.937,2.862,18.061,27.984,3.558,2.521,...,27208.777,0.012,6.226,0.977,0.023,0.008,0.016,3.854e+05,94.203,378.656

In [10]:
import pandas as pd
from onekey_algo import get_param_in_cwd
import numpy as np
import os

label_data = pd.read_csv(get_param_in_cwd('label_file'), dtype={'ID': str})
data_root = get_param_in_cwd('data_root')
os.makedirs(data_root, exist_ok=True)
for ug in get_param_in_cwd('subsets'):
    sub_group = label_data[label_data['group'] == ug]
    display(sub_group)
    sub_features = pd.merge(sel_features, sub_group[['ID']], on='ID', how='inner')
    print(ug, len(np.unique(sub_group['ID'])), len(np.unique(sub_features['ID'])))
    sub_features.to_csv(f'{data_root}/{ug}.csv', index=False)

             ID  label  group
31    87.nii.gz      0  train
93   324.nii.gz      0  train
94   329.nii.gz      0  train
95   348.nii.gz      0  train
96   354.nii.gz      0  train
..          ...    ...    ...
400  750.nii.gz      1  train
401  751.nii.gz      1  train
402  752.nii.gz      1  train
403  753.nii.gz      0  train
404  832.nii.gz      0  train

[298 rows x 3 columns]

train 298 298

             ID  label group
0      1.nii.gz      1   val
4     13.nii.gz      1   val
6     20.nii.gz      1   val
8     38.nii.gz      1   val
21    61.nii.gz      1   val
..          ...    ...   ...
111  410.nii.gz      1   val
113  412.nii.gz      1   val
114  413.nii.gz      1   val
115  414.nii.gz      1   val
116  415.nii.gz      1   val

[74 rows x 3 columns]

val 74 74

              ID  label group
1       2.nii.gz      0  test
2       3.nii.gz      0  test
3       4.nii.gz      0  test
5      19.nii.gz      0  test
7      28.nii.gz      0  test
..           ...    ...   ...
440  1036.nii.gz      1  test
441  1037.nii.gz      1  test
442  1038.nii.gz      1  test
443  1039.nii.gz      1  test
444  1040.nii.gz      1  test

[68 rows x 3 columns]

test 68 68

             ID  label group
102  401.nii.gz      1  gene
103  402.nii.gz      1  gene
105  404.nii.gz      1  gene
107  406.nii.gz      0  gene
112  411.nii.gz      0  gene

gene 5 5

In [11]:
import os
import pandas as pd
import sys
import builtins
import types

# ==== 第二部分：保存原始sys.exit函数 ====
original_exit = sys.exit

# ==== 第三部分：创建安全的替代函数 ====
def safe_print_only_exit(code=0):
    """
    打印消息但不退出的安全函数
    在IPython中使用这个替代sys.exit
    """
    print("hello")
    # 故意不调用原始的sys.exit，确保在IPython中继续执行
    return

# ==== 第四部分：猴子补丁sys模块 ====
# 直接替换sys.exit函数，这是最关键的部分
sys.exit = safe_print_only_exit

# 同时替换builtins.exit（如果存在）
if hasattr(builtins, 'exit'):
    builtins.exit = safe_print_only_exit
else:
    builtins.exit = safe_print_only_exit
import os
from onekey_algo import get_param_in_cwd
from onekey_algo.fusion.MultiTransformer.run_model import train_categorical_model as clf_main
from collections import namedtuple

data_root = get_param_in_cwd('data_root')
# 单中心设置参数
train = os.path.join(data_root, 'train.csv')
if 'val' in get_param_in_cwd('subsets'):
    val = os.path.join(data_root, 'val.csv')
    tests = [os.path.join(data_root, f'{subset}.csv') for subset in get_param_in_cwd('subsets')]
else:
    val = os.path.join(data_root, 'test.csv')
    tests = []

# 多中心设置参数
# train = os.path.join(data_root, 'train.csv')
# val = os.path.join(data_root, 'val.csv')
# tests = [os.path.join(data_root, subset + '.csv') for subset in get_param_in_cwd('subsets')
#          if subset not in ['train', 'val'] and os.path.exists(os.path.join(data_root, subset + '.csv'))]
print(tests)
# tests = [os.path.join(data_root, 'NHH-GC.csv')]
target_file = get_param_in_cwd('label_file')
input_dim = sel_features.shape[1] - 1
normalize = True
header = 0

bags_size = get_param_in_cwd('bagsize')
for bags_size in [bags_size]:
    params = dict(train=train,
                  val=val,
                  tests=tests,
                  target_file=target_file,
                  j=0,
                  input_dim=input_dim,
                  bags_size=bags_size,
                  normalize=normalize,
                  header=header,
                  gpus=[0],
                  batch_size=8,
                  model_name='Transformer',
                  epochs=get_param_in_cwd('transformer_epoch', 100),
                  init_lr=0.001,
                  optimizer='sgd',
                  model_root=os.path.join(get_param_in_cwd('model_root'), f'Transformer'),
                  add_date=False,
                  retrain='',
                  iters_start=0,
                  iters_verbose=1,
                  save_per_epoch=True,
                  pretrained=True)
    # 训练模型
    Args = namedtuple("Args", params)
    clf_main(Args(**params))

['data\\train.csv', 'data\\val.csv', 'data\\test.csv', 'data\\gene.csv']

[2026-06-18 18:38:56 - <frozen onekey_algo.datasets.StructureDataset>:  83]	INFO	正在进行标准化，请稍后...
[2026-06-18 18:38:58 - <frozen onekey_algo.utils.about_log>: 149]	INFO	特征文件：data\train.csv
[2026-06-18 18:38:58 - <frozen onekey_algo.utils.about_log>: 149]	INFO	label文件：D:\\9gene-negative\\labels.csv
[2026-06-18 18:38:58 - <frozen onekey_algo.utils.about_log>: 149]	INFO	一共获取到：298个样本, 共2类。
[2026-06-18 18:38:58 - <frozen onekey_algo.datasets.StructureDataset>:  83]	INFO	正在进行标准化，请稍后...
[2026-06-18 18:38:59 - <frozen onekey_algo.utils.about_log>: 149]	INFO	特征文件：data\val.csv
[2026-06-18 18:38:59 - <frozen onekey_algo.utils.about_log>: 149]	INFO	label文件：D:\\9gene-negative\\labels.csv
[2026-06-18 18:38:59 - <frozen onekey_algo.utils.about_log>: 149]	INFO	一共获取到：74个样本, 共2类。
[2026-06-18 18:38:59 - <frozen onekey_algo.datasets.StructureDataset>:  83]	INFO	正在进行标准化，请稍后...
[2026-06-18 18:39:01 - <frozen onekey_algo.utils.about_log>: 149]	INFO	特征文件：data\train.csv
[2026-06-18 18:39:01 - <frozen onekey_algo.utils.about_log>: 149]	INFO	label文件：None
[2026-06-18 18:39:01 - <frozen onekey_algo.utils.about_log>: 149]	INFO	一共获取到：298个样本, 共2类。
[2026-06-18 18:39:01 - <frozen onekey_algo.datasets.StructureDataset>:  83]	INFO	正在进行标准化，请稍后...
[2026-06-18 18:39:02 - <frozen onekey_algo.utils.about_log>: 149]	INFO	特征文件：data\val.csv
[2026-06-18 18:39:02 - <frozen onekey_algo.utils.about_log>: 149]	INFO	label文件：None
[2026-06-18 18:39:02 - <frozen onekey_algo.utils.about_log>: 149]	INFO	一共获取到：74个样本, 共2类。
[2026-06-18 18:39:02 - <frozen onekey_algo.datasets.StructureDataset>:  83]	INFO	正在进行标准化，请稍后...
[2026-06-18 18:39:03 - <frozen onekey_algo.utils.about_log>: 149]	INFO	特征文件：data\test.csv
[2026-06-18 18:39:03 - <frozen onekey_algo.utils.about_log>: 149]	INFO	label文件：None
[2026-06-18 18:39:03 - <frozen onekey_algo.utils.about_log>: 149]	INFO	一共获取到：68个样本, 共2类。
[2026-06-18 18:39:03 - <frozen onekey_algo.datasets.StructureDataset>:  83]	INFO	正在进行标准化，请稍后...
[2026-06-18 18:39:05 - <frozen onekey_algo.utils.about_log>: 149]	INFO	特征文件：data\gene.csv
[2026-06-18 18:39:05 - <frozen onekey_algo.utils.about_log>: 149]	INFO	label文件：None
[2026-06-18 18:39:05 - <frozen onekey_algo.utils.about_log>: 149]	INFO	一共获取到：5个样本, 共2类。
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 321]	INFO	Start training...
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.027,1	LR: 0.001000	Loss: 0.917	Acc: 25.0000	 Speed: 208.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.054,2	LR: 0.001000	Loss: 0.727	Acc: 37.5000	 Speed: 363.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.081,3	LR: 0.001000	Loss: 0.703	Acc: 62.5000	 Speed: 421.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.107,4	LR: 0.001000	Loss: 0.618	Acc: 87.5000	 Speed: 411.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.134,5	LR: 0.001000	Loss: 0.720	Acc: 50.0000	 Speed: 338.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.161,6	LR: 0.001000	Loss: 0.744	Acc: 37.5000	 Speed: 385.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.188,7	LR: 0.001000	Loss: 0.605	Acc: 87.5000	 Speed: 283.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.215,8	LR: 0.001000	Loss: 0.439	Acc: 87.5000	 Speed: 380.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.242,9	LR: 0.001000	Loss: 0.696	Acc: 62.5000	 Speed: 365.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.268,10	LR: 0.001000	Loss: 0.664	Acc: 62.5000	 Speed: 333.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.295,11	LR: 0.001000	Loss: 0.582	Acc: 75.0000	 Speed: 389.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.322,12	LR: 0.001000	Loss: 0.689	Acc: 62.5000	 Speed: 615.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.349,13	LR: 0.001000	Loss: 0.469	Acc: 87.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.376,14	LR: 0.001000	Loss: 0.932	Acc: 37.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.403,15	LR: 0.001000	Loss: 0.597	Acc: 75.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.430,16	LR: 0.001000	Loss: 0.729	Acc: 62.5000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.456,17	LR: 0.001000	Loss: 1.008	Acc: 12.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.483,18	LR: 0.001000	Loss: 0.708	Acc: 62.5000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.510,19	LR: 0.001000	Loss: 0.726	Acc: 37.5000	 Speed: 1703.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.537,20	LR: 0.001000	Loss: 0.693	Acc: 50.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.564,21	LR: 0.001000	Loss: 0.589	Acc: 87.5000	 Speed: 2743.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.591,22	LR: 0.001000	Loss: 0.889	Acc: 37.5000	 Speed: 1897.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.617,23	LR: 0.001000	Loss: 0.704	Acc: 50.0000	 Speed: 2077.42 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.644,24	LR: 0.001000	Loss: 0.702	Acc: 37.5000	 Speed: 2281.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.671,25	LR: 0.001000	Loss: 0.694	Acc: 62.5000	 Speed: 1899.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.698,26	LR: 0.001000	Loss: 0.802	Acc: 37.5000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.725,27	LR: 0.001000	Loss: 0.695	Acc: 50.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.752,28	LR: 0.001000	Loss: 0.644	Acc: 62.5000	 Speed: 1213.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.779,29	LR: 0.001000	Loss: 0.882	Acc: 12.5000	 Speed: 1774.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.805,30	LR: 0.001000	Loss: 0.661	Acc: 75.0000	 Speed: 1720.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.832,31	LR: 0.001000	Loss: 0.755	Acc: 37.5000	 Speed: 1600.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.859,32	LR: 0.001000	Loss: 0.693	Acc: 50.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.886,33	LR: 0.001000	Loss: 0.705	Acc: 50.0000	 Speed: 1600.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.913,34	LR: 0.001000	Loss: 0.707	Acc: 50.0000	 Speed: 1337.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.940,35	LR: 0.001000	Loss: 0.726	Acc: 37.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.966,36	LR: 0.001000	Loss: 0.758	Acc: 37.5000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 0.993,37	LR: 0.001000	Loss: 0.677	Acc: 50.0000	 Speed: 2111.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.020,38	LR: 0.001000	Loss: 0.659	Acc: 50.0000	 Speed: 547.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 47.297	Speed: 3363.6614 samples/s	Time: 0.02s
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.047,39	LR: 0.001000	Loss: 0.712	Acc: 50.0000	 Speed: 52.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.074,40	LR: 0.001000	Loss: 0.644	Acc: 100.0000	 Speed: 1615.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.101,41	LR: 0.001000	Loss: 0.610	Acc: 75.0000	 Speed: 1216.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.128,42	LR: 0.001000	Loss: 0.832	Acc: 25.0000	 Speed: 1938.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.154,43	LR: 0.001000	Loss: 0.647	Acc: 62.5000	 Speed: 2480.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.181,44	LR: 0.001000	Loss: 0.795	Acc: 37.5000	 Speed: 2598.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.208,45	LR: 0.001000	Loss: 0.657	Acc: 50.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.235,46	LR: 0.001000	Loss: 0.704	Acc: 50.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.262,47	LR: 0.001000	Loss: 0.673	Acc: 62.5000	 Speed: 1333.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.289,48	LR: 0.001000	Loss: 0.602	Acc: 62.5000	 Speed: 1465.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.315,49	LR: 0.001000	Loss: 0.692	Acc: 50.0000	 Speed: 1278.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.342,50	LR: 0.001000	Loss: 0.706	Acc: 50.0000	 Speed: 1504.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.369,51	LR: 0.001000	Loss: 0.716	Acc: 62.5000	 Speed: 2168.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.396,52	LR: 0.001000	Loss: 0.690	Acc: 62.5000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.423,53	LR: 0.001000	Loss: 0.683	Acc: 50.0000	 Speed: 1118.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.450,54	LR: 0.000999	Loss: 0.617	Acc: 62.5000	 Speed: 2000.38 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.477,55	LR: 0.000999	Loss: 0.654	Acc: 62.5000	 Speed: 1823.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.503,56	LR: 0.000999	Loss: 0.829	Acc: 25.0000	 Speed: 1490.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.530,57	LR: 0.000999	Loss: 0.707	Acc: 50.0000	 Speed: 1378.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.557,58	LR: 0.000999	Loss: 0.679	Acc: 50.0000	 Speed: 1951.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.584,59	LR: 0.000999	Loss: 0.744	Acc: 37.5000	 Speed: 1760.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.611,60	LR: 0.000999	Loss: 0.880	Acc: 0.0000	 Speed: 1645.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.638,61	LR: 0.000999	Loss: 0.808	Acc: 25.0000	 Speed: 1785.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.664,62	LR: 0.000999	Loss: 0.661	Acc: 75.0000	 Speed: 2175.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.691,63	LR: 0.000999	Loss: 0.701	Acc: 62.5000	 Speed: 2370.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.718,64	LR: 0.000999	Loss: 0.625	Acc: 62.5000	 Speed: 2664.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.745,65	LR: 0.000999	Loss: 0.678	Acc: 50.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.772,66	LR: 0.000999	Loss: 0.765	Acc: 37.5000	 Speed: 2025.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.799,67	LR: 0.000999	Loss: 0.619	Acc: 87.5000	 Speed: 2537.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.826,68	LR: 0.000999	Loss: 0.794	Acc: 12.5000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.852,69	LR: 0.000999	Loss: 0.641	Acc: 87.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.879,70	LR: 0.000999	Loss: 0.634	Acc: 62.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.906,71	LR: 0.000999	Loss: 0.876	Acc: 25.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:05 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.933,72	LR: 0.000999	Loss: 0.678	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.960,73	LR: 0.000999	Loss: 0.683	Acc: 50.0000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 1.987,74	LR: 0.000999	Loss: 0.655	Acc: 75.0000	 Speed: 1842.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.013,75	LR: 0.000999	Loss: 0.752	Acc: 37.5000	 Speed: 2666.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.040,76	LR: 0.000999	Loss: 0.689	Acc: 50.0000	 Speed: 666.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3243.4139 samples/s	Time: 0.02s
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.067,77	LR: 0.000999	Loss: 0.650	Acc: 75.0000	 Speed: 51.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.094,78	LR: 0.000999	Loss: 0.602	Acc: 75.0000	 Speed: 2016.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.121,79	LR: 0.000999	Loss: 0.915	Acc: 25.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.148,80	LR: 0.000999	Loss: 0.715	Acc: 50.0000	 Speed: 1741.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.174,81	LR: 0.000999	Loss: 0.671	Acc: 50.0000	 Speed: 1297.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.201,82	LR: 0.000999	Loss: 0.706	Acc: 37.5000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.228,83	LR: 0.000999	Loss: 0.630	Acc: 75.0000	 Speed: 2563.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.255,84	LR: 0.000999	Loss: 0.676	Acc: 50.0000	 Speed: 2132.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.282,85	LR: 0.000999	Loss: 0.673	Acc: 50.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.309,86	LR: 0.000999	Loss: 0.592	Acc: 75.0000	 Speed: 2446.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.336,87	LR: 0.000999	Loss: 0.936	Acc: 12.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.362,88	LR: 0.000999	Loss: 0.633	Acc: 75.0000	 Speed: 2570.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.389,89	LR: 0.000999	Loss: 0.686	Acc: 37.5000	 Speed: 2196.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.416,90	LR: 0.000999	Loss: 0.740	Acc: 25.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.443,91	LR: 0.000999	Loss: 0.709	Acc: 50.0000	 Speed: 2957.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.470,92	LR: 0.000998	Loss: 0.677	Acc: 50.0000	 Speed: 1937.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.497,93	LR: 0.000998	Loss: 0.711	Acc: 62.5000	 Speed: 1591.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.523,94	LR: 0.000998	Loss: 0.574	Acc: 75.0000	 Speed: 1784.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.550,95	LR: 0.000998	Loss: 0.620	Acc: 62.5000	 Speed: 2165.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.577,96	LR: 0.000998	Loss: 0.484	Acc: 87.5000	 Speed: 1232.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.604,97	LR: 0.000998	Loss: 0.824	Acc: 37.5000	 Speed: 2024.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.631,98	LR: 0.000998	Loss: 0.643	Acc: 62.5000	 Speed: 1459.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.658,99	LR: 0.000998	Loss: 0.617	Acc: 62.5000	 Speed: 2663.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.685,100	LR: 0.000998	Loss: 0.705	Acc: 62.5000	 Speed: 2112.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.711,101	LR: 0.000998	Loss: 0.725	Acc: 50.0000	 Speed: 2665.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.738,102	LR: 0.000998	Loss: 0.708	Acc: 50.0000	 Speed: 1741.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.765,103	LR: 0.000998	Loss: 0.702	Acc: 50.0000	 Speed: 1784.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.792,104	LR: 0.000998	Loss: 0.664	Acc: 62.5000	 Speed: 2016.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.819,105	LR: 0.000998	Loss: 0.683	Acc: 50.0000	 Speed: 2235.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.846,106	LR: 0.000998	Loss: 0.859	Acc: 12.5000	 Speed: 2001.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.872,107	LR: 0.000998	Loss: 0.652	Acc: 50.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.899,108	LR: 0.000998	Loss: 0.700	Acc: 50.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.926,109	LR: 0.000998	Loss: 0.631	Acc: 87.5000	 Speed: 1446.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.953,110	LR: 0.000998	Loss: 0.739	Acc: 25.0000	 Speed: 1708.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 2.980,111	LR: 0.000998	Loss: 0.644	Acc: 62.5000	 Speed: 1518.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.007,112	LR: 0.000998	Loss: 0.732	Acc: 37.5000	 Speed: 1810.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.034,113	LR: 0.000998	Loss: 0.704	Acc: 37.5000	 Speed: 2408.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.060,114	LR: 0.000998	Loss: 0.537	Acc: 100.0000	 Speed: 665.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 59.459	Speed: 3408.1311 samples/s	Time: 0.02s
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.087,115	LR: 0.000998	Loss: 0.585	Acc: 87.5000	 Speed: 51.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.114,116	LR: 0.000998	Loss: 0.628	Acc: 75.0000	 Speed: 1628.14 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.141,117	LR: 0.000998	Loss: 0.538	Acc: 75.0000	 Speed: 2185.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.168,118	LR: 0.000998	Loss: 0.841	Acc: 25.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.195,119	LR: 0.000997	Loss: 0.628	Acc: 75.0000	 Speed: 2113.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.221,120	LR: 0.000997	Loss: 0.628	Acc: 62.5000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.248,121	LR: 0.000997	Loss: 0.609	Acc: 75.0000	 Speed: 1869.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.275,122	LR: 0.000997	Loss: 0.616	Acc: 62.5000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.302,123	LR: 0.000997	Loss: 0.703	Acc: 50.0000	 Speed: 2028.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.329,124	LR: 0.000997	Loss: 0.706	Acc: 50.0000	 Speed: 1997.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.356,125	LR: 0.000997	Loss: 0.677	Acc: 37.5000	 Speed: 2562.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.383,126	LR: 0.000997	Loss: 0.648	Acc: 62.5000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.409,127	LR: 0.000997	Loss: 0.599	Acc: 75.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.436,128	LR: 0.000997	Loss: 0.591	Acc: 62.5000	 Speed: 2266.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.463,129	LR: 0.000997	Loss: 0.845	Acc: 25.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.490,130	LR: 0.000997	Loss: 0.722	Acc: 50.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.517,131	LR: 0.000997	Loss: 0.641	Acc: 87.5000	 Speed: 1333.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.544,132	LR: 0.000997	Loss: 0.664	Acc: 62.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.570,133	LR: 0.000997	Loss: 0.648	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.597,134	LR: 0.000997	Loss: 0.626	Acc: 75.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.624,135	LR: 0.000997	Loss: 0.709	Acc: 37.5000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.651,136	LR: 0.000997	Loss: 0.733	Acc: 62.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.678,137	LR: 0.000997	Loss: 0.724	Acc: 50.0000	 Speed: 1942.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.705,138	LR: 0.000997	Loss: 0.874	Acc: 12.5000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.732,139	LR: 0.000997	Loss: 0.665	Acc: 50.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.758,140	LR: 0.000997	Loss: 0.662	Acc: 50.0000	 Speed: 1916.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.785,141	LR: 0.000996	Loss: 0.700	Acc: 62.5000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.812,142	LR: 0.000996	Loss: 0.630	Acc: 62.5000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.839,143	LR: 0.000996	Loss: 0.857	Acc: 12.5000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.866,144	LR: 0.000996	Loss: 0.573	Acc: 87.5000	 Speed: 1600.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.893,145	LR: 0.000996	Loss: 0.641	Acc: 87.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.919,146	LR: 0.000996	Loss: 0.562	Acc: 75.0000	 Speed: 2159.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.946,147	LR: 0.000996	Loss: 0.604	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 3.973,148	LR: 0.000996	Loss: 0.632	Acc: 75.0000	 Speed: 2062.22 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.000,149	LR: 0.000996	Loss: 0.686	Acc: 50.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.027,150	LR: 0.000996	Loss: 0.753	Acc: 37.5000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.054,151	LR: 0.000996	Loss: 0.682	Acc: 50.0000	 Speed: 1535.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.081,152	LR: 0.000996	Loss: 0.653	Acc: 50.0000	 Speed: 500.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 47.297	Speed: 3665.2673 samples/s	Time: 0.02s
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.107,153	LR: 0.000996	Loss: 0.608	Acc: 62.5000	 Speed: 53.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.134,154	LR: 0.000996	Loss: 0.796	Acc: 25.0000	 Speed: 2644.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.161,155	LR: 0.000996	Loss: 0.657	Acc: 62.5000	 Speed: 1589.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.188,156	LR: 0.000996	Loss: 0.706	Acc: 50.0000	 Speed: 1377.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.215,157	LR: 0.000996	Loss: 0.642	Acc: 100.0000	 Speed: 1182.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.242,158	LR: 0.000996	Loss: 0.667	Acc: 62.5000	 Speed: 1993.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.268,159	LR: 0.000996	Loss: 0.714	Acc: 50.0000	 Speed: 2355.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.295,160	LR: 0.000995	Loss: 0.690	Acc: 50.0000	 Speed: 1775.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.322,161	LR: 0.000995	Loss: 0.606	Acc: 75.0000	 Speed: 1222.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.349,162	LR: 0.000995	Loss: 0.614	Acc: 75.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.376,163	LR: 0.000995	Loss: 0.676	Acc: 62.5000	 Speed: 1200.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.403,164	LR: 0.000995	Loss: 0.692	Acc: 50.0000	 Speed: 2166.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.430,165	LR: 0.000995	Loss: 0.605	Acc: 75.0000	 Speed: 1947.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.456,166	LR: 0.000995	Loss: 0.588	Acc: 87.5000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.483,167	LR: 0.000995	Loss: 0.629	Acc: 75.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.510,168	LR: 0.000995	Loss: 0.604	Acc: 75.0000	 Speed: 2048.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.537,169	LR: 0.000995	Loss: 0.691	Acc: 62.5000	 Speed: 2193.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.564,170	LR: 0.000995	Loss: 0.736	Acc: 62.5000	 Speed: 1924.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.591,171	LR: 0.000995	Loss: 0.746	Acc: 50.0000	 Speed: 1996.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.617,172	LR: 0.000995	Loss: 0.567	Acc: 75.0000	 Speed: 2662.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.644,173	LR: 0.000995	Loss: 0.671	Acc: 62.5000	 Speed: 1943.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.671,174	LR: 0.000995	Loss: 0.698	Acc: 50.0000	 Speed: 2136.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.698,175	LR: 0.000995	Loss: 0.607	Acc: 87.5000	 Speed: 1997.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.725,176	LR: 0.000995	Loss: 0.752	Acc: 37.5000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.752,177	LR: 0.000994	Loss: 0.706	Acc: 50.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.779,178	LR: 0.000994	Loss: 0.670	Acc: 62.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.805,179	LR: 0.000994	Loss: 0.539	Acc: 87.5000	 Speed: 2000.74 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.832,180	LR: 0.000994	Loss: 0.649	Acc: 62.5000	 Speed: 1600.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.859,181	LR: 0.000994	Loss: 0.617	Acc: 62.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.886,182	LR: 0.000994	Loss: 0.692	Acc: 62.5000	 Speed: 1333.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.913,183	LR: 0.000994	Loss: 0.914	Acc: 25.0000	 Speed: 1332.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.940,184	LR: 0.000994	Loss: 0.683	Acc: 50.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:06 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.966,185	LR: 0.000994	Loss: 0.650	Acc: 75.0000	 Speed: 1719.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 4.993,186	LR: 0.000994	Loss: 0.722	Acc: 50.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.020,187	LR: 0.000994	Loss: 0.611	Acc: 62.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.047,188	LR: 0.000994	Loss: 0.571	Acc: 75.0000	 Speed: 1332.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.074,189	LR: 0.000994	Loss: 0.677	Acc: 50.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.101,190	LR: 0.000994	Loss: 0.492	Acc: 100.0000	 Speed: 399.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 60.811	Speed: 3363.7708 samples/s	Time: 0.02s
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.128,191	LR: 0.000994	Loss: 0.625	Acc: 75.0000	 Speed: 52.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.154,192	LR: 0.000993	Loss: 0.663	Acc: 62.5000	 Speed: 1839.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.181,193	LR: 0.000993	Loss: 0.575	Acc: 87.5000	 Speed: 1600.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.208,194	LR: 0.000993	Loss: 0.606	Acc: 50.0000	 Speed: 1486.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.235,195	LR: 0.000993	Loss: 0.594	Acc: 87.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.262,196	LR: 0.000993	Loss: 0.607	Acc: 62.5000	 Speed: 1468.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.289,197	LR: 0.000993	Loss: 0.780	Acc: 12.5000	 Speed: 1755.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.315,198	LR: 0.000993	Loss: 0.697	Acc: 25.0000	 Speed: 2411.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.342,199	LR: 0.000993	Loss: 0.632	Acc: 75.0000	 Speed: 1222.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.369,200	LR: 0.000993	Loss: 0.678	Acc: 62.5000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.396,201	LR: 0.000993	Loss: 0.784	Acc: 37.5000	 Speed: 1842.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.423,202	LR: 0.000993	Loss: 0.726	Acc: 37.5000	 Speed: 2202.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.450,203	LR: 0.000993	Loss: 0.569	Acc: 100.0000	 Speed: 1844.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.477,204	LR: 0.000993	Loss: 0.604	Acc: 87.5000	 Speed: 1967.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.503,205	LR: 0.000993	Loss: 0.693	Acc: 50.0000	 Speed: 2611.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.530,206	LR: 0.000992	Loss: 0.612	Acc: 75.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.557,207	LR: 0.000992	Loss: 0.669	Acc: 62.5000	 Speed: 2281.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.584,208	LR: 0.000992	Loss: 0.624	Acc: 62.5000	 Speed: 1728.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.611,209	LR: 0.000992	Loss: 0.711	Acc: 50.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.638,210	LR: 0.000992	Loss: 0.743	Acc: 37.5000	 Speed: 1135.01 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.664,211	LR: 0.000992	Loss: 0.609	Acc: 75.0000	 Speed: 1616.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.691,212	LR: 0.000992	Loss: 0.552	Acc: 87.5000	 Speed: 1267.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.718,213	LR: 0.000992	Loss: 0.587	Acc: 62.5000	 Speed: 1791.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.745,214	LR: 0.000992	Loss: 0.679	Acc: 50.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.772,215	LR: 0.000992	Loss: 0.662	Acc: 62.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.799,216	LR: 0.000992	Loss: 0.704	Acc: 50.0000	 Speed: 1745.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.826,217	LR: 0.000992	Loss: 0.726	Acc: 50.0000	 Speed: 1267.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.852,218	LR: 0.000992	Loss: 0.634	Acc: 75.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.879,219	LR: 0.000991	Loss: 0.622	Acc: 62.5000	 Speed: 2280.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.906,220	LR: 0.000991	Loss: 0.547	Acc: 87.5000	 Speed: 1873.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.933,221	LR: 0.000991	Loss: 0.702	Acc: 50.0000	 Speed: 1851.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.960,222	LR: 0.000991	Loss: 0.672	Acc: 62.5000	 Speed: 1790.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 5.987,223	LR: 0.000991	Loss: 0.569	Acc: 62.5000	 Speed: 1845.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.013,224	LR: 0.000991	Loss: 0.711	Acc: 62.5000	 Speed: 2408.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.040,225	LR: 0.000991	Loss: 0.592	Acc: 75.0000	 Speed: 1588.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.067,226	LR: 0.000991	Loss: 0.704	Acc: 62.5000	 Speed: 1835.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.094,227	LR: 0.000991	Loss: 0.529	Acc: 87.5000	 Speed: 2233.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.121,228	LR: 0.000991	Loss: 0.375	Acc: 100.0000	 Speed: 555.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 52.703	Speed: 3846.7454 samples/s	Time: 0.02s
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.148,229	LR: 0.000991	Loss: 0.737	Acc: 37.5000	 Speed: 53.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.174,230	LR: 0.000991	Loss: 0.503	Acc: 87.5000	 Speed: 1429.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.201,231	LR: 0.000991	Loss: 0.608	Acc: 50.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.228,232	LR: 0.000990	Loss: 0.524	Acc: 87.5000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.255,233	LR: 0.000990	Loss: 0.732	Acc: 62.5000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.282,234	LR: 0.000990	Loss: 0.870	Acc: 37.5000	 Speed: 1936.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.309,235	LR: 0.000990	Loss: 0.629	Acc: 62.5000	 Speed: 2276.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.336,236	LR: 0.000990	Loss: 0.622	Acc: 87.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.362,237	LR: 0.000990	Loss: 0.649	Acc: 62.5000	 Speed: 1137.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.389,238	LR: 0.000990	Loss: 0.656	Acc: 75.0000	 Speed: 1741.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.416,239	LR: 0.000990	Loss: 0.835	Acc: 37.5000	 Speed: 1655.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.443,240	LR: 0.000990	Loss: 0.597	Acc: 75.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.470,241	LR: 0.000990	Loss: 0.691	Acc: 50.0000	 Speed: 1806.04 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.497,242	LR: 0.000990	Loss: 0.721	Acc: 37.5000	 Speed: 1570.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.523,243	LR: 0.000990	Loss: 0.661	Acc: 62.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.550,244	LR: 0.000989	Loss: 0.652	Acc: 75.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.577,245	LR: 0.000989	Loss: 0.599	Acc: 62.5000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.604,246	LR: 0.000989	Loss: 0.714	Acc: 50.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.631,247	LR: 0.000989	Loss: 0.717	Acc: 37.5000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.658,248	LR: 0.000989	Loss: 0.645	Acc: 50.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.685,249	LR: 0.000989	Loss: 0.635	Acc: 62.5000	 Speed: 2042.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.711,250	LR: 0.000989	Loss: 0.506	Acc: 75.0000	 Speed: 1872.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.738,251	LR: 0.000989	Loss: 0.752	Acc: 25.0000	 Speed: 1832.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.765,252	LR: 0.000989	Loss: 0.669	Acc: 62.5000	 Speed: 2026.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.792,253	LR: 0.000989	Loss: 0.574	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.819,254	LR: 0.000989	Loss: 0.608	Acc: 100.0000	 Speed: 2012.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.846,255	LR: 0.000988	Loss: 0.628	Acc: 62.5000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.872,256	LR: 0.000988	Loss: 0.590	Acc: 75.0000	 Speed: 1259.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.899,257	LR: 0.000988	Loss: 0.620	Acc: 50.0000	 Speed: 2090.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.926,258	LR: 0.000988	Loss: 0.588	Acc: 62.5000	 Speed: 1679.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.953,259	LR: 0.000988	Loss: 0.642	Acc: 50.0000	 Speed: 1721.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 6.980,260	LR: 0.000988	Loss: 0.584	Acc: 75.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.007,261	LR: 0.000988	Loss: 0.653	Acc: 75.0000	 Speed: 1590.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.034,262	LR: 0.000988	Loss: 0.693	Acc: 37.5000	 Speed: 1997.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.060,263	LR: 0.000988	Loss: 0.646	Acc: 50.0000	 Speed: 2239.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.087,264	LR: 0.000988	Loss: 0.560	Acc: 87.5000	 Speed: 1609.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.114,265	LR: 0.000988	Loss: 0.626	Acc: 75.0000	 Speed: 1575.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.141,266	LR: 0.000987	Loss: 0.657	Acc: 100.0000	 Speed: 400.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 47.297	Speed: 3793.1061 samples/s	Time: 0.02s
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.168,267	LR: 0.000987	Loss: 0.710	Acc: 37.5000	 Speed: 52.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.195,268	LR: 0.000987	Loss: 0.703	Acc: 62.5000	 Speed: 1979.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.221,269	LR: 0.000987	Loss: 0.666	Acc: 62.5000	 Speed: 1706.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.248,270	LR: 0.000987	Loss: 0.630	Acc: 62.5000	 Speed: 2341.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.275,271	LR: 0.000987	Loss: 0.619	Acc: 62.5000	 Speed: 2119.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.302,272	LR: 0.000987	Loss: 0.639	Acc: 50.0000	 Speed: 1913.57 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.329,273	LR: 0.000987	Loss: 0.643	Acc: 50.0000	 Speed: 1678.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.356,274	LR: 0.000987	Loss: 0.662	Acc: 62.5000	 Speed: 1939.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.383,275	LR: 0.000987	Loss: 0.623	Acc: 62.5000	 Speed: 1955.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.409,276	LR: 0.000987	Loss: 0.669	Acc: 37.5000	 Speed: 1480.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.436,277	LR: 0.000986	Loss: 0.716	Acc: 37.5000	 Speed: 1716.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.463,278	LR: 0.000986	Loss: 0.728	Acc: 50.0000	 Speed: 1315.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.490,279	LR: 0.000986	Loss: 0.628	Acc: 87.5000	 Speed: 2213.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.517,280	LR: 0.000986	Loss: 0.577	Acc: 62.5000	 Speed: 1314.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.544,281	LR: 0.000986	Loss: 0.652	Acc: 62.5000	 Speed: 1412.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.570,282	LR: 0.000986	Loss: 0.594	Acc: 87.5000	 Speed: 1544.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.597,283	LR: 0.000986	Loss: 0.648	Acc: 62.5000	 Speed: 1527.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.624,284	LR: 0.000986	Loss: 0.620	Acc: 62.5000	 Speed: 1355.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.651,285	LR: 0.000986	Loss: 0.591	Acc: 62.5000	 Speed: 2193.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.678,286	LR: 0.000986	Loss: 0.635	Acc: 75.0000	 Speed: 2162.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.705,287	LR: 0.000985	Loss: 0.653	Acc: 50.0000	 Speed: 2251.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.732,288	LR: 0.000985	Loss: 0.657	Acc: 50.0000	 Speed: 2100.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.758,289	LR: 0.000985	Loss: 0.616	Acc: 75.0000	 Speed: 2216.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.785,290	LR: 0.000985	Loss: 0.553	Acc: 87.5000	 Speed: 2555.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.812,291	LR: 0.000985	Loss: 0.604	Acc: 75.0000	 Speed: 1142.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.839,292	LR: 0.000985	Loss: 0.580	Acc: 62.5000	 Speed: 1191.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.866,293	LR: 0.000985	Loss: 0.623	Acc: 75.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:07 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.893,294	LR: 0.000985	Loss: 0.657	Acc: 50.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.919,295	LR: 0.000985	Loss: 0.602	Acc: 75.0000	 Speed: 1676.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.946,296	LR: 0.000985	Loss: 0.632	Acc: 62.5000	 Speed: 2614.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 7.973,297	LR: 0.000984	Loss: 0.546	Acc: 87.5000	 Speed: 1705.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.000,298	LR: 0.000984	Loss: 0.658	Acc: 75.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.027,299	LR: 0.000984	Loss: 0.560	Acc: 87.5000	 Speed: 1713.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.054,300	LR: 0.000984	Loss: 0.625	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.081,301	LR: 0.000984	Loss: 0.548	Acc: 75.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.107,302	LR: 0.000984	Loss: 0.642	Acc: 50.0000	 Speed: 1419.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.134,303	LR: 0.000984	Loss: 0.765	Acc: 37.5000	 Speed: 2023.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.161,304	LR: 0.000984	Loss: 0.504	Acc: 100.0000	 Speed: 667.25 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 62.162	Speed: 3377.1666 samples/s	Time: 0.02s
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.188,305	LR: 0.000984	Loss: 0.711	Acc: 37.5000	 Speed: 49.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.215,306	LR: 0.000983	Loss: 0.528	Acc: 75.0000	 Speed: 1877.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.242,307	LR: 0.000983	Loss: 0.600	Acc: 75.0000	 Speed: 1838.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.268,308	LR: 0.000983	Loss: 0.625	Acc: 75.0000	 Speed: 1942.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.295,309	LR: 0.000983	Loss: 0.570	Acc: 62.5000	 Speed: 2262.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.322,310	LR: 0.000983	Loss: 0.770	Acc: 37.5000	 Speed: 2360.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.349,311	LR: 0.000983	Loss: 0.609	Acc: 62.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.376,312	LR: 0.000983	Loss: 0.636	Acc: 62.5000	 Speed: 1418.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.403,313	LR: 0.000983	Loss: 0.683	Acc: 50.0000	 Speed: 2015.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.430,314	LR: 0.000983	Loss: 0.627	Acc: 75.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.456,315	LR: 0.000982	Loss: 0.609	Acc: 75.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.483,316	LR: 0.000982	Loss: 0.671	Acc: 62.5000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.510,317	LR: 0.000982	Loss: 0.544	Acc: 87.5000	 Speed: 1333.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.537,318	LR: 0.000982	Loss: 0.668	Acc: 62.5000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.564,319	LR: 0.000982	Loss: 0.585	Acc: 75.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.591,320	LR: 0.000982	Loss: 0.662	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.617,321	LR: 0.000982	Loss: 0.598	Acc: 75.0000	 Speed: 1370.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.644,322	LR: 0.000982	Loss: 0.550	Acc: 87.5000	 Speed: 1997.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.671,323	LR: 0.000982	Loss: 0.606	Acc: 62.5000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.698,324	LR: 0.000981	Loss: 0.465	Acc: 87.5000	 Speed: 1777.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.725,325	LR: 0.000981	Loss: 0.483	Acc: 75.0000	 Speed: 1772.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.752,326	LR: 0.000981	Loss: 0.799	Acc: 50.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.779,327	LR: 0.000981	Loss: 0.566	Acc: 87.5000	 Speed: 1762.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.805,328	LR: 0.000981	Loss: 0.708	Acc: 62.5000	 Speed: 1886.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.832,329	LR: 0.000981	Loss: 0.568	Acc: 62.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.859,330	LR: 0.000981	Loss: 0.672	Acc: 62.5000	 Speed: 2280.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.886,331	LR: 0.000981	Loss: 0.693	Acc: 50.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.913,332	LR: 0.000981	Loss: 0.629	Acc: 75.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.940,333	LR: 0.000980	Loss: 0.571	Acc: 87.5000	 Speed: 1255.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.966,334	LR: 0.000980	Loss: 0.658	Acc: 75.0000	 Speed: 1528.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 8.993,335	LR: 0.000980	Loss: 0.625	Acc: 75.0000	 Speed: 1885.50 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.020,336	LR: 0.000980	Loss: 0.578	Acc: 75.0000	 Speed: 1017.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.047,337	LR: 0.000980	Loss: 0.611	Acc: 62.5000	 Speed: 1565.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.074,338	LR: 0.000980	Loss: 0.622	Acc: 75.0000	 Speed: 2324.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.101,339	LR: 0.000980	Loss: 0.751	Acc: 37.5000	 Speed: 2441.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.128,340	LR: 0.000980	Loss: 0.684	Acc: 37.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.154,341	LR: 0.000979	Loss: 0.739	Acc: 37.5000	 Speed: 1822.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.181,342	LR: 0.000979	Loss: 0.522	Acc: 100.0000	 Speed: 486.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3755.8810 samples/s	Time: 0.02s
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.208,343	LR: 0.000979	Loss: 0.410	Acc: 87.5000	 Speed: 53.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.235,344	LR: 0.000979	Loss: 0.401	Acc: 75.0000	 Speed: 2216.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.262,345	LR: 0.000979	Loss: 0.706	Acc: 50.0000	 Speed: 1849.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.289,346	LR: 0.000979	Loss: 0.544	Acc: 75.0000	 Speed: 1548.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.315,347	LR: 0.000979	Loss: 0.794	Acc: 50.0000	 Speed: 1504.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.342,348	LR: 0.000979	Loss: 0.563	Acc: 87.5000	 Speed: 1679.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.369,349	LR: 0.000978	Loss: 0.462	Acc: 87.5000	 Speed: 1937.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.396,350	LR: 0.000978	Loss: 0.517	Acc: 75.0000	 Speed: 1679.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.423,351	LR: 0.000978	Loss: 0.628	Acc: 75.0000	 Speed: 1711.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.450,352	LR: 0.000978	Loss: 0.688	Acc: 37.5000	 Speed: 1452.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.477,353	LR: 0.000978	Loss: 0.589	Acc: 87.5000	 Speed: 1429.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.503,354	LR: 0.000978	Loss: 0.627	Acc: 75.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.530,355	LR: 0.000978	Loss: 0.577	Acc: 75.0000	 Speed: 1711.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.557,356	LR: 0.000978	Loss: 0.582	Acc: 75.0000	 Speed: 3079.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.584,357	LR: 0.000978	Loss: 0.743	Acc: 37.5000	 Speed: 2102.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.611,358	LR: 0.000977	Loss: 0.644	Acc: 62.5000	 Speed: 1749.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.638,359	LR: 0.000977	Loss: 0.685	Acc: 37.5000	 Speed: 2397.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.664,360	LR: 0.000977	Loss: 0.702	Acc: 50.0000	 Speed: 1951.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.691,361	LR: 0.000977	Loss: 0.547	Acc: 75.0000	 Speed: 1972.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.718,362	LR: 0.000977	Loss: 0.415	Acc: 100.0000	 Speed: 1942.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.745,363	LR: 0.000977	Loss: 0.624	Acc: 62.5000	 Speed: 1950.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.772,364	LR: 0.000977	Loss: 0.579	Acc: 75.0000	 Speed: 1863.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.799,365	LR: 0.000976	Loss: 0.594	Acc: 62.5000	 Speed: 1938.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.826,366	LR: 0.000976	Loss: 0.575	Acc: 87.5000	 Speed: 1702.92 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.852,367	LR: 0.000976	Loss: 0.604	Acc: 62.5000	 Speed: 1678.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.879,368	LR: 0.000976	Loss: 0.623	Acc: 50.0000	 Speed: 1457.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.906,369	LR: 0.000976	Loss: 0.617	Acc: 75.0000	 Speed: 1774.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.933,370	LR: 0.000976	Loss: 0.597	Acc: 75.0000	 Speed: 2526.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.960,371	LR: 0.000976	Loss: 0.571	Acc: 75.0000	 Speed: 1825.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 9.987,372	LR: 0.000976	Loss: 0.698	Acc: 50.0000	 Speed: 1787.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.013,373	LR: 0.000975	Loss: 0.757	Acc: 37.5000	 Speed: 2193.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.040,374	LR: 0.000975	Loss: 0.683	Acc: 50.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.067,375	LR: 0.000975	Loss: 0.610	Acc: 62.5000	 Speed: 1598.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.094,376	LR: 0.000975	Loss: 0.554	Acc: 75.0000	 Speed: 1773.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.121,377	LR: 0.000975	Loss: 0.742	Acc: 37.5000	 Speed: 1951.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.148,378	LR: 0.000975	Loss: 0.658	Acc: 75.0000	 Speed: 2416.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.174,379	LR: 0.000975	Loss: 0.614	Acc: 75.0000	 Speed: 1573.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.201,380	LR: 0.000975	Loss: 0.479	Acc: 100.0000	 Speed: 601.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 58.108	Speed: 3632.7496 samples/s	Time: 0.02s
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.228,381	LR: 0.000974	Loss: 0.569	Acc: 75.0000	 Speed: 53.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.255,382	LR: 0.000974	Loss: 0.779	Acc: 37.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.282,383	LR: 0.000974	Loss: 0.593	Acc: 62.5000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.309,384	LR: 0.000974	Loss: 0.544	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.336,385	LR: 0.000974	Loss: 0.631	Acc: 62.5000	 Speed: 1889.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.362,386	LR: 0.000974	Loss: 0.729	Acc: 50.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.389,387	LR: 0.000974	Loss: 0.538	Acc: 87.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.416,388	LR: 0.000973	Loss: 0.629	Acc: 75.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.443,389	LR: 0.000973	Loss: 0.614	Acc: 75.0000	 Speed: 2058.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.470,390	LR: 0.000973	Loss: 0.513	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.497,391	LR: 0.000973	Loss: 0.576	Acc: 75.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.523,392	LR: 0.000973	Loss: 0.650	Acc: 62.5000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.550,393	LR: 0.000973	Loss: 0.501	Acc: 87.5000	 Speed: 1391.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.577,394	LR: 0.000973	Loss: 0.671	Acc: 37.5000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.604,395	LR: 0.000973	Loss: 0.557	Acc: 75.0000	 Speed: 1424.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.631,396	LR: 0.000972	Loss: 0.728	Acc: 25.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.658,397	LR: 0.000972	Loss: 0.692	Acc: 37.5000	 Speed: 1386.03 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.685,398	LR: 0.000972	Loss: 0.578	Acc: 62.5000	 Speed: 1932.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.711,399	LR: 0.000972	Loss: 0.576	Acc: 75.0000	 Speed: 1680.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.738,400	LR: 0.000972	Loss: 0.597	Acc: 50.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:08 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.765,401	LR: 0.000972	Loss: 0.558	Acc: 75.0000	 Speed: 1704.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.792,402	LR: 0.000972	Loss: 0.570	Acc: 87.5000	 Speed: 2362.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.819,403	LR: 0.000971	Loss: 0.521	Acc: 87.5000	 Speed: 2663.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.846,404	LR: 0.000971	Loss: 0.682	Acc: 62.5000	 Speed: 1686.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.872,405	LR: 0.000971	Loss: 0.620	Acc: 75.0000	 Speed: 2035.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.899,406	LR: 0.000971	Loss: 0.498	Acc: 87.5000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.926,407	LR: 0.000971	Loss: 0.625	Acc: 62.5000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.953,408	LR: 0.000971	Loss: 0.601	Acc: 87.5000	 Speed: 1745.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 10.980,409	LR: 0.000971	Loss: 0.649	Acc: 75.0000	 Speed: 2663.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.007,410	LR: 0.000970	Loss: 0.555	Acc: 75.0000	 Speed: 1498.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.034,411	LR: 0.000970	Loss: 0.653	Acc: 62.5000	 Speed: 1786.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.060,412	LR: 0.000970	Loss: 0.668	Acc: 62.5000	 Speed: 1824.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.087,413	LR: 0.000970	Loss: 0.571	Acc: 62.5000	 Speed: 2293.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.114,414	LR: 0.000970	Loss: 0.524	Acc: 75.0000	 Speed: 1661.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.141,415	LR: 0.000970	Loss: 0.715	Acc: 50.0000	 Speed: 1996.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.168,416	LR: 0.000970	Loss: 0.516	Acc: 100.0000	 Speed: 1550.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.195,417	LR: 0.000969	Loss: 0.660	Acc: 75.0000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.221,418	LR: 0.000969	Loss: 0.318	Acc: 100.0000	 Speed: 547.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 50.000	Speed: 3818.6801 samples/s	Time: 0.02s
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.248,419	LR: 0.000969	Loss: 0.679	Acc: 37.5000	 Speed: 52.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.275,420	LR: 0.000969	Loss: 0.519	Acc: 87.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.302,421	LR: 0.000969	Loss: 0.496	Acc: 87.5000	 Speed: 1333.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.329,422	LR: 0.000969	Loss: 0.554	Acc: 75.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.356,423	LR: 0.000969	Loss: 0.426	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.383,424	LR: 0.000968	Loss: 0.683	Acc: 50.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.409,425	LR: 0.000968	Loss: 0.575	Acc: 62.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.436,426	LR: 0.000968	Loss: 0.740	Acc: 37.5000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.463,427	LR: 0.000968	Loss: 0.654	Acc: 75.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.490,428	LR: 0.000968	Loss: 0.580	Acc: 62.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.517,429	LR: 0.000968	Loss: 0.620	Acc: 62.5000	 Speed: 1976.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.544,430	LR: 0.000967	Loss: 0.630	Acc: 75.0000	 Speed: 1333.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.570,431	LR: 0.000967	Loss: 0.676	Acc: 37.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.597,432	LR: 0.000967	Loss: 0.570	Acc: 75.0000	 Speed: 1314.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.624,433	LR: 0.000967	Loss: 0.715	Acc: 50.0000	 Speed: 1507.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.651,434	LR: 0.000967	Loss: 0.501	Acc: 87.5000	 Speed: 1333.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.678,435	LR: 0.000967	Loss: 0.471	Acc: 75.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.705,436	LR: 0.000967	Loss: 0.778	Acc: 37.5000	 Speed: 2662.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.732,437	LR: 0.000966	Loss: 0.527	Acc: 100.0000	 Speed: 1683.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.758,438	LR: 0.000966	Loss: 0.558	Acc: 75.0000	 Speed: 1598.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.785,439	LR: 0.000966	Loss: 0.652	Acc: 62.5000	 Speed: 1933.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.812,440	LR: 0.000966	Loss: 0.570	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.839,441	LR: 0.000966	Loss: 0.558	Acc: 75.0000	 Speed: 1899.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.866,442	LR: 0.000966	Loss: 0.602	Acc: 62.5000	 Speed: 2188.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.893,443	LR: 0.000966	Loss: 0.597	Acc: 75.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.919,444	LR: 0.000965	Loss: 0.622	Acc: 75.0000	 Speed: 1943.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.946,445	LR: 0.000965	Loss: 0.517	Acc: 87.5000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 11.973,446	LR: 0.000965	Loss: 0.741	Acc: 50.0000	 Speed: 2092.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.000,447	LR: 0.000965	Loss: 0.730	Acc: 25.0000	 Speed: 1916.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.027,448	LR: 0.000965	Loss: 0.574	Acc: 75.0000	 Speed: 1680.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.054,449	LR: 0.000965	Loss: 0.513	Acc: 75.0000	 Speed: 1057.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.081,450	LR: 0.000964	Loss: 0.478	Acc: 87.5000	 Speed: 2013.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.107,451	LR: 0.000964	Loss: 0.572	Acc: 75.0000	 Speed: 2183.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.134,452	LR: 0.000964	Loss: 0.600	Acc: 75.0000	 Speed: 1516.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.161,453	LR: 0.000964	Loss: 0.492	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.188,454	LR: 0.000964	Loss: 0.546	Acc: 75.0000	 Speed: 2269.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.215,455	LR: 0.000964	Loss: 0.662	Acc: 62.5000	 Speed: 2196.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.242,456	LR: 0.000963	Loss: 0.617	Acc: 50.0000	 Speed: 662.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 58.108	Speed: 3587.6930 samples/s	Time: 0.02s
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.268,457	LR: 0.000963	Loss: 0.694	Acc: 50.0000	 Speed: 51.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.295,458	LR: 0.000963	Loss: 0.645	Acc: 50.0000	 Speed: 1969.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.322,459	LR: 0.000963	Loss: 0.560	Acc: 75.0000	 Speed: 1881.59 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.349,460	LR: 0.000963	Loss: 0.517	Acc: 75.0000	 Speed: 2232.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.376,461	LR: 0.000963	Loss: 0.658	Acc: 50.0000	 Speed: 2604.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.403,462	LR: 0.000963	Loss: 0.560	Acc: 75.0000	 Speed: 2208.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.430,463	LR: 0.000962	Loss: 0.579	Acc: 62.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.456,464	LR: 0.000962	Loss: 0.527	Acc: 75.0000	 Speed: 1354.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.483,465	LR: 0.000962	Loss: 0.603	Acc: 75.0000	 Speed: 2387.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.510,466	LR: 0.000962	Loss: 0.445	Acc: 100.0000	 Speed: 1997.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.537,467	LR: 0.000962	Loss: 0.449	Acc: 87.5000	 Speed: 1501.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.564,468	LR: 0.000962	Loss: 0.657	Acc: 75.0000	 Speed: 2520.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.591,469	LR: 0.000961	Loss: 0.535	Acc: 87.5000	 Speed: 1740.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.617,470	LR: 0.000961	Loss: 0.528	Acc: 87.5000	 Speed: 1910.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.644,471	LR: 0.000961	Loss: 0.477	Acc: 87.5000	 Speed: 1672.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.671,472	LR: 0.000961	Loss: 0.583	Acc: 75.0000	 Speed: 2198.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.698,473	LR: 0.000961	Loss: 0.703	Acc: 50.0000	 Speed: 1915.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.725,474	LR: 0.000961	Loss: 0.716	Acc: 50.0000	 Speed: 1940.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.752,475	LR: 0.000960	Loss: 0.657	Acc: 50.0000	 Speed: 1305.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.779,476	LR: 0.000960	Loss: 0.485	Acc: 100.0000	 Speed: 2164.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.805,477	LR: 0.000960	Loss: 0.455	Acc: 75.0000	 Speed: 2052.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.832,478	LR: 0.000960	Loss: 0.539	Acc: 75.0000	 Speed: 1642.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.859,479	LR: 0.000960	Loss: 0.602	Acc: 75.0000	 Speed: 1378.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.886,480	LR: 0.000960	Loss: 0.569	Acc: 75.0000	 Speed: 1400.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.913,481	LR: 0.000959	Loss: 0.595	Acc: 62.5000	 Speed: 1384.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.940,482	LR: 0.000959	Loss: 0.671	Acc: 50.0000	 Speed: 1997.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.966,483	LR: 0.000959	Loss: 0.512	Acc: 87.5000	 Speed: 1896.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 12.993,484	LR: 0.000959	Loss: 0.573	Acc: 75.0000	 Speed: 2223.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.020,485	LR: 0.000959	Loss: 0.672	Acc: 50.0000	 Speed: 2155.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.047,486	LR: 0.000959	Loss: 0.571	Acc: 75.0000	 Speed: 1931.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.074,487	LR: 0.000958	Loss: 0.595	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.101,488	LR: 0.000958	Loss: 0.574	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.128,489	LR: 0.000958	Loss: 0.588	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.154,490	LR: 0.000958	Loss: 0.574	Acc: 62.5000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.181,491	LR: 0.000958	Loss: 0.639	Acc: 50.0000	 Speed: 1739.29 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.208,492	LR: 0.000958	Loss: 0.497	Acc: 100.0000	 Speed: 1927.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.235,493	LR: 0.000957	Loss: 0.388	Acc: 100.0000	 Speed: 1598.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.262,494	LR: 0.000957	Loss: 0.272	Acc: 100.0000	 Speed: 500.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 60.811	Speed: 3687.0374 samples/s	Time: 0.02s
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.289,495	LR: 0.000957	Loss: 0.442	Acc: 87.5000	 Speed: 53.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.315,496	LR: 0.000957	Loss: 0.415	Acc: 100.0000	 Speed: 2428.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.342,497	LR: 0.000957	Loss: 0.566	Acc: 50.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.369,498	LR: 0.000957	Loss: 0.488	Acc: 87.5000	 Speed: 892.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.396,499	LR: 0.000956	Loss: 0.576	Acc: 75.0000	 Speed: 1626.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.423,500	LR: 0.000956	Loss: 0.552	Acc: 87.5000	 Speed: 1912.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.450,501	LR: 0.000956	Loss: 0.586	Acc: 75.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.477,502	LR: 0.000956	Loss: 0.723	Acc: 37.5000	 Speed: 2166.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.503,503	LR: 0.000956	Loss: 0.482	Acc: 87.5000	 Speed: 2498.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.530,504	LR: 0.000956	Loss: 0.631	Acc: 62.5000	 Speed: 1883.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.557,505	LR: 0.000955	Loss: 0.507	Acc: 75.0000	 Speed: 1757.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.584,506	LR: 0.000955	Loss: 0.613	Acc: 50.0000	 Speed: 1731.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.611,507	LR: 0.000955	Loss: 0.617	Acc: 62.5000	 Speed: 2306.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.638,508	LR: 0.000955	Loss: 0.435	Acc: 87.5000	 Speed: 2348.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.664,509	LR: 0.000955	Loss: 0.498	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.691,510	LR: 0.000954	Loss: 0.674	Acc: 37.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:09 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.718,511	LR: 0.000954	Loss: 0.628	Acc: 50.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.745,512	LR: 0.000954	Loss: 0.681	Acc: 50.0000	 Speed: 1710.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.772,513	LR: 0.000954	Loss: 0.631	Acc: 62.5000	 Speed: 1142.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.799,514	LR: 0.000954	Loss: 0.478	Acc: 87.5000	 Speed: 1684.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.826,515	LR: 0.000954	Loss: 0.574	Acc: 62.5000	 Speed: 1599.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.852,516	LR: 0.000953	Loss: 0.572	Acc: 87.5000	 Speed: 2071.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.879,517	LR: 0.000953	Loss: 0.556	Acc: 75.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.906,518	LR: 0.000953	Loss: 0.562	Acc: 75.0000	 Speed: 2300.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.933,519	LR: 0.000953	Loss: 0.596	Acc: 62.5000	 Speed: 1899.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.960,520	LR: 0.000953	Loss: 0.593	Acc: 62.5000	 Speed: 1239.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 13.987,521	LR: 0.000953	Loss: 0.534	Acc: 87.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.013,522	LR: 0.000952	Loss: 0.596	Acc: 62.5000	 Speed: 1333.38 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.040,523	LR: 0.000952	Loss: 0.519	Acc: 87.5000	 Speed: 1505.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.067,524	LR: 0.000952	Loss: 0.587	Acc: 62.5000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.094,525	LR: 0.000952	Loss: 0.477	Acc: 100.0000	 Speed: 1583.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.121,526	LR: 0.000952	Loss: 0.437	Acc: 87.5000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.148,527	LR: 0.000951	Loss: 0.510	Acc: 75.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.174,528	LR: 0.000951	Loss: 0.410	Acc: 87.5000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.201,529	LR: 0.000951	Loss: 0.598	Acc: 62.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.228,530	LR: 0.000951	Loss: 0.694	Acc: 50.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.255,531	LR: 0.000951	Loss: 0.507	Acc: 75.0000	 Speed: 2001.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.282,532	LR: 0.000951	Loss: 0.342	Acc: 100.0000	 Speed: 666.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 59.459	Speed: 3858.7013 samples/s	Time: 0.02s
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.309,533	LR: 0.000950	Loss: 0.597	Acc: 62.5000	 Speed: 53.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.336,534	LR: 0.000950	Loss: 0.518	Acc: 75.0000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.362,535	LR: 0.000950	Loss: 0.380	Acc: 100.0000	 Speed: 2073.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.389,536	LR: 0.000950	Loss: 0.667	Acc: 50.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.416,537	LR: 0.000950	Loss: 0.529	Acc: 75.0000	 Speed: 1816.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.443,538	LR: 0.000949	Loss: 0.585	Acc: 75.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.470,539	LR: 0.000949	Loss: 0.614	Acc: 62.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.497,540	LR: 0.000949	Loss: 0.576	Acc: 62.5000	 Speed: 2264.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.523,541	LR: 0.000949	Loss: 0.474	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.550,542	LR: 0.000949	Loss: 0.448	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.577,543	LR: 0.000948	Loss: 0.651	Acc: 50.0000	 Speed: 2662.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.604,544	LR: 0.000948	Loss: 0.588	Acc: 62.5000	 Speed: 1627.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.631,545	LR: 0.000948	Loss: 0.432	Acc: 100.0000	 Speed: 1909.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.658,546	LR: 0.000948	Loss: 0.475	Acc: 62.5000	 Speed: 1524.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.685,547	LR: 0.000948	Loss: 0.688	Acc: 62.5000	 Speed: 1713.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.711,548	LR: 0.000948	Loss: 0.457	Acc: 87.5000	 Speed: 1774.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.738,549	LR: 0.000947	Loss: 0.543	Acc: 75.0000	 Speed: 1599.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.765,550	LR: 0.000947	Loss: 0.613	Acc: 62.5000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.792,551	LR: 0.000947	Loss: 0.485	Acc: 87.5000	 Speed: 2661.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.819,552	LR: 0.000947	Loss: 0.514	Acc: 75.0000	 Speed: 2290.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.846,553	LR: 0.000947	Loss: 0.481	Acc: 87.5000	 Speed: 1429.49 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.872,554	LR: 0.000946	Loss: 0.488	Acc: 87.5000	 Speed: 2007.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.899,555	LR: 0.000946	Loss: 0.503	Acc: 75.0000	 Speed: 1142.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.926,556	LR: 0.000946	Loss: 0.526	Acc: 75.0000	 Speed: 1291.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.953,557	LR: 0.000946	Loss: 0.535	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 14.980,558	LR: 0.000946	Loss: 0.719	Acc: 62.5000	 Speed: 1542.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.007,559	LR: 0.000945	Loss: 0.385	Acc: 100.0000	 Speed: 1397.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.034,560	LR: 0.000945	Loss: 0.602	Acc: 62.5000	 Speed: 1528.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.060,561	LR: 0.000945	Loss: 0.590	Acc: 75.0000	 Speed: 1772.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.087,562	LR: 0.000945	Loss: 0.459	Acc: 87.5000	 Speed: 1946.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.114,563	LR: 0.000945	Loss: 0.481	Acc: 75.0000	 Speed: 1773.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.141,564	LR: 0.000944	Loss: 0.631	Acc: 62.5000	 Speed: 2841.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.168,565	LR: 0.000944	Loss: 0.584	Acc: 75.0000	 Speed: 2277.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.195,566	LR: 0.000944	Loss: 0.493	Acc: 87.5000	 Speed: 1770.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.221,567	LR: 0.000944	Loss: 0.507	Acc: 75.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.248,568	LR: 0.000944	Loss: 0.506	Acc: 75.0000	 Speed: 1943.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.275,569	LR: 0.000944	Loss: 0.501	Acc: 87.5000	 Speed: 1501.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.302,570	LR: 0.000943	Loss: 0.628	Acc: 50.0000	 Speed: 499.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 58.108	Speed: 3459.5282 samples/s	Time: 0.02s
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.329,571	LR: 0.000943	Loss: 0.572	Acc: 75.0000	 Speed: 51.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.356,572	LR: 0.000943	Loss: 0.404	Acc: 100.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.383,573	LR: 0.000943	Loss: 0.419	Acc: 87.5000	 Speed: 2261.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.409,574	LR: 0.000943	Loss: 0.492	Acc: 87.5000	 Speed: 1619.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.436,575	LR: 0.000942	Loss: 0.527	Acc: 62.5000	 Speed: 2015.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.463,576	LR: 0.000942	Loss: 0.457	Acc: 87.5000	 Speed: 1131.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.490,577	LR: 0.000942	Loss: 0.571	Acc: 87.5000	 Speed: 1246.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.517,578	LR: 0.000942	Loss: 0.572	Acc: 87.5000	 Speed: 1887.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.544,579	LR: 0.000942	Loss: 0.618	Acc: 62.5000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.570,580	LR: 0.000941	Loss: 0.526	Acc: 87.5000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.597,581	LR: 0.000941	Loss: 0.551	Acc: 62.5000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.624,582	LR: 0.000941	Loss: 0.589	Acc: 62.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.651,583	LR: 0.000941	Loss: 0.425	Acc: 87.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.678,584	LR: 0.000941	Loss: 0.528	Acc: 75.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.705,585	LR: 0.000940	Loss: 0.461	Acc: 75.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.732,586	LR: 0.000940	Loss: 0.570	Acc: 62.5000	 Speed: 2218.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.758,587	LR: 0.000940	Loss: 0.468	Acc: 87.5000	 Speed: 1911.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.785,588	LR: 0.000940	Loss: 0.560	Acc: 87.5000	 Speed: 2251.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.812,589	LR: 0.000940	Loss: 0.574	Acc: 62.5000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.839,590	LR: 0.000939	Loss: 0.489	Acc: 87.5000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.866,591	LR: 0.000939	Loss: 0.459	Acc: 87.5000	 Speed: 2352.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.893,592	LR: 0.000939	Loss: 0.469	Acc: 87.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.919,593	LR: 0.000939	Loss: 0.322	Acc: 100.0000	 Speed: 1087.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.946,594	LR: 0.000939	Loss: 0.538	Acc: 75.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 15.973,595	LR: 0.000938	Loss: 0.473	Acc: 87.5000	 Speed: 1929.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.000,596	LR: 0.000938	Loss: 0.503	Acc: 75.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.027,597	LR: 0.000938	Loss: 0.640	Acc: 62.5000	 Speed: 1919.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.054,598	LR: 0.000938	Loss: 0.508	Acc: 75.0000	 Speed: 2277.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.081,599	LR: 0.000938	Loss: 0.671	Acc: 62.5000	 Speed: 1715.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.107,600	LR: 0.000937	Loss: 0.459	Acc: 87.5000	 Speed: 1828.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.134,601	LR: 0.000937	Loss: 0.503	Acc: 87.5000	 Speed: 1852.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.161,602	LR: 0.000937	Loss: 0.459	Acc: 75.0000	 Speed: 1643.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.188,603	LR: 0.000937	Loss: 0.479	Acc: 87.5000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.215,604	LR: 0.000937	Loss: 0.499	Acc: 75.0000	 Speed: 2656.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.242,605	LR: 0.000936	Loss: 0.483	Acc: 87.5000	 Speed: 1703.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.268,606	LR: 0.000936	Loss: 0.544	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.295,607	LR: 0.000936	Loss: 0.385	Acc: 87.5000	 Speed: 2115.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.322,608	LR: 0.000936	Loss: 0.944	Acc: 50.0000	 Speed: 569.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 59.459	Speed: 3528.8329 samples/s	Time: 0.02s
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.349,609	LR: 0.000935	Loss: 0.609	Acc: 75.0000	 Speed: 50.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.376,610	LR: 0.000935	Loss: 0.604	Acc: 62.5000	 Speed: 2164.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.403,611	LR: 0.000935	Loss: 0.513	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.430,612	LR: 0.000935	Loss: 0.523	Acc: 87.5000	 Speed: 1985.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.456,613	LR: 0.000935	Loss: 0.444	Acc: 87.5000	 Speed: 1805.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.483,614	LR: 0.000934	Loss: 0.520	Acc: 75.0000	 Speed: 2084.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.510,615	LR: 0.000934	Loss: 0.595	Acc: 62.5000	 Speed: 1703.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.537,616	LR: 0.000934	Loss: 0.503	Acc: 87.5000	 Speed: 1997.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.564,617	LR: 0.000934	Loss: 0.593	Acc: 75.0000	 Speed: 1919.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.591,618	LR: 0.000934	Loss: 0.476	Acc: 75.0000	 Speed: 1568.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.617,619	LR: 0.000933	Loss: 0.493	Acc: 87.5000	 Speed: 1911.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:10 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.644,620	LR: 0.000933	Loss: 0.519	Acc: 75.0000	 Speed: 1558.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.671,621	LR: 0.000933	Loss: 0.557	Acc: 75.0000	 Speed: 1891.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.698,622	LR: 0.000933	Loss: 0.521	Acc: 75.0000	 Speed: 2571.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.725,623	LR: 0.000933	Loss: 0.432	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.752,624	LR: 0.000932	Loss: 0.460	Acc: 100.0000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.779,625	LR: 0.000932	Loss: 0.444	Acc: 87.5000	 Speed: 1835.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.805,626	LR: 0.000932	Loss: 0.582	Acc: 87.5000	 Speed: 1884.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.832,627	LR: 0.000932	Loss: 0.231	Acc: 100.0000	 Speed: 1766.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.859,628	LR: 0.000931	Loss: 0.439	Acc: 87.5000	 Speed: 1838.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.886,629	LR: 0.000931	Loss: 0.707	Acc: 37.5000	 Speed: 1814.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.913,630	LR: 0.000931	Loss: 0.443	Acc: 87.5000	 Speed: 2118.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.940,631	LR: 0.000931	Loss: 0.473	Acc: 75.0000	 Speed: 1701.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.966,632	LR: 0.000931	Loss: 0.471	Acc: 87.5000	 Speed: 1952.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 16.993,633	LR: 0.000930	Loss: 0.525	Acc: 75.0000	 Speed: 1713.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.020,634	LR: 0.000930	Loss: 0.321	Acc: 100.0000	 Speed: 1864.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.047,635	LR: 0.000930	Loss: 0.561	Acc: 62.5000	 Speed: 1649.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.074,636	LR: 0.000930	Loss: 0.493	Acc: 87.5000	 Speed: 2805.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.101,637	LR: 0.000930	Loss: 0.552	Acc: 62.5000	 Speed: 1712.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.128,638	LR: 0.000929	Loss: 0.530	Acc: 87.5000	 Speed: 1780.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.154,639	LR: 0.000929	Loss: 0.406	Acc: 100.0000	 Speed: 1780.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.181,640	LR: 0.000929	Loss: 0.612	Acc: 62.5000	 Speed: 1940.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.208,641	LR: 0.000929	Loss: 0.492	Acc: 87.5000	 Speed: 1265.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.235,642	LR: 0.000928	Loss: 0.465	Acc: 75.0000	 Speed: 1546.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.262,643	LR: 0.000928	Loss: 0.569	Acc: 87.5000	 Speed: 1205.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.289,644	LR: 0.000928	Loss: 0.575	Acc: 62.5000	 Speed: 1988.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.315,645	LR: 0.000928	Loss: 0.449	Acc: 87.5000	 Speed: 1889.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.342,646	LR: 0.000928	Loss: 0.303	Acc: 100.0000	 Speed: 459.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 62.162	Speed: 3829.6584 samples/s	Time: 0.02s

[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.369,647	LR: 0.000927	Loss: 0.492	Acc: 87.5000	 Speed: 52.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.396,648	LR: 0.000927	Loss: 0.434	Acc: 100.0000	 Speed: 2022.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.423,649	LR: 0.000927	Loss: 0.383	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.450,650	LR: 0.000927	Loss: 0.355	Acc: 87.5000	 Speed: 2150.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.477,651	LR: 0.000927	Loss: 0.432	Acc: 75.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.503,652	LR: 0.000926	Loss: 0.687	Acc: 62.5000	 Speed: 1792.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.530,653	LR: 0.000926	Loss: 0.557	Acc: 62.5000	 Speed: 1741.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.557,654	LR: 0.000926	Loss: 0.597	Acc: 62.5000	 Speed: 2119.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.584,655	LR: 0.000926	Loss: 0.340	Acc: 100.0000	 Speed: 2176.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.611,656	LR: 0.000925	Loss: 0.552	Acc: 87.5000	 Speed: 1775.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.638,657	LR: 0.000925	Loss: 0.539	Acc: 75.0000	 Speed: 1751.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.664,658	LR: 0.000925	Loss: 0.472	Acc: 87.5000	 Speed: 1997.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.691,659	LR: 0.000925	Loss: 0.446	Acc: 100.0000	 Speed: 1837.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.718,660	LR: 0.000925	Loss: 0.490	Acc: 87.5000	 Speed: 2264.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.745,661	LR: 0.000924	Loss: 0.440	Acc: 100.0000	 Speed: 2660.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.772,662	LR: 0.000924	Loss: 0.443	Acc: 87.5000	 Speed: 1811.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.799,663	LR: 0.000924	Loss: 0.397	Acc: 100.0000	 Speed: 1946.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.826,664	LR: 0.000924	Loss: 0.645	Acc: 62.5000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.852,665	LR: 0.000923	Loss: 0.444	Acc: 100.0000	 Speed: 1400.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.879,666	LR: 0.000923	Loss: 0.531	Acc: 62.5000	 Speed: 1667.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.906,667	LR: 0.000923	Loss: 0.556	Acc: 62.5000	 Speed: 2110.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.933,668	LR: 0.000923	Loss: 0.407	Acc: 87.5000	 Speed: 2341.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.960,669	LR: 0.000923	Loss: 0.628	Acc: 37.5000	 Speed: 1477.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 17.987,670	LR: 0.000922	Loss: 0.485	Acc: 87.5000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.013,671	LR: 0.000922	Loss: 0.469	Acc: 87.5000	 Speed: 1761.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.040,672	LR: 0.000922	Loss: 0.481	Acc: 87.5000	 Speed: 1258.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.067,673	LR: 0.000922	Loss: 0.249	Acc: 100.0000	 Speed: 1833.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.094,674	LR: 0.000921	Loss: 0.468	Acc: 87.5000	 Speed: 1690.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.121,675	LR: 0.000921	Loss: 0.472	Acc: 87.5000	 Speed: 1893.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.148,676	LR: 0.000921	Loss: 0.498	Acc: 62.5000	 Speed: 2687.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.174,677	LR: 0.000921	Loss: 0.449	Acc: 87.5000	 Speed: 1652.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.201,678	LR: 0.000920	Loss: 0.569	Acc: 75.0000	 Speed: 2427.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.228,679	LR: 0.000920	Loss: 0.427	Acc: 75.0000	 Speed: 2031.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.255,680	LR: 0.000920	Loss: 0.445	Acc: 87.5000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.282,681	LR: 0.000920	Loss: 0.473	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.309,682	LR: 0.000920	Loss: 0.392	Acc: 87.5000	 Speed: 2208.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.336,683	LR: 0.000919	Loss: 0.522	Acc: 75.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.362,684	LR: 0.000919	Loss: 0.371	Acc: 100.0000	 Speed: 665.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 60.811	Speed: 3363.5521 samples/s	Time: 0.02s
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.389,685	LR: 0.000919	Loss: 0.407	Acc: 87.5000	 Speed: 53.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.416,686	LR: 0.000919	Loss: 0.362	Acc: 87.5000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.443,687	LR: 0.000918	Loss: 0.689	Acc: 62.5000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.470,688	LR: 0.000918	Loss: 0.300	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.497,689	LR: 0.000918	Loss: 0.637	Acc: 50.0000	 Speed: 2665.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.523,690	LR: 0.000918	Loss: 0.330	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.550,691	LR: 0.000917	Loss: 0.453	Acc: 87.5000	 Speed: 2665.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.577,692	LR: 0.000917	Loss: 0.596	Acc: 62.5000	 Speed: 2669.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.604,693	LR: 0.000917	Loss: 0.529	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.631,694	LR: 0.000917	Loss: 0.356	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.658,695	LR: 0.000917	Loss: 0.470	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.685,696	LR: 0.000916	Loss: 0.372	Acc: 100.0000	 Speed: 2668.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.711,697	LR: 0.000916	Loss: 0.638	Acc: 50.0000	 Speed: 1601.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.738,698	LR: 0.000916	Loss: 0.394	Acc: 87.5000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.765,699	LR: 0.000916	Loss: 0.472	Acc: 87.5000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.792,700	LR: 0.000915	Loss: 0.424	Acc: 87.5000	 Speed: 1142.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.819,701	LR: 0.000915	Loss: 0.496	Acc: 75.0000	 Speed: 1777.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.846,702	LR: 0.000915	Loss: 0.372	Acc: 100.0000	 Speed: 1597.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.872,703	LR: 0.000915	Loss: 0.329	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.899,704	LR: 0.000914	Loss: 0.412	Acc: 100.0000	 Speed: 2666.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.926,705	LR: 0.000914	Loss: 0.424	Acc: 100.0000	 Speed: 1599.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.953,706	LR: 0.000914	Loss: 0.403	Acc: 87.5000	 Speed: 1600.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 18.980,707	LR: 0.000914	Loss: 0.394	Acc: 87.5000	 Speed: 1333.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.007,708	LR: 0.000913	Loss: 0.576	Acc: 75.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.034,709	LR: 0.000913	Loss: 0.541	Acc: 62.5000	 Speed: 1998.83 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.060,710	LR: 0.000913	Loss: 0.627	Acc: 75.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.087,711	LR: 0.000913	Loss: 0.423	Acc: 87.5000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.114,712	LR: 0.000913	Loss: 0.530	Acc: 75.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.141,713	LR: 0.000912	Loss: 0.491	Acc: 75.0000	 Speed: 1997.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.168,714	LR: 0.000912	Loss: 0.429	Acc: 87.5000	 Speed: 2664.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.195,715	LR: 0.000912	Loss: 0.506	Acc: 87.5000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.221,716	LR: 0.000912	Loss: 0.480	Acc: 75.0000	 Speed: 1599.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.248,717	LR: 0.000911	Loss: 0.588	Acc: 62.5000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.275,718	LR: 0.000911	Loss: 0.526	Acc: 87.5000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.302,719	LR: 0.000911	Loss: 0.412	Acc: 75.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.329,720	LR: 0.000911	Loss: 0.527	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.356,721	LR: 0.000910	Loss: 0.419	Acc: 87.5000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.383,722	LR: 0.000910	Loss: 0.398	Acc: 100.0000	 Speed: 500.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3718.6665 samples/s	Time: 0.02s
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.409,723	LR: 0.000910	Loss: 0.409	Acc: 75.0000	 Speed: 51.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.436,724	LR: 0.000910	Loss: 0.313	Acc: 87.5000	 Speed: 2001.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.463,725	LR: 0.000909	Loss: 0.314	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.490,726	LR: 0.000909	Loss: 0.488	Acc: 75.0000	 Speed: 1333.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.517,727	LR: 0.000909	Loss: 0.286	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.544,728	LR: 0.000909	Loss: 0.545	Acc: 50.0000	 Speed: 1723.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.570,729	LR: 0.000908	Loss: 0.523	Acc: 62.5000	 Speed: 1132.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.597,730	LR: 0.000908	Loss: 0.440	Acc: 87.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.624,731	LR: 0.000908	Loss: 0.360	Acc: 100.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.651,732	LR: 0.000908	Loss: 0.324	Acc: 100.0000	 Speed: 1897.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:11 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.678,733	LR: 0.000907	Loss: 0.328	Acc: 87.5000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.705,734	LR: 0.000907	Loss: 0.416	Acc: 87.5000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.732,735	LR: 0.000907	Loss: 0.573	Acc: 75.0000	 Speed: 1772.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.758,736	LR: 0.000907	Loss: 0.412	Acc: 87.5000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.785,737	LR: 0.000906	Loss: 0.382	Acc: 87.5000	 Speed: 1333.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.812,738	LR: 0.000906	Loss: 0.446	Acc: 87.5000	 Speed: 1599.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.839,739	LR: 0.000906	Loss: 0.493	Acc: 75.0000	 Speed: 1787.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.866,740	LR: 0.000906	Loss: 0.310	Acc: 100.0000	 Speed: 1598.59 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.893,741	LR: 0.000905	Loss: 0.287	Acc: 100.0000	 Speed: 2284.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.919,742	LR: 0.000905	Loss: 0.443	Acc: 75.0000	 Speed: 2002.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.946,743	LR: 0.000905	Loss: 0.434	Acc: 87.5000	 Speed: 1997.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 19.973,744	LR: 0.000905	Loss: 0.471	Acc: 87.5000	 Speed: 2394.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.000,745	LR: 0.000905	Loss: 0.672	Acc: 75.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.027,746	LR: 0.000904	Loss: 0.507	Acc: 75.0000	 Speed: 1604.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.054,747	LR: 0.000904	Loss: 0.542	Acc: 50.0000	 Speed: 1536.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.081,748	LR: 0.000904	Loss: 0.625	Acc: 62.5000	 Speed: 1757.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.107,749	LR: 0.000904	Loss: 0.687	Acc: 37.5000	 Speed: 2157.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.134,750	LR: 0.000903	Loss: 0.417	Acc: 75.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.161,751	LR: 0.000903	Loss: 0.569	Acc: 75.0000	 Speed: 2159.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.188,752	LR: 0.000903	Loss: 0.288	Acc: 100.0000	 Speed: 2064.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.215,753	LR: 0.000903	Loss: 0.605	Acc: 75.0000	 Speed: 2169.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.242,754	LR: 0.000902	Loss: 0.477	Acc: 75.0000	 Speed: 1774.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.268,755	LR: 0.000902	Loss: 0.556	Acc: 62.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.295,756	LR: 0.000902	Loss: 0.591	Acc: 62.5000	 Speed: 2559.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.322,757	LR: 0.000902	Loss: 0.357	Acc: 100.0000	 Speed: 1848.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.349,758	LR: 0.000901	Loss: 0.332	Acc: 100.0000	 Speed: 1793.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.376,759	LR: 0.000901	Loss: 0.344	Acc: 100.0000	 Speed: 1651.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.403,760	LR: 0.000901	Loss: 0.405	Acc: 100.0000	 Speed: 509.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 51.351	Speed: 3526.5475 samples/s	Time: 0.02s
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.430,761	LR: 0.000901	Loss: 0.292	Acc: 100.0000	 Speed: 51.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.456,762	LR: 0.000900	Loss: 0.466	Acc: 87.5000	 Speed: 2278.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.483,763	LR: 0.000900	Loss: 0.256	Acc: 100.0000	 Speed: 1838.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.510,764	LR: 0.000900	Loss: 0.498	Acc: 87.5000	 Speed: 1714.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.537,765	LR: 0.000899	Loss: 0.370	Acc: 100.0000	 Speed: 2174.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.564,766	LR: 0.000899	Loss: 0.444	Acc: 75.0000	 Speed: 1512.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.591,767	LR: 0.000899	Loss: 0.465	Acc: 100.0000	 Speed: 1332.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.617,768	LR: 0.000899	Loss: 0.703	Acc: 50.0000	 Speed: 1854.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.644,769	LR: 0.000898	Loss: 0.401	Acc: 100.0000	 Speed: 1293.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.671,770	LR: 0.000898	Loss: 0.365	Acc: 100.0000	 Speed: 1857.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.698,771	LR: 0.000898	Loss: 0.434	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.725,772	LR: 0.000898	Loss: 0.549	Acc: 75.0000	 Speed: 2724.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.752,773	LR: 0.000897	Loss: 0.413	Acc: 75.0000	 Speed: 1852.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.779,774	LR: 0.000897	Loss: 0.414	Acc: 87.5000	 Speed: 1899.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.805,775	LR: 0.000897	Loss: 0.410	Acc: 87.5000	 Speed: 1907.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.832,776	LR: 0.000897	Loss: 0.290	Acc: 87.5000	 Speed: 1873.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.859,777	LR: 0.000896	Loss: 0.405	Acc: 100.0000	 Speed: 1748.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.886,778	LR: 0.000896	Loss: 0.502	Acc: 62.5000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.913,779	LR: 0.000896	Loss: 0.636	Acc: 75.0000	 Speed: 1972.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.940,780	LR: 0.000896	Loss: 0.290	Acc: 100.0000	 Speed: 2094.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.966,781	LR: 0.000895	Loss: 0.273	Acc: 100.0000	 Speed: 2161.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 20.993,782	LR: 0.000895	Loss: 0.347	Acc: 100.0000	 Speed: 1679.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.020,783	LR: 0.000895	Loss: 0.483	Acc: 62.5000	 Speed: 2111.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.047,784	LR: 0.000895	Loss: 0.461	Acc: 75.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.074,785	LR: 0.000894	Loss: 0.452	Acc: 75.0000	 Speed: 2023.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.101,786	LR: 0.000894	Loss: 0.321	Acc: 100.0000	 Speed: 1865.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.128,787	LR: 0.000894	Loss: 0.466	Acc: 75.0000	 Speed: 2421.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.154,788	LR: 0.000894	Loss: 0.308	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.181,789	LR: 0.000893	Loss: 0.604	Acc: 75.0000	 Speed: 1810.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.208,790	LR: 0.000893	Loss: 0.619	Acc: 75.0000	 Speed: 993.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.235,791	LR: 0.000893	Loss: 0.358	Acc: 100.0000	 Speed: 1837.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.262,792	LR: 0.000893	Loss: 0.569	Acc: 62.5000	 Speed: 2202.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.289,793	LR: 0.000892	Loss: 0.232	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.315,794	LR: 0.000892	Loss: 0.470	Acc: 75.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.342,795	LR: 0.000892	Loss: 0.420	Acc: 87.5000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.369,796	LR: 0.000891	Loss: 0.372	Acc: 75.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.396,797	LR: 0.000891	Loss: 0.383	Acc: 100.0000	 Speed: 1601.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.423,798	LR: 0.000891	Loss: 0.375	Acc: 100.0000	 Speed: 666.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3700.0035 samples/s	Time: 0.02s
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.450,799	LR: 0.000891	Loss: 0.372	Acc: 87.5000	 Speed: 54.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.477,800	LR: 0.000890	Loss: 0.372	Acc: 87.5000	 Speed: 1911.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.503,801	LR: 0.000890	Loss: 0.267	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.530,802	LR: 0.000890	Loss: 0.571	Acc: 75.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.557,803	LR: 0.000890	Loss: 0.439	Acc: 75.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.584,804	LR: 0.000889	Loss: 0.471	Acc: 75.0000	 Speed: 2020.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.611,805	LR: 0.000889	Loss: 0.463	Acc: 87.5000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.638,806	LR: 0.000889	Loss: 0.359	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.664,807	LR: 0.000889	Loss: 0.344	Acc: 87.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.691,808	LR: 0.000888	Loss: 0.330	Acc: 87.5000	 Speed: 1702.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.718,809	LR: 0.000888	Loss: 0.395	Acc: 87.5000	 Speed: 1843.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.745,810	LR: 0.000888	Loss: 0.321	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.772,811	LR: 0.000888	Loss: 0.534	Acc: 75.0000	 Speed: 2183.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.799,812	LR: 0.000887	Loss: 0.401	Acc: 100.0000	 Speed: 1723.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.826,813	LR: 0.000887	Loss: 0.435	Acc: 87.5000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.852,814	LR: 0.000887	Loss: 0.344	Acc: 100.0000	 Speed: 1229.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.879,815	LR: 0.000886	Loss: 0.443	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.906,816	LR: 0.000886	Loss: 0.286	Acc: 100.0000	 Speed: 1598.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.933,817	LR: 0.000886	Loss: 0.508	Acc: 75.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.960,818	LR: 0.000886	Loss: 0.464	Acc: 75.0000	 Speed: 2293.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 21.987,819	LR: 0.000885	Loss: 0.445	Acc: 75.0000	 Speed: 1572.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.013,820	LR: 0.000885	Loss: 0.463	Acc: 87.5000	 Speed: 1761.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.040,821	LR: 0.000885	Loss: 0.296	Acc: 100.0000	 Speed: 1228.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.067,822	LR: 0.000885	Loss: 0.378	Acc: 100.0000	 Speed: 2272.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.094,823	LR: 0.000884	Loss: 0.592	Acc: 87.5000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.121,824	LR: 0.000884	Loss: 0.317	Acc: 87.5000	 Speed: 2369.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.148,825	LR: 0.000884	Loss: 0.303	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.174,826	LR: 0.000884	Loss: 0.408	Acc: 75.0000	 Speed: 2664.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.201,827	LR: 0.000883	Loss: 0.262	Acc: 87.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.228,828	LR: 0.000883	Loss: 0.444	Acc: 75.0000	 Speed: 1600.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.255,829	LR: 0.000883	Loss: 0.352	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.282,830	LR: 0.000882	Loss: 0.423	Acc: 87.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.309,831	LR: 0.000882	Loss: 0.227	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.336,832	LR: 0.000882	Loss: 0.653	Acc: 62.5000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.362,833	LR: 0.000882	Loss: 0.237	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.389,834	LR: 0.000881	Loss: 0.296	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.416,835	LR: 0.000881	Loss: 0.574	Acc: 62.5000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.443,836	LR: 0.000881	Loss: 0.161	Acc: 100.0000	 Speed: 500.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3524.3451 samples/s	Time: 0.02s
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.470,837	LR: 0.000881	Loss: 0.311	Acc: 100.0000	 Speed: 52.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.497,838	LR: 0.000880	Loss: 0.311	Acc: 87.5000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.523,839	LR: 0.000880	Loss: 0.316	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.550,840	LR: 0.000880	Loss: 0.452	Acc: 87.5000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.577,841	LR: 0.000879	Loss: 0.248	Acc: 100.0000	 Speed: 1545.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.604,842	LR: 0.000879	Loss: 0.291	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.631,843	LR: 0.000879	Loss: 0.388	Acc: 87.5000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.658,844	LR: 0.000879	Loss: 0.379	Acc: 87.5000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.685,845	LR: 0.000878	Loss: 0.330	Acc: 87.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:12 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.711,846	LR: 0.000878	Loss: 0.273	Acc: 100.0000	 Speed: 2665.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.738,847	LR: 0.000878	Loss: 0.317	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.765,848	LR: 0.000877	Loss: 0.300	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.792,849	LR: 0.000877	Loss: 0.310	Acc: 87.5000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.819,850	LR: 0.000877	Loss: 0.298	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.846,851	LR: 0.000877	Loss: 0.278	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.872,852	LR: 0.000876	Loss: 0.406	Acc: 87.5000	 Speed: 2001.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.899,853	LR: 0.000876	Loss: 0.690	Acc: 50.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.926,854	LR: 0.000876	Loss: 0.328	Acc: 87.5000	 Speed: 1333.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.953,855	LR: 0.000876	Loss: 0.307	Acc: 100.0000	 Speed: 707.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 22.980,856	LR: 0.000875	Loss: 0.310	Acc: 100.0000	 Speed: 1462.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.007,857	LR: 0.000875	Loss: 0.579	Acc: 75.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.034,858	LR: 0.000875	Loss: 0.261	Acc: 100.0000	 Speed: 1839.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.060,859	LR: 0.000874	Loss: 0.459	Acc: 75.0000	 Speed: 1520.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.087,860	LR: 0.000874	Loss: 0.490	Acc: 87.5000	 Speed: 1600.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.114,861	LR: 0.000874	Loss: 0.422	Acc: 87.5000	 Speed: 1695.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.141,862	LR: 0.000874	Loss: 0.294	Acc: 100.0000	 Speed: 1997.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.168,863	LR: 0.000873	Loss: 0.305	Acc: 87.5000	 Speed: 2388.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.195,864	LR: 0.000873	Loss: 0.436	Acc: 87.5000	 Speed: 1747.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.221,865	LR: 0.000873	Loss: 0.458	Acc: 87.5000	 Speed: 1787.47 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.248,866	LR: 0.000872	Loss: 0.344	Acc: 75.0000	 Speed: 1796.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.275,867	LR: 0.000872	Loss: 0.402	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.302,868	LR: 0.000872	Loss: 0.421	Acc: 87.5000	 Speed: 2643.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.329,869	LR: 0.000872	Loss: 0.355	Acc: 87.5000	 Speed: 1718.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.356,870	LR: 0.000871	Loss: 0.300	Acc: 100.0000	 Speed: 1560.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.383,871	LR: 0.000871	Loss: 0.528	Acc: 75.0000	 Speed: 1585.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.409,872	LR: 0.000871	Loss: 0.276	Acc: 100.0000	 Speed: 2279.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.436,873	LR: 0.000870	Loss: 0.375	Acc: 87.5000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.463,874	LR: 0.000870	Loss: 0.546	Acc: 50.0000	 Speed: 500.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3672.5967 samples/s	Time: 0.02s
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.490,875	LR: 0.000870	Loss: 0.261	Acc: 100.0000	 Speed: 50.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.517,876	LR: 0.000870	Loss: 0.280	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.544,877	LR: 0.000869	Loss: 0.335	Acc: 100.0000	 Speed: 1463.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.570,878	LR: 0.000869	Loss: 0.340	Acc: 87.5000	 Speed: 2600.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.597,879	LR: 0.000869	Loss: 0.207	Acc: 100.0000	 Speed: 1333.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.624,880	LR: 0.000869	Loss: 0.339	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.651,881	LR: 0.000868	Loss: 0.439	Acc: 87.5000	 Speed: 1783.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.678,882	LR: 0.000868	Loss: 0.398	Acc: 75.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.705,883	LR: 0.000868	Loss: 0.300	Acc: 87.5000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.732,884	LR: 0.000867	Loss: 0.357	Acc: 87.5000	 Speed: 1419.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.758,885	LR: 0.000867	Loss: 0.292	Acc: 100.0000	 Speed: 1390.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.785,886	LR: 0.000867	Loss: 0.227	Acc: 100.0000	 Speed: 1332.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.812,887	LR: 0.000866	Loss: 0.481	Acc: 75.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.839,888	LR: 0.000866	Loss: 0.246	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.866,889	LR: 0.000866	Loss: 0.372	Acc: 87.5000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.893,890	LR: 0.000866	Loss: 0.178	Acc: 100.0000	 Speed: 2141.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.919,891	LR: 0.000865	Loss: 0.324	Acc: 87.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.946,892	LR: 0.000865	Loss: 0.345	Acc: 87.5000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 23.973,893	LR: 0.000865	Loss: 0.257	Acc: 100.0000	 Speed: 2207.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.000,894	LR: 0.000864	Loss: 0.261	Acc: 87.5000	 Speed: 1632.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.027,895	LR: 0.000864	Loss: 0.279	Acc: 100.0000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.054,896	LR: 0.000864	Loss: 0.492	Acc: 87.5000	 Speed: 2001.10 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.081,897	LR: 0.000864	Loss: 0.320	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.107,898	LR: 0.000863	Loss: 0.357	Acc: 87.5000	 Speed: 1599.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.134,899	LR: 0.000863	Loss: 0.419	Acc: 75.0000	 Speed: 2174.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.161,900	LR: 0.000863	Loss: 0.298	Acc: 87.5000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.188,901	LR: 0.000862	Loss: 0.447	Acc: 75.0000	 Speed: 1599.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.215,902	LR: 0.000862	Loss: 0.342	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.242,903	LR: 0.000862	Loss: 0.570	Acc: 75.0000	 Speed: 1270.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.268,904	LR: 0.000862	Loss: 0.323	Acc: 87.5000	 Speed: 1903.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.295,905	LR: 0.000861	Loss: 0.261	Acc: 100.0000	 Speed: 2338.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.322,906	LR: 0.000861	Loss: 0.449	Acc: 75.0000	 Speed: 2106.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.349,907	LR: 0.000861	Loss: 0.328	Acc: 87.5000	 Speed: 2394.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.376,908	LR: 0.000860	Loss: 0.266	Acc: 87.5000	 Speed: 1876.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.403,909	LR: 0.000860	Loss: 0.222	Acc: 100.0000	 Speed: 1785.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.430,910	LR: 0.000860	Loss: 0.543	Acc: 75.0000	 Speed: 1782.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.456,911	LR: 0.000860	Loss: 0.316	Acc: 87.5000	 Speed: 2432.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.483,912	LR: 0.000859	Loss: 0.393	Acc: 100.0000	 Speed: 512.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3708.7132 samples/s	Time: 0.02s
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.510,913	LR: 0.000859	Loss: 0.333	Acc: 100.0000	 Speed: 52.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.537,914	LR: 0.000859	Loss: 0.225	Acc: 100.0000	 Speed: 1599.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.564,915	LR: 0.000858	Loss: 0.422	Acc: 75.0000	 Speed: 889.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.591,916	LR: 0.000858	Loss: 0.291	Acc: 100.0000	 Speed: 1333.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.617,917	LR: 0.000858	Loss: 0.225	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.644,918	LR: 0.000857	Loss: 0.409	Acc: 87.5000	 Speed: 2283.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.671,919	LR: 0.000857	Loss: 0.375	Acc: 87.5000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.698,920	LR: 0.000857	Loss: 0.395	Acc: 87.5000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.725,921	LR: 0.000857	Loss: 0.412	Acc: 75.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.752,922	LR: 0.000856	Loss: 0.270	Acc: 87.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.779,923	LR: 0.000856	Loss: 0.163	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.805,924	LR: 0.000856	Loss: 0.240	Acc: 100.0000	 Speed: 2001.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.832,925	LR: 0.000855	Loss: 0.363	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.859,926	LR: 0.000855	Loss: 0.272	Acc: 87.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.886,927	LR: 0.000855	Loss: 0.354	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.913,928	LR: 0.000855	Loss: 0.309	Acc: 87.5000	 Speed: 1333.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.940,929	LR: 0.000854	Loss: 0.156	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.966,930	LR: 0.000854	Loss: 0.256	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 24.993,931	LR: 0.000854	Loss: 0.283	Acc: 87.5000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.020,932	LR: 0.000853	Loss: 0.332	Acc: 75.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.047,933	LR: 0.000853	Loss: 0.457	Acc: 87.5000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.074,934	LR: 0.000853	Loss: 0.310	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.101,935	LR: 0.000852	Loss: 0.299	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.128,936	LR: 0.000852	Loss: 0.356	Acc: 87.5000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.154,937	LR: 0.000852	Loss: 0.226	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.181,938	LR: 0.000852	Loss: 0.357	Acc: 100.0000	 Speed: 1994.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.208,939	LR: 0.000851	Loss: 0.213	Acc: 100.0000	 Speed: 1594.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.235,940	LR: 0.000851	Loss: 0.418	Acc: 87.5000	 Speed: 2265.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.262,941	LR: 0.000851	Loss: 0.471	Acc: 87.5000	 Speed: 1739.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.289,942	LR: 0.000850	Loss: 0.235	Acc: 100.0000	 Speed: 2310.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.315,943	LR: 0.000850	Loss: 0.276	Acc: 100.0000	 Speed: 1270.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.342,944	LR: 0.000850	Loss: 0.251	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.369,945	LR: 0.000849	Loss: 0.292	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.396,946	LR: 0.000849	Loss: 0.337	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.423,947	LR: 0.000849	Loss: 0.328	Acc: 87.5000	 Speed: 1653.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.450,948	LR: 0.000849	Loss: 0.287	Acc: 100.0000	 Speed: 1756.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.477,949	LR: 0.000848	Loss: 0.389	Acc: 87.5000	 Speed: 2013.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.503,950	LR: 0.000848	Loss: 0.154	Acc: 100.0000	 Speed: 640.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 51.351	Speed: 3550.2665 samples/s	Time: 0.02s
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.530,951	LR: 0.000848	Loss: 0.285	Acc: 87.5000	 Speed: 51.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.557,952	LR: 0.000847	Loss: 0.212	Acc: 87.5000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:13 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.584,953	LR: 0.000847	Loss: 0.497	Acc: 62.5000	 Speed: 1585.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.611,954	LR: 0.000847	Loss: 0.389	Acc: 87.5000	 Speed: 1763.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.638,955	LR: 0.000846	Loss: 0.317	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.664,956	LR: 0.000846	Loss: 0.366	Acc: 75.0000	 Speed: 1760.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.691,957	LR: 0.000846	Loss: 0.254	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.718,958	LR: 0.000845	Loss: 0.311	Acc: 87.5000	 Speed: 2664.53 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.745,959	LR: 0.000845	Loss: 0.266	Acc: 87.5000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.772,960	LR: 0.000845	Loss: 0.207	Acc: 100.0000	 Speed: 1654.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.799,961	LR: 0.000845	Loss: 0.287	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.826,962	LR: 0.000844	Loss: 0.367	Acc: 87.5000	 Speed: 2104.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.852,963	LR: 0.000844	Loss: 0.212	Acc: 100.0000	 Speed: 2160.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.879,964	LR: 0.000844	Loss: 0.356	Acc: 87.5000	 Speed: 2101.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.906,965	LR: 0.000843	Loss: 0.336	Acc: 87.5000	 Speed: 1828.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.933,966	LR: 0.000843	Loss: 0.308	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.960,967	LR: 0.000843	Loss: 0.183	Acc: 100.0000	 Speed: 2366.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 25.987,968	LR: 0.000842	Loss: 0.291	Acc: 100.0000	 Speed: 1723.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.013,969	LR: 0.000842	Loss: 0.208	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.040,970	LR: 0.000842	Loss: 0.225	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.067,971	LR: 0.000842	Loss: 0.262	Acc: 87.5000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.094,972	LR: 0.000841	Loss: 0.353	Acc: 87.5000	 Speed: 1993.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.121,973	LR: 0.000841	Loss: 0.299	Acc: 87.5000	 Speed: 2661.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.148,974	LR: 0.000841	Loss: 0.214	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.174,975	LR: 0.000840	Loss: 0.283	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.201,976	LR: 0.000840	Loss: 0.288	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.228,977	LR: 0.000840	Loss: 0.373	Acc: 87.5000	 Speed: 1451.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.255,978	LR: 0.000839	Loss: 0.150	Acc: 100.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.282,979	LR: 0.000839	Loss: 0.159	Acc: 100.0000	 Speed: 1729.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.309,980	LR: 0.000839	Loss: 0.211	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.336,981	LR: 0.000838	Loss: 0.355	Acc: 87.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.362,982	LR: 0.000838	Loss: 0.340	Acc: 87.5000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.389,983	LR: 0.000838	Loss: 0.232	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.416,984	LR: 0.000837	Loss: 0.292	Acc: 87.5000	 Speed: 1217.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.443,985	LR: 0.000837	Loss: 0.349	Acc: 75.0000	 Speed: 1530.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.470,986	LR: 0.000837	Loss: 0.166	Acc: 100.0000	 Speed: 1605.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.497,987	LR: 0.000837	Loss: 0.291	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.523,988	LR: 0.000836	Loss: 0.391	Acc: 100.0000	 Speed: 605.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3588.8960 samples/s	Time: 0.02s
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.550,989	LR: 0.000836	Loss: 0.211	Acc: 100.0000	 Speed: 53.30 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.577,990	LR: 0.000836	Loss: 0.346	Acc: 87.5000	 Speed: 1644.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.604,991	LR: 0.000835	Loss: 0.259	Acc: 87.5000	 Speed: 1737.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.631,992	LR: 0.000835	Loss: 0.210	Acc: 100.0000	 Speed: 2186.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.658,993	LR: 0.000835	Loss: 0.275	Acc: 87.5000	 Speed: 1932.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.685,994	LR: 0.000834	Loss: 0.235	Acc: 87.5000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.711,995	LR: 0.000834	Loss: 0.449	Acc: 75.0000	 Speed: 1730.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.738,996	LR: 0.000834	Loss: 0.220	Acc: 100.0000	 Speed: 1496.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.765,997	LR: 0.000833	Loss: 0.135	Acc: 100.0000	 Speed: 1781.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.792,998	LR: 0.000833	Loss: 0.205	Acc: 100.0000	 Speed: 1642.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.819,999	LR: 0.000833	Loss: 0.272	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.846,1000	LR: 0.000832	Loss: 0.208	Acc: 87.5000	 Speed: 2423.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.872,1001	LR: 0.000832	Loss: 0.212	Acc: 100.0000	 Speed: 1774.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.899,1002	LR: 0.000832	Loss: 0.469	Acc: 75.0000	 Speed: 1774.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.926,1003	LR: 0.000832	Loss: 0.394	Acc: 100.0000	 Speed: 1613.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.953,1004	LR: 0.000831	Loss: 0.248	Acc: 87.5000	 Speed: 1678.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 26.980,1005	LR: 0.000831	Loss: 0.266	Acc: 100.0000	 Speed: 2146.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.007,1006	LR: 0.000831	Loss: 0.322	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.034,1007	LR: 0.000830	Loss: 0.260	Acc: 87.5000	 Speed: 2400.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.060,1008	LR: 0.000830	Loss: 0.227	Acc: 87.5000	 Speed: 1784.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.087,1009	LR: 0.000830	Loss: 0.263	Acc: 100.0000	 Speed: 2091.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.114,1010	LR: 0.000829	Loss: 0.326	Acc: 87.5000	 Speed: 2277.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.141,1011	LR: 0.000829	Loss: 0.202	Acc: 100.0000	 Speed: 2014.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.168,1012	LR: 0.000829	Loss: 0.188	Acc: 100.0000	 Speed: 2186.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.195,1013	LR: 0.000828	Loss: 0.209	Acc: 100.0000	 Speed: 2088.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.221,1014	LR: 0.000828	Loss: 0.320	Acc: 87.5000	 Speed: 2017.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.248,1015	LR: 0.000828	Loss: 0.186	Acc: 100.0000	 Speed: 2055.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.275,1016	LR: 0.000827	Loss: 0.258	Acc: 100.0000	 Speed: 2351.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.302,1017	LR: 0.000827	Loss: 0.145	Acc: 100.0000	 Speed: 1329.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.329,1018	LR: 0.000827	Loss: 0.365	Acc: 75.0000	 Speed: 1513.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.356,1019	LR: 0.000826	Loss: 0.248	Acc: 75.0000	 Speed: 1834.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.383,1020	LR: 0.000826	Loss: 0.246	Acc: 87.5000	 Speed: 1897.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.409,1021	LR: 0.000826	Loss: 0.159	Acc: 100.0000	 Speed: 1731.48 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.436,1022	LR: 0.000825	Loss: 0.375	Acc: 87.5000	 Speed: 2458.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.463,1023	LR: 0.000825	Loss: 0.152	Acc: 100.0000	 Speed: 1824.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.490,1024	LR: 0.000825	Loss: 0.296	Acc: 87.5000	 Speed: 2677.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.517,1025	LR: 0.000825	Loss: 0.335	Acc: 100.0000	 Speed: 2244.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.544,1026	LR: 0.000824	Loss: 0.262	Acc: 100.0000	 Speed: 747.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 58.108	Speed: 3568.5123 samples/s	Time: 0.02s
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.570,1027	LR: 0.000824	Loss: 0.285	Acc: 87.5000	 Speed: 53.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.597,1028	LR: 0.000824	Loss: 0.214	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.624,1029	LR: 0.000823	Loss: 0.267	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.651,1030	LR: 0.000823	Loss: 0.196	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.678,1031	LR: 0.000823	Loss: 0.343	Acc: 75.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.705,1032	LR: 0.000822	Loss: 0.172	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.732,1033	LR: 0.000822	Loss: 0.214	Acc: 100.0000	 Speed: 2668.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.758,1034	LR: 0.000822	Loss: 0.302	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.785,1035	LR: 0.000821	Loss: 0.143	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.812,1036	LR: 0.000821	Loss: 0.311	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.839,1037	LR: 0.000821	Loss: 0.154	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.866,1038	LR: 0.000820	Loss: 0.147	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.893,1039	LR: 0.000820	Loss: 0.324	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.919,1040	LR: 0.000820	Loss: 0.303	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.946,1041	LR: 0.000819	Loss: 0.201	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 27.973,1042	LR: 0.000819	Loss: 0.184	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.000,1043	LR: 0.000819	Loss: 0.145	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.027,1044	LR: 0.000818	Loss: 0.164	Acc: 100.0000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.054,1045	LR: 0.000818	Loss: 0.221	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.081,1046	LR: 0.000818	Loss: 0.200	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.107,1047	LR: 0.000817	Loss: 0.185	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.134,1048	LR: 0.000817	Loss: 0.307	Acc: 87.5000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.161,1049	LR: 0.000817	Loss: 0.395	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.188,1050	LR: 0.000816	Loss: 0.301	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.215,1051	LR: 0.000816	Loss: 0.281	Acc: 87.5000	 Speed: 1142.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.242,1052	LR: 0.000816	Loss: 0.225	Acc: 100.0000	 Speed: 1333.54 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.268,1053	LR: 0.000815	Loss: 0.126	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.295,1054	LR: 0.000815	Loss: 0.238	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.322,1055	LR: 0.000815	Loss: 0.132	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.349,1056	LR: 0.000814	Loss: 0.108	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.376,1057	LR: 0.000814	Loss: 0.152	Acc: 100.0000	 Speed: 2093.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.403,1058	LR: 0.000814	Loss: 0.386	Acc: 75.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.430,1059	LR: 0.000813	Loss: 0.355	Acc: 87.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.456,1060	LR: 0.000813	Loss: 0.247	Acc: 87.5000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.483,1061	LR: 0.000813	Loss: 0.276	Acc: 87.5000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.510,1062	LR: 0.000812	Loss: 0.200	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.537,1063	LR: 0.000812	Loss: 0.169	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.564,1064	LR: 0.000812	Loss: 0.424	Acc: 100.0000	 Speed: 500.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 51.351	Speed: 3523.2249 samples/s	Time: 0.02s
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.591,1065	LR: 0.000812	Loss: 0.245	Acc: 87.5000	 Speed: 53.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.617,1066	LR: 0.000811	Loss: 0.116	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.644,1067	LR: 0.000811	Loss: 0.233	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:14 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.671,1068	LR: 0.000811	Loss: 0.169	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.698,1069	LR: 0.000810	Loss: 0.220	Acc: 100.0000	 Speed: 2235.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.725,1070	LR: 0.000810	Loss: 0.163	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.752,1071	LR: 0.000810	Loss: 0.227	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.779,1072	LR: 0.000809	Loss: 0.210	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.805,1073	LR: 0.000809	Loss: 0.160	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.832,1074	LR: 0.000809	Loss: 0.192	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.859,1075	LR: 0.000808	Loss: 0.159	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.886,1076	LR: 0.000808	Loss: 0.139	Acc: 100.0000	 Speed: 2100.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.913,1077	LR: 0.000808	Loss: 0.158	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.940,1078	LR: 0.000807	Loss: 0.137	Acc: 100.0000	 Speed: 2665.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.966,1079	LR: 0.000807	Loss: 0.211	Acc: 100.0000	 Speed: 1435.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 28.993,1080	LR: 0.000807	Loss: 0.188	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.020,1081	LR: 0.000806	Loss: 0.318	Acc: 87.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.047,1082	LR: 0.000806	Loss: 0.430	Acc: 87.5000	 Speed: 2196.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.074,1083	LR: 0.000806	Loss: 0.238	Acc: 87.5000	 Speed: 1999.43 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.101,1084	LR: 0.000805	Loss: 0.240	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.128,1085	LR: 0.000805	Loss: 0.130	Acc: 100.0000	 Speed: 2240.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.154,1086	LR: 0.000805	Loss: 0.209	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.181,1087	LR: 0.000804	Loss: 0.182	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.208,1088	LR: 0.000804	Loss: 0.282	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.235,1089	LR: 0.000804	Loss: 0.080	Acc: 100.0000	 Speed: 1333.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.262,1090	LR: 0.000803	Loss: 0.240	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.289,1091	LR: 0.000803	Loss: 0.173	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.315,1092	LR: 0.000803	Loss: 0.154	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.342,1093	LR: 0.000802	Loss: 0.257	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.369,1094	LR: 0.000802	Loss: 0.194	Acc: 100.0000	 Speed: 1723.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.396,1095	LR: 0.000802	Loss: 0.250	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.423,1096	LR: 0.000801	Loss: 0.228	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.450,1097	LR: 0.000801	Loss: 0.129	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.477,1098	LR: 0.000801	Loss: 0.168	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.503,1099	LR: 0.000800	Loss: 0.229	Acc: 100.0000	 Speed: 1601.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.530,1100	LR: 0.000800	Loss: 0.436	Acc: 75.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.557,1101	LR: 0.000799	Loss: 0.240	Acc: 87.5000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.584,1102	LR: 0.000799	Loss: 0.350	Acc: 100.0000	 Speed: 499.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3523.6249 samples/s	Time: 0.02s
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.611,1103	LR: 0.000799	Loss: 0.059	Acc: 100.0000	 Speed: 52.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.638,1104	LR: 0.000798	Loss: 0.154	Acc: 100.0000	 Speed: 1734.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.664,1105	LR: 0.000798	Loss: 0.152	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.691,1106	LR: 0.000798	Loss: 0.188	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.718,1107	LR: 0.000797	Loss: 0.206	Acc: 100.0000	 Speed: 1599.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.745,1108	LR: 0.000797	Loss: 0.121	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.772,1109	LR: 0.000797	Loss: 0.283	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.799,1110	LR: 0.000796	Loss: 0.183	Acc: 100.0000	 Speed: 1600.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.826,1111	LR: 0.000796	Loss: 0.268	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.852,1112	LR: 0.000796	Loss: 0.241	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.879,1113	LR: 0.000795	Loss: 0.269	Acc: 87.5000	 Speed: 2248.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.906,1114	LR: 0.000795	Loss: 0.234	Acc: 100.0000	 Speed: 1598.82 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.933,1115	LR: 0.000795	Loss: 0.142	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.960,1116	LR: 0.000794	Loss: 0.106	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 29.987,1117	LR: 0.000794	Loss: 0.140	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.013,1118	LR: 0.000794	Loss: 0.267	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.040,1119	LR: 0.000793	Loss: 0.159	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.067,1120	LR: 0.000793	Loss: 0.265	Acc: 87.5000	 Speed: 1428.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.094,1121	LR: 0.000793	Loss: 0.123	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.121,1122	LR: 0.000792	Loss: 0.164	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.148,1123	LR: 0.000792	Loss: 0.145	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.174,1124	LR: 0.000792	Loss: 0.140	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.201,1125	LR: 0.000791	Loss: 0.144	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.228,1126	LR: 0.000791	Loss: 0.116	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.255,1127	LR: 0.000791	Loss: 0.188	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.282,1128	LR: 0.000790	Loss: 0.220	Acc: 87.5000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.309,1129	LR: 0.000790	Loss: 0.141	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.336,1130	LR: 0.000790	Loss: 0.199	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.362,1131	LR: 0.000789	Loss: 0.273	Acc: 87.5000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.389,1132	LR: 0.000789	Loss: 0.106	Acc: 100.0000	 Speed: 1333.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.416,1133	LR: 0.000789	Loss: 0.156	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.443,1134	LR: 0.000788	Loss: 0.206	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.470,1135	LR: 0.000788	Loss: 0.201	Acc: 100.0000	 Speed: 1443.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.497,1136	LR: 0.000788	Loss: 0.171	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.523,1137	LR: 0.000787	Loss: 0.145	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.550,1138	LR: 0.000787	Loss: 0.261	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.577,1139	LR: 0.000787	Loss: 0.275	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.604,1140	LR: 0.000786	Loss: 0.392	Acc: 100.0000	 Speed: 567.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 59.459	Speed: 3750.8429 samples/s	Time: 0.02s
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.631,1141	LR: 0.000786	Loss: 0.123	Acc: 100.0000	 Speed: 53.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.658,1142	LR: 0.000785	Loss: 0.220	Acc: 100.0000	 Speed: 1349.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.685,1143	LR: 0.000785	Loss: 0.187	Acc: 100.0000	 Speed: 2145.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.711,1144	LR: 0.000785	Loss: 0.154	Acc: 100.0000	 Speed: 1799.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.738,1145	LR: 0.000784	Loss: 0.181	Acc: 100.0000	 Speed: 1996.93 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.765,1146	LR: 0.000784	Loss: 0.096	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.792,1147	LR: 0.000784	Loss: 0.308	Acc: 87.5000	 Speed: 1326.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.819,1148	LR: 0.000783	Loss: 0.307	Acc: 75.0000	 Speed: 1773.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.846,1149	LR: 0.000783	Loss: 0.120	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.872,1150	LR: 0.000783	Loss: 0.330	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.899,1151	LR: 0.000782	Loss: 0.142	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.926,1152	LR: 0.000782	Loss: 0.137	Acc: 100.0000	 Speed: 1142.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.953,1153	LR: 0.000782	Loss: 0.164	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 30.980,1154	LR: 0.000781	Loss: 0.106	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.007,1155	LR: 0.000781	Loss: 0.180	Acc: 100.0000	 Speed: 2163.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.034,1156	LR: 0.000781	Loss: 0.090	Acc: 100.0000	 Speed: 2301.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.060,1157	LR: 0.000780	Loss: 0.172	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.087,1158	LR: 0.000780	Loss: 0.203	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.114,1159	LR: 0.000780	Loss: 0.172	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.141,1160	LR: 0.000779	Loss: 0.197	Acc: 87.5000	 Speed: 1990.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.168,1161	LR: 0.000779	Loss: 0.067	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.195,1162	LR: 0.000779	Loss: 0.126	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.221,1163	LR: 0.000778	Loss: 0.155	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.248,1164	LR: 0.000778	Loss: 0.104	Acc: 100.0000	 Speed: 1333.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.275,1165	LR: 0.000777	Loss: 0.255	Acc: 87.5000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.302,1166	LR: 0.000777	Loss: 0.114	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.329,1167	LR: 0.000777	Loss: 0.087	Acc: 100.0000	 Speed: 1143.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.356,1168	LR: 0.000776	Loss: 0.149	Acc: 100.0000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.383,1169	LR: 0.000776	Loss: 0.159	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.409,1170	LR: 0.000776	Loss: 0.172	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.436,1171	LR: 0.000775	Loss: 0.388	Acc: 75.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.463,1172	LR: 0.000775	Loss: 0.183	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.490,1173	LR: 0.000775	Loss: 0.093	Acc: 100.0000	 Speed: 2002.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.517,1174	LR: 0.000774	Loss: 0.078	Acc: 100.0000	 Speed: 1333.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.544,1175	LR: 0.000774	Loss: 0.129	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.570,1176	LR: 0.000774	Loss: 0.128	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.597,1177	LR: 0.000773	Loss: 0.227	Acc: 87.5000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.624,1178	LR: 0.000773	Loss: 0.239	Acc: 100.0000	 Speed: 421.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:15 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3699.2979 samples/s	Time: 0.02s
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.651,1179	LR: 0.000773	Loss: 0.132	Acc: 100.0000	 Speed: 50.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.678,1180	LR: 0.000772	Loss: 0.135	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.705,1181	LR: 0.000772	Loss: 0.095	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.732,1182	LR: 0.000771	Loss: 0.106	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.758,1183	LR: 0.000771	Loss: 0.157	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.785,1184	LR: 0.000771	Loss: 0.135	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.812,1185	LR: 0.000770	Loss: 0.102	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.839,1186	LR: 0.000770	Loss: 0.169	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.866,1187	LR: 0.000770	Loss: 0.159	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.893,1188	LR: 0.000769	Loss: 0.147	Acc: 100.0000	 Speed: 1142.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.919,1189	LR: 0.000769	Loss: 0.110	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.946,1190	LR: 0.000769	Loss: 0.142	Acc: 100.0000	 Speed: 1996.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 31.973,1191	LR: 0.000768	Loss: 0.103	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.000,1192	LR: 0.000768	Loss: 0.143	Acc: 87.5000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.027,1193	LR: 0.000768	Loss: 0.180	Acc: 87.5000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.054,1194	LR: 0.000767	Loss: 0.082	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.081,1195	LR: 0.000767	Loss: 0.204	Acc: 87.5000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.107,1196	LR: 0.000766	Loss: 0.130	Acc: 100.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.134,1197	LR: 0.000766	Loss: 0.114	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.161,1198	LR: 0.000766	Loss: 0.131	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.188,1199	LR: 0.000765	Loss: 0.155	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.215,1200	LR: 0.000765	Loss: 0.113	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.242,1201	LR: 0.000765	Loss: 0.104	Acc: 100.0000	 Speed: 1200.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.268,1202	LR: 0.000764	Loss: 0.310	Acc: 75.0000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.295,1203	LR: 0.000764	Loss: 0.168	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.322,1204	LR: 0.000764	Loss: 0.068	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.349,1205	LR: 0.000763	Loss: 0.088	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.376,1206	LR: 0.000763	Loss: 0.111	Acc: 100.0000	 Speed: 1142.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.403,1207	LR: 0.000763	Loss: 0.179	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.430,1208	LR: 0.000762	Loss: 0.180	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.456,1209	LR: 0.000762	Loss: 0.099	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.483,1210	LR: 0.000761	Loss: 0.243	Acc: 87.5000	 Speed: 1420.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.510,1211	LR: 0.000761	Loss: 0.147	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.537,1212	LR: 0.000761	Loss: 0.129	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.564,1213	LR: 0.000760	Loss: 0.159	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.591,1214	LR: 0.000760	Loss: 0.121	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.617,1215	LR: 0.000760	Loss: 0.207	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.644,1216	LR: 0.000759	Loss: 0.147	Acc: 100.0000	 Speed: 760.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3585.3721 samples/s	Time: 0.02s
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.671,1217	LR: 0.000759	Loss: 0.072	Acc: 100.0000	 Speed: 54.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.698,1218	LR: 0.000759	Loss: 0.090	Acc: 100.0000	 Speed: 1769.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.725,1219	LR: 0.000758	Loss: 0.097	Acc: 100.0000	 Speed: 1995.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.752,1220	LR: 0.000758	Loss: 0.184	Acc: 100.0000	 Speed: 1748.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.779,1221	LR: 0.000758	Loss: 0.125	Acc: 100.0000	 Speed: 1839.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.805,1222	LR: 0.000757	Loss: 0.209	Acc: 100.0000	 Speed: 2011.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.832,1223	LR: 0.000757	Loss: 0.122	Acc: 100.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.859,1224	LR: 0.000756	Loss: 0.106	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.886,1225	LR: 0.000756	Loss: 0.122	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.913,1226	LR: 0.000756	Loss: 0.094	Acc: 100.0000	 Speed: 2670.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.940,1227	LR: 0.000755	Loss: 0.075	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.966,1228	LR: 0.000755	Loss: 0.078	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 32.993,1229	LR: 0.000755	Loss: 0.165	Acc: 100.0000	 Speed: 2668.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.020,1230	LR: 0.000754	Loss: 0.082	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.047,1231	LR: 0.000754	Loss: 0.092	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.074,1232	LR: 0.000754	Loss: 0.107	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.101,1233	LR: 0.000753	Loss: 0.133	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.128,1234	LR: 0.000753	Loss: 0.124	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.154,1235	LR: 0.000752	Loss: 0.091	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.181,1236	LR: 0.000752	Loss: 0.083	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.208,1237	LR: 0.000752	Loss: 0.066	Acc: 100.0000	 Speed: 1333.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.235,1238	LR: 0.000751	Loss: 0.106	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.262,1239	LR: 0.000751	Loss: 0.076	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.289,1240	LR: 0.000751	Loss: 0.093	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.315,1241	LR: 0.000750	Loss: 0.158	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.342,1242	LR: 0.000750	Loss: 0.134	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.369,1243	LR: 0.000750	Loss: 0.162	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.396,1244	LR: 0.000749	Loss: 0.252	Acc: 87.5000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.423,1245	LR: 0.000749	Loss: 0.079	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.450,1246	LR: 0.000748	Loss: 0.180	Acc: 87.5000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.477,1247	LR: 0.000748	Loss: 0.150	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.503,1248	LR: 0.000748	Loss: 0.111	Acc: 100.0000	 Speed: 2001.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.530,1249	LR: 0.000747	Loss: 0.081	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.557,1250	LR: 0.000747	Loss: 0.086	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.584,1251	LR: 0.000747	Loss: 0.141	Acc: 100.0000	 Speed: 2665.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.611,1252	LR: 0.000746	Loss: 0.306	Acc: 87.5000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.638,1253	LR: 0.000746	Loss: 0.153	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.664,1254	LR: 0.000745	Loss: 0.285	Acc: 100.0000	 Speed: 666.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 50.000	Speed: 3466.7928 samples/s	Time: 0.02s
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.691,1255	LR: 0.000745	Loss: 0.313	Acc: 87.5000	 Speed: 52.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.718,1256	LR: 0.000745	Loss: 0.194	Acc: 87.5000	 Speed: 1513.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.745,1257	LR: 0.000744	Loss: 0.089	Acc: 100.0000	 Speed: 2668.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.772,1258	LR: 0.000744	Loss: 0.178	Acc: 87.5000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.799,1259	LR: 0.000744	Loss: 0.223	Acc: 100.0000	 Speed: 1505.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.826,1260	LR: 0.000743	Loss: 0.083	Acc: 100.0000	 Speed: 2282.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.852,1261	LR: 0.000743	Loss: 0.132	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.879,1262	LR: 0.000743	Loss: 0.063	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.906,1263	LR: 0.000742	Loss: 0.088	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.933,1264	LR: 0.000742	Loss: 0.099	Acc: 100.0000	 Speed: 2668.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.960,1265	LR: 0.000741	Loss: 0.113	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 33.987,1266	LR: 0.000741	Loss: 0.045	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.013,1267	LR: 0.000741	Loss: 0.201	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.040,1268	LR: 0.000740	Loss: 0.093	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.067,1269	LR: 0.000740	Loss: 0.117	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.094,1270	LR: 0.000740	Loss: 0.116	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.121,1271	LR: 0.000739	Loss: 0.090	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.148,1272	LR: 0.000739	Loss: 0.115	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.174,1273	LR: 0.000738	Loss: 0.074	Acc: 100.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.201,1274	LR: 0.000738	Loss: 0.052	Acc: 100.0000	 Speed: 2001.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.228,1275	LR: 0.000738	Loss: 0.146	Acc: 100.0000	 Speed: 1918.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.255,1276	LR: 0.000737	Loss: 0.121	Acc: 100.0000	 Speed: 2112.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.282,1277	LR: 0.000737	Loss: 0.131	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.309,1278	LR: 0.000737	Loss: 0.071	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.336,1279	LR: 0.000736	Loss: 0.070	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.362,1280	LR: 0.000736	Loss: 0.060	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.389,1281	LR: 0.000736	Loss: 0.185	Acc: 87.5000	 Speed: 1142.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.416,1282	LR: 0.000735	Loss: 0.085	Acc: 100.0000	 Speed: 1333.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.443,1283	LR: 0.000735	Loss: 0.110	Acc: 100.0000	 Speed: 1000.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.470,1284	LR: 0.000734	Loss: 0.092	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.497,1285	LR: 0.000734	Loss: 0.075	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.523,1286	LR: 0.000734	Loss: 0.096	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.550,1287	LR: 0.000733	Loss: 0.055	Acc: 100.0000	 Speed: 2279.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.577,1288	LR: 0.000733	Loss: 0.138	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.604,1289	LR: 0.000733	Loss: 0.107	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.631,1290	LR: 0.000732	Loss: 0.146	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.658,1291	LR: 0.000732	Loss: 0.090	Acc: 100.0000	 Speed: 1900.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.685,1292	LR: 0.000731	Loss: 0.037	Acc: 100.0000	 Speed: 499.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:16 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3699.7389 samples/s	Time: 0.02s
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.711,1293	LR: 0.000731	Loss: 0.078	Acc: 100.0000	 Speed: 52.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.738,1294	LR: 0.000731	Loss: 0.118	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.765,1295	LR: 0.000730	Loss: 0.079	Acc: 100.0000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.792,1296	LR: 0.000730	Loss: 0.063	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.819,1297	LR: 0.000730	Loss: 0.121	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.846,1298	LR: 0.000729	Loss: 0.038	Acc: 100.0000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.872,1299	LR: 0.000729	Loss: 0.061	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.899,1300	LR: 0.000728	Loss: 0.105	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.926,1301	LR: 0.000728	Loss: 0.083	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.953,1302	LR: 0.000728	Loss: 0.050	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 34.980,1303	LR: 0.000727	Loss: 0.172	Acc: 87.5000	 Speed: 1599.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.007,1304	LR: 0.000727	Loss: 0.088	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.034,1305	LR: 0.000727	Loss: 0.064	Acc: 100.0000	 Speed: 1333.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.060,1306	LR: 0.000726	Loss: 0.128	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.087,1307	LR: 0.000726	Loss: 0.072	Acc: 100.0000	 Speed: 1422.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.114,1308	LR: 0.000725	Loss: 0.075	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.141,1309	LR: 0.000725	Loss: 0.074	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.168,1310	LR: 0.000725	Loss: 0.077	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.195,1311	LR: 0.000724	Loss: 0.115	Acc: 100.0000	 Speed: 2500.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.221,1312	LR: 0.000724	Loss: 0.083	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.248,1313	LR: 0.000724	Loss: 0.210	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.275,1314	LR: 0.000723	Loss: 0.116	Acc: 100.0000	 Speed: 1575.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.302,1315	LR: 0.000723	Loss: 0.150	Acc: 100.0000	 Speed: 2518.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.329,1316	LR: 0.000722	Loss: 0.116	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.356,1317	LR: 0.000722	Loss: 0.100	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.383,1318	LR: 0.000722	Loss: 0.088	Acc: 100.0000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.409,1319	LR: 0.000721	Loss: 0.070	Acc: 100.0000	 Speed: 2167.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.436,1320	LR: 0.000721	Loss: 0.094	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.463,1321	LR: 0.000720	Loss: 0.047	Acc: 100.0000	 Speed: 2044.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.490,1322	LR: 0.000720	Loss: 0.153	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.517,1323	LR: 0.000720	Loss: 0.094	Acc: 100.0000	 Speed: 2169.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.544,1324	LR: 0.000719	Loss: 0.069	Acc: 100.0000	 Speed: 999.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.570,1325	LR: 0.000719	Loss: 0.138	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.597,1326	LR: 0.000719	Loss: 0.098	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.624,1327	LR: 0.000718	Loss: 0.076	Acc: 100.0000	 Speed: 1478.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.651,1328	LR: 0.000718	Loss: 0.077	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.678,1329	LR: 0.000717	Loss: 0.054	Acc: 100.0000	 Speed: 2032.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.705,1330	LR: 0.000717	Loss: 0.026	Acc: 100.0000	 Speed: 452.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3694.5862 samples/s	Time: 0.02s
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.732,1331	LR: 0.000717	Loss: 0.064	Acc: 100.0000	 Speed: 52.33 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.758,1332	LR: 0.000716	Loss: 0.035	Acc: 100.0000	 Speed: 1737.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.785,1333	LR: 0.000716	Loss: 0.076	Acc: 100.0000	 Speed: 2076.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.812,1334	LR: 0.000716	Loss: 0.082	Acc: 100.0000	 Speed: 2004.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.839,1335	LR: 0.000715	Loss: 0.065	Acc: 100.0000	 Speed: 1582.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.866,1336	LR: 0.000715	Loss: 0.075	Acc: 100.0000	 Speed: 1953.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.893,1337	LR: 0.000714	Loss: 0.098	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.919,1338	LR: 0.000714	Loss: 0.075	Acc: 100.0000	 Speed: 1516.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.946,1339	LR: 0.000714	Loss: 0.092	Acc: 100.0000	 Speed: 1794.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 35.973,1340	LR: 0.000713	Loss: 0.052	Acc: 100.0000	 Speed: 2211.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.000,1341	LR: 0.000713	Loss: 0.076	Acc: 100.0000	 Speed: 1247.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.027,1342	LR: 0.000713	Loss: 0.095	Acc: 100.0000	 Speed: 2073.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.054,1343	LR: 0.000712	Loss: 0.097	Acc: 100.0000	 Speed: 2220.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.081,1344	LR: 0.000712	Loss: 0.155	Acc: 100.0000	 Speed: 1985.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.107,1345	LR: 0.000711	Loss: 0.078	Acc: 100.0000	 Speed: 2384.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.134,1346	LR: 0.000711	Loss: 0.080	Acc: 100.0000	 Speed: 1395.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.161,1347	LR: 0.000711	Loss: 0.060	Acc: 100.0000	 Speed: 1871.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.188,1348	LR: 0.000710	Loss: 0.083	Acc: 100.0000	 Speed: 2021.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.215,1349	LR: 0.000710	Loss: 0.042	Acc: 100.0000	 Speed: 1312.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.242,1350	LR: 0.000709	Loss: 0.065	Acc: 100.0000	 Speed: 1914.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.268,1351	LR: 0.000709	Loss: 0.038	Acc: 100.0000	 Speed: 2281.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.295,1352	LR: 0.000709	Loss: 0.154	Acc: 100.0000	 Speed: 1983.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.322,1353	LR: 0.000708	Loss: 0.062	Acc: 100.0000	 Speed: 2199.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.349,1354	LR: 0.000708	Loss: 0.061	Acc: 100.0000	 Speed: 2003.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.376,1355	LR: 0.000708	Loss: 0.078	Acc: 100.0000	 Speed: 2321.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.403,1356	LR: 0.000707	Loss: 0.146	Acc: 100.0000	 Speed: 2067.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.430,1357	LR: 0.000707	Loss: 0.057	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.456,1358	LR: 0.000706	Loss: 0.127	Acc: 100.0000	 Speed: 2282.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.483,1359	LR: 0.000706	Loss: 0.090	Acc: 100.0000	 Speed: 1781.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.510,1360	LR: 0.000706	Loss: 0.050	Acc: 100.0000	 Speed: 2161.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.537,1361	LR: 0.000705	Loss: 0.039	Acc: 100.0000	 Speed: 1837.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.564,1362	LR: 0.000705	Loss: 0.057	Acc: 100.0000	 Speed: 1926.64 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.591,1363	LR: 0.000704	Loss: 0.096	Acc: 100.0000	 Speed: 2543.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.617,1364	LR: 0.000704	Loss: 0.049	Acc: 100.0000	 Speed: 1762.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.644,1365	LR: 0.000704	Loss: 0.086	Acc: 100.0000	 Speed: 1992.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.671,1366	LR: 0.000703	Loss: 0.078	Acc: 100.0000	 Speed: 2265.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.698,1367	LR: 0.000703	Loss: 0.120	Acc: 100.0000	 Speed: 2282.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.725,1368	LR: 0.000703	Loss: 0.028	Acc: 100.0000	 Speed: 538.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3557.3467 samples/s	Time: 0.02s
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.752,1369	LR: 0.000702	Loss: 0.044	Acc: 100.0000	 Speed: 52.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.779,1370	LR: 0.000702	Loss: 0.077	Acc: 100.0000	 Speed: 1976.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.805,1371	LR: 0.000701	Loss: 0.067	Acc: 100.0000	 Speed: 1598.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.832,1372	LR: 0.000701	Loss: 0.097	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.859,1373	LR: 0.000701	Loss: 0.160	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.886,1374	LR: 0.000700	Loss: 0.045	Acc: 100.0000	 Speed: 2121.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.913,1375	LR: 0.000700	Loss: 0.061	Acc: 100.0000	 Speed: 1755.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.940,1376	LR: 0.000699	Loss: 0.073	Acc: 100.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.966,1377	LR: 0.000699	Loss: 0.085	Acc: 100.0000	 Speed: 1796.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 36.993,1378	LR: 0.000699	Loss: 0.070	Acc: 100.0000	 Speed: 2287.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.020,1379	LR: 0.000698	Loss: 0.071	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.047,1380	LR: 0.000698	Loss: 0.077	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.074,1381	LR: 0.000698	Loss: 0.063	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.101,1382	LR: 0.000697	Loss: 0.065	Acc: 100.0000	 Speed: 1635.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.128,1383	LR: 0.000697	Loss: 0.051	Acc: 100.0000	 Speed: 1761.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.154,1384	LR: 0.000696	Loss: 0.065	Acc: 100.0000	 Speed: 2059.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.181,1385	LR: 0.000696	Loss: 0.099	Acc: 100.0000	 Speed: 1812.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.208,1386	LR: 0.000696	Loss: 0.131	Acc: 100.0000	 Speed: 2064.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.235,1387	LR: 0.000695	Loss: 0.090	Acc: 100.0000	 Speed: 2192.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.262,1388	LR: 0.000695	Loss: 0.034	Acc: 100.0000	 Speed: 1758.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.289,1389	LR: 0.000694	Loss: 0.049	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.315,1390	LR: 0.000694	Loss: 0.065	Acc: 100.0000	 Speed: 1807.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.342,1391	LR: 0.000694	Loss: 0.052	Acc: 100.0000	 Speed: 2528.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.369,1392	LR: 0.000693	Loss: 0.074	Acc: 100.0000	 Speed: 2171.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.396,1393	LR: 0.000693	Loss: 0.042	Acc: 100.0000	 Speed: 2663.68 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.423,1394	LR: 0.000692	Loss: 0.022	Acc: 100.0000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.450,1395	LR: 0.000692	Loss: 0.092	Acc: 100.0000	 Speed: 2038.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.477,1396	LR: 0.000692	Loss: 0.050	Acc: 100.0000	 Speed: 2207.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.503,1397	LR: 0.000691	Loss: 0.110	Acc: 100.0000	 Speed: 2897.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.530,1398	LR: 0.000691	Loss: 0.110	Acc: 100.0000	 Speed: 1840.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.557,1399	LR: 0.000691	Loss: 0.120	Acc: 100.0000	 Speed: 1532.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.584,1400	LR: 0.000690	Loss: 0.044	Acc: 100.0000	 Speed: 1353.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.611,1401	LR: 0.000690	Loss: 0.101	Acc: 100.0000	 Speed: 2121.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.638,1402	LR: 0.000689	Loss: 0.083	Acc: 100.0000	 Speed: 1334.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.664,1403	LR: 0.000689	Loss: 0.083	Acc: 100.0000	 Speed: 1543.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.691,1404	LR: 0.000689	Loss: 0.039	Acc: 100.0000	 Speed: 1944.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.718,1405	LR: 0.000688	Loss: 0.064	Acc: 100.0000	 Speed: 2256.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.745,1406	LR: 0.000688	Loss: 0.073	Acc: 100.0000	 Speed: 585.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:17 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3399.9923 samples/s	Time: 0.02s
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.772,1407	LR: 0.000687	Loss: 0.114	Acc: 100.0000	 Speed: 52.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.799,1408	LR: 0.000687	Loss: 0.045	Acc: 100.0000	 Speed: 2063.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.826,1409	LR: 0.000687	Loss: 0.052	Acc: 100.0000	 Speed: 2073.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.852,1410	LR: 0.000686	Loss: 0.111	Acc: 100.0000	 Speed: 1950.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.879,1411	LR: 0.000686	Loss: 0.036	Acc: 100.0000	 Speed: 2058.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.906,1412	LR: 0.000685	Loss: 0.077	Acc: 100.0000	 Speed: 2161.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.933,1413	LR: 0.000685	Loss: 0.070	Acc: 100.0000	 Speed: 1376.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.960,1414	LR: 0.000685	Loss: 0.098	Acc: 100.0000	 Speed: 1690.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 37.987,1415	LR: 0.000684	Loss: 0.036	Acc: 100.0000	 Speed: 1272.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.013,1416	LR: 0.000684	Loss: 0.074	Acc: 100.0000	 Speed: 1919.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.040,1417	LR: 0.000683	Loss: 0.057	Acc: 100.0000	 Speed: 1511.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.067,1418	LR: 0.000683	Loss: 0.069	Acc: 100.0000	 Speed: 1726.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.094,1419	LR: 0.000683	Loss: 0.048	Acc: 100.0000	 Speed: 1566.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.121,1420	LR: 0.000682	Loss: 0.099	Acc: 100.0000	 Speed: 1373.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.148,1421	LR: 0.000682	Loss: 0.114	Acc: 100.0000	 Speed: 1841.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.174,1422	LR: 0.000682	Loss: 0.059	Acc: 100.0000	 Speed: 1856.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.201,1423	LR: 0.000681	Loss: 0.084	Acc: 100.0000	 Speed: 2077.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.228,1424	LR: 0.000681	Loss: 0.038	Acc: 100.0000	 Speed: 2133.42 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.255,1425	LR: 0.000680	Loss: 0.054	Acc: 100.0000	 Speed: 1678.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.282,1426	LR: 0.000680	Loss: 0.044	Acc: 100.0000	 Speed: 1967.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.309,1427	LR: 0.000680	Loss: 0.052	Acc: 100.0000	 Speed: 1749.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.336,1428	LR: 0.000679	Loss: 0.039	Acc: 100.0000	 Speed: 2049.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.362,1429	LR: 0.000679	Loss: 0.048	Acc: 100.0000	 Speed: 1309.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.389,1430	LR: 0.000678	Loss: 0.053	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.416,1431	LR: 0.000678	Loss: 0.028	Acc: 100.0000	 Speed: 2565.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.443,1432	LR: 0.000678	Loss: 0.046	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.470,1433	LR: 0.000677	Loss: 0.088	Acc: 100.0000	 Speed: 2194.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.497,1434	LR: 0.000677	Loss: 0.071	Acc: 100.0000	 Speed: 1679.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.523,1435	LR: 0.000676	Loss: 0.039	Acc: 100.0000	 Speed: 1856.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.550,1436	LR: 0.000676	Loss: 0.077	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.577,1437	LR: 0.000676	Loss: 0.034	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.604,1438	LR: 0.000675	Loss: 0.060	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.631,1439	LR: 0.000675	Loss: 0.067	Acc: 100.0000	 Speed: 1956.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.658,1440	LR: 0.000674	Loss: 0.072	Acc: 100.0000	 Speed: 1856.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.685,1441	LR: 0.000674	Loss: 0.047	Acc: 100.0000	 Speed: 1929.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.711,1442	LR: 0.000674	Loss: 0.061	Acc: 100.0000	 Speed: 2075.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.738,1443	LR: 0.000673	Loss: 0.096	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.765,1444	LR: 0.000673	Loss: 0.040	Acc: 100.0000	 Speed: 666.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3567.0769 samples/s	Time: 0.02s
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.792,1445	LR: 0.000672	Loss: 0.030	Acc: 100.0000	 Speed: 53.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.819,1446	LR: 0.000672	Loss: 0.031	Acc: 100.0000	 Speed: 1833.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.846,1447	LR: 0.000672	Loss: 0.082	Acc: 100.0000	 Speed: 1955.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.872,1448	LR: 0.000671	Loss: 0.047	Acc: 100.0000	 Speed: 2145.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.899,1449	LR: 0.000671	Loss: 0.036	Acc: 100.0000	 Speed: 2156.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.926,1450	LR: 0.000670	Loss: 0.056	Acc: 100.0000	 Speed: 1558.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.953,1451	LR: 0.000670	Loss: 0.064	Acc: 100.0000	 Speed: 2631.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 38.980,1452	LR: 0.000670	Loss: 0.087	Acc: 100.0000	 Speed: 1916.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.007,1453	LR: 0.000669	Loss: 0.043	Acc: 100.0000	 Speed: 1940.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.034,1454	LR: 0.000669	Loss: 0.058	Acc: 100.0000	 Speed: 2765.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.060,1455	LR: 0.000668	Loss: 0.049	Acc: 100.0000	 Speed: 2212.04 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.087,1456	LR: 0.000668	Loss: 0.067	Acc: 100.0000	 Speed: 1872.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.114,1457	LR: 0.000668	Loss: 0.069	Acc: 100.0000	 Speed: 1219.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.141,1458	LR: 0.000667	Loss: 0.065	Acc: 100.0000	 Speed: 2612.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.168,1459	LR: 0.000667	Loss: 0.028	Acc: 100.0000	 Speed: 817.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.195,1460	LR: 0.000666	Loss: 0.065	Acc: 100.0000	 Speed: 1649.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.221,1461	LR: 0.000666	Loss: 0.037	Acc: 100.0000	 Speed: 1506.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.248,1462	LR: 0.000666	Loss: 0.067	Acc: 100.0000	 Speed: 1723.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.275,1463	LR: 0.000665	Loss: 0.082	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.302,1464	LR: 0.000665	Loss: 0.073	Acc: 100.0000	 Speed: 1599.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.329,1465	LR: 0.000664	Loss: 0.050	Acc: 100.0000	 Speed: 1906.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.356,1466	LR: 0.000664	Loss: 0.062	Acc: 100.0000	 Speed: 1791.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.383,1467	LR: 0.000664	Loss: 0.028	Acc: 100.0000	 Speed: 1677.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.409,1468	LR: 0.000663	Loss: 0.037	Acc: 100.0000	 Speed: 2112.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.436,1469	LR: 0.000663	Loss: 0.065	Acc: 100.0000	 Speed: 1552.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.463,1470	LR: 0.000663	Loss: 0.076	Acc: 100.0000	 Speed: 1462.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.490,1471	LR: 0.000662	Loss: 0.055	Acc: 100.0000	 Speed: 1801.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.517,1472	LR: 0.000662	Loss: 0.049	Acc: 100.0000	 Speed: 2074.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.544,1473	LR: 0.000661	Loss: 0.085	Acc: 100.0000	 Speed: 1516.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.570,1474	LR: 0.000661	Loss: 0.072	Acc: 100.0000	 Speed: 1804.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.597,1475	LR: 0.000661	Loss: 0.040	Acc: 100.0000	 Speed: 1644.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.624,1476	LR: 0.000660	Loss: 0.032	Acc: 100.0000	 Speed: 2145.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.651,1477	LR: 0.000660	Loss: 0.088	Acc: 100.0000	 Speed: 1437.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.678,1478	LR: 0.000659	Loss: 0.044	Acc: 100.0000	 Speed: 1772.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.705,1479	LR: 0.000659	Loss: 0.023	Acc: 100.0000	 Speed: 1534.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.732,1480	LR: 0.000659	Loss: 0.047	Acc: 100.0000	 Speed: 1566.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.758,1481	LR: 0.000658	Loss: 0.096	Acc: 100.0000	 Speed: 1870.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.785,1482	LR: 0.000658	Loss: 0.018	Acc: 100.0000	 Speed: 590.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3594.3406 samples/s	Time: 0.02s
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.812,1483	LR: 0.000657	Loss: 0.057	Acc: 100.0000	 Speed: 51.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.839,1484	LR: 0.000657	Loss: 0.052	Acc: 100.0000	 Speed: 2280.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.866,1485	LR: 0.000657	Loss: 0.060	Acc: 100.0000	 Speed: 1642.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.893,1486	LR: 0.000656	Loss: 0.060	Acc: 100.0000	 Speed: 1215.74 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.919,1487	LR: 0.000656	Loss: 0.058	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.946,1488	LR: 0.000655	Loss: 0.081	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 39.973,1489	LR: 0.000655	Loss: 0.032	Acc: 100.0000	 Speed: 1989.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.000,1490	LR: 0.000655	Loss: 0.032	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.027,1491	LR: 0.000654	Loss: 0.046	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.054,1492	LR: 0.000654	Loss: 0.052	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.081,1493	LR: 0.000653	Loss: 0.024	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.107,1494	LR: 0.000653	Loss: 0.069	Acc: 100.0000	 Speed: 1582.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.134,1495	LR: 0.000653	Loss: 0.052	Acc: 100.0000	 Speed: 1799.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.161,1496	LR: 0.000652	Loss: 0.068	Acc: 100.0000	 Speed: 1599.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.188,1497	LR: 0.000652	Loss: 0.060	Acc: 100.0000	 Speed: 1775.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.215,1498	LR: 0.000651	Loss: 0.056	Acc: 100.0000	 Speed: 2668.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.242,1499	LR: 0.000651	Loss: 0.077	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.268,1500	LR: 0.000650	Loss: 0.044	Acc: 100.0000	 Speed: 1836.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.295,1501	LR: 0.000650	Loss: 0.038	Acc: 100.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.322,1502	LR: 0.000650	Loss: 0.028	Acc: 100.0000	 Speed: 2035.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.349,1503	LR: 0.000649	Loss: 0.067	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.376,1504	LR: 0.000649	Loss: 0.029	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.403,1505	LR: 0.000648	Loss: 0.084	Acc: 100.0000	 Speed: 2069.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.430,1506	LR: 0.000648	Loss: 0.026	Acc: 100.0000	 Speed: 2623.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.456,1507	LR: 0.000648	Loss: 0.048	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.483,1508	LR: 0.000647	Loss: 0.045	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.510,1509	LR: 0.000647	Loss: 0.042	Acc: 100.0000	 Speed: 2110.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.537,1510	LR: 0.000646	Loss: 0.056	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.564,1511	LR: 0.000646	Loss: 0.051	Acc: 100.0000	 Speed: 1849.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.591,1512	LR: 0.000646	Loss: 0.030	Acc: 100.0000	 Speed: 930.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.617,1513	LR: 0.000645	Loss: 0.039	Acc: 100.0000	 Speed: 1460.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.644,1514	LR: 0.000645	Loss: 0.077	Acc: 100.0000	 Speed: 2217.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.671,1515	LR: 0.000644	Loss: 0.025	Acc: 100.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.698,1516	LR: 0.000644	Loss: 0.039	Acc: 100.0000	 Speed: 1285.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.725,1517	LR: 0.000644	Loss: 0.035	Acc: 100.0000	 Speed: 1383.63 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.752,1518	LR: 0.000643	Loss: 0.045	Acc: 100.0000	 Speed: 1744.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.779,1519	LR: 0.000643	Loss: 0.029	Acc: 100.0000	 Speed: 1996.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.805,1520	LR: 0.000642	Loss: 0.179	Acc: 100.0000	 Speed: 595.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:18 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 54.054	Speed: 3338.0134 samples/s	Time: 0.02s
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.832,1521	LR: 0.000642	Loss: 0.035	Acc: 100.0000	 Speed: 51.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.859,1522	LR: 0.000642	Loss: 0.074	Acc: 100.0000	 Speed: 2210.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.886,1523	LR: 0.000641	Loss: 0.034	Acc: 100.0000	 Speed: 1573.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.913,1524	LR: 0.000641	Loss: 0.032	Acc: 100.0000	 Speed: 1855.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.940,1525	LR: 0.000640	Loss: 0.029	Acc: 100.0000	 Speed: 2215.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.966,1526	LR: 0.000640	Loss: 0.042	Acc: 100.0000	 Speed: 1946.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 40.993,1527	LR: 0.000640	Loss: 0.080	Acc: 100.0000	 Speed: 1410.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.020,1528	LR: 0.000639	Loss: 0.038	Acc: 100.0000	 Speed: 2112.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.047,1529	LR: 0.000639	Loss: 0.101	Acc: 100.0000	 Speed: 1773.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.074,1530	LR: 0.000638	Loss: 0.061	Acc: 100.0000	 Speed: 1854.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.101,1531	LR: 0.000638	Loss: 0.064	Acc: 100.0000	 Speed: 2066.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.128,1532	LR: 0.000638	Loss: 0.038	Acc: 100.0000	 Speed: 2169.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.154,1533	LR: 0.000637	Loss: 0.019	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.181,1534	LR: 0.000637	Loss: 0.028	Acc: 100.0000	 Speed: 2025.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.208,1535	LR: 0.000636	Loss: 0.021	Acc: 100.0000	 Speed: 1571.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.235,1536	LR: 0.000636	Loss: 0.068	Acc: 100.0000	 Speed: 2221.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.262,1537	LR: 0.000636	Loss: 0.045	Acc: 100.0000	 Speed: 1716.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.289,1538	LR: 0.000635	Loss: 0.033	Acc: 100.0000	 Speed: 1915.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.315,1539	LR: 0.000635	Loss: 0.024	Acc: 100.0000	 Speed: 2356.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.342,1540	LR: 0.000634	Loss: 0.069	Acc: 100.0000	 Speed: 2185.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.369,1541	LR: 0.000634	Loss: 0.049	Acc: 100.0000	 Speed: 2664.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.396,1542	LR: 0.000634	Loss: 0.019	Acc: 100.0000	 Speed: 1423.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.423,1543	LR: 0.000633	Loss: 0.149	Acc: 100.0000	 Speed: 1961.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.450,1544	LR: 0.000633	Loss: 0.062	Acc: 100.0000	 Speed: 2448.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.477,1545	LR: 0.000632	Loss: 0.022	Acc: 100.0000	 Speed: 2281.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.503,1546	LR: 0.000632	Loss: 0.029	Acc: 100.0000	 Speed: 2120.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.530,1547	LR: 0.000631	Loss: 0.030	Acc: 100.0000	 Speed: 2664.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.557,1548	LR: 0.000631	Loss: 0.038	Acc: 100.0000	 Speed: 2003.97 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.584,1549	LR: 0.000631	Loss: 0.053	Acc: 100.0000	 Speed: 1915.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.611,1550	LR: 0.000630	Loss: 0.033	Acc: 100.0000	 Speed: 2079.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.638,1551	LR: 0.000630	Loss: 0.023	Acc: 100.0000	 Speed: 1315.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.664,1552	LR: 0.000629	Loss: 0.049	Acc: 100.0000	 Speed: 1899.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.691,1553	LR: 0.000629	Loss: 0.052	Acc: 100.0000	 Speed: 1775.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.718,1554	LR: 0.000629	Loss: 0.069	Acc: 100.0000	 Speed: 2020.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.745,1555	LR: 0.000628	Loss: 0.045	Acc: 100.0000	 Speed: 1846.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.772,1556	LR: 0.000628	Loss: 0.034	Acc: 100.0000	 Speed: 1917.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.799,1557	LR: 0.000627	Loss: 0.040	Acc: 100.0000	 Speed: 1082.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.826,1558	LR: 0.000627	Loss: 0.018	Acc: 100.0000	 Speed: 360.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3696.6984 samples/s	Time: 0.02s
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.852,1559	LR: 0.000627	Loss: 0.019	Acc: 100.0000	 Speed: 51.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.879,1560	LR: 0.000626	Loss: 0.034	Acc: 100.0000	 Speed: 2112.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.906,1561	LR: 0.000626	Loss: 0.029	Acc: 100.0000	 Speed: 1264.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.933,1562	LR: 0.000625	Loss: 0.061	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.960,1563	LR: 0.000625	Loss: 0.023	Acc: 100.0000	 Speed: 1455.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 41.987,1564	LR: 0.000625	Loss: 0.017	Acc: 100.0000	 Speed: 1931.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.013,1565	LR: 0.000624	Loss: 0.025	Acc: 100.0000	 Speed: 1868.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.040,1566	LR: 0.000624	Loss: 0.024	Acc: 100.0000	 Speed: 1744.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.067,1567	LR: 0.000623	Loss: 0.029	Acc: 100.0000	 Speed: 1826.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.094,1568	LR: 0.000623	Loss: 0.038	Acc: 100.0000	 Speed: 2110.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.121,1569	LR: 0.000623	Loss: 0.031	Acc: 100.0000	 Speed: 2180.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.148,1570	LR: 0.000622	Loss: 0.021	Acc: 100.0000	 Speed: 2703.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.174,1571	LR: 0.000622	Loss: 0.051	Acc: 100.0000	 Speed: 2004.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.201,1572	LR: 0.000621	Loss: 0.039	Acc: 100.0000	 Speed: 1566.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.228,1573	LR: 0.000621	Loss: 0.087	Acc: 100.0000	 Speed: 1716.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.255,1574	LR: 0.000620	Loss: 0.027	Acc: 100.0000	 Speed: 2334.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.282,1575	LR: 0.000620	Loss: 0.055	Acc: 100.0000	 Speed: 1847.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.309,1576	LR: 0.000620	Loss: 0.039	Acc: 100.0000	 Speed: 1843.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.336,1577	LR: 0.000619	Loss: 0.046	Acc: 100.0000	 Speed: 1868.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.362,1578	LR: 0.000619	Loss: 0.011	Acc: 100.0000	 Speed: 2670.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.389,1579	LR: 0.000618	Loss: 0.046	Acc: 100.0000	 Speed: 1964.20 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.416,1580	LR: 0.000618	Loss: 0.025	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.443,1581	LR: 0.000618	Loss: 0.031	Acc: 100.0000	 Speed: 1659.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.470,1582	LR: 0.000617	Loss: 0.026	Acc: 100.0000	 Speed: 1598.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.497,1583	LR: 0.000617	Loss: 0.045	Acc: 100.0000	 Speed: 1792.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.523,1584	LR: 0.000616	Loss: 0.047	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.550,1585	LR: 0.000616	Loss: 0.055	Acc: 100.0000	 Speed: 1824.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.577,1586	LR: 0.000616	Loss: 0.058	Acc: 100.0000	 Speed: 1604.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.604,1587	LR: 0.000615	Loss: 0.060	Acc: 100.0000	 Speed: 2008.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.631,1588	LR: 0.000615	Loss: 0.053	Acc: 100.0000	 Speed: 1996.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.658,1589	LR: 0.000614	Loss: 0.087	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.685,1590	LR: 0.000614	Loss: 0.029	Acc: 100.0000	 Speed: 2500.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.711,1591	LR: 0.000613	Loss: 0.075	Acc: 100.0000	 Speed: 1586.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.738,1592	LR: 0.000613	Loss: 0.055	Acc: 100.0000	 Speed: 1894.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.765,1593	LR: 0.000613	Loss: 0.051	Acc: 100.0000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.792,1594	LR: 0.000612	Loss: 0.035	Acc: 100.0000	 Speed: 1693.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.819,1595	LR: 0.000612	Loss: 0.023	Acc: 100.0000	 Speed: 1619.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.846,1596	LR: 0.000611	Loss: 0.006	Acc: 100.0000	 Speed: 665.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3762.3004 samples/s	Time: 0.02s
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.872,1597	LR: 0.000611	Loss: 0.038	Acc: 100.0000	 Speed: 53.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.899,1598	LR: 0.000611	Loss: 0.037	Acc: 100.0000	 Speed: 2103.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.926,1599	LR: 0.000610	Loss: 0.027	Acc: 100.0000	 Speed: 1655.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.953,1600	LR: 0.000610	Loss: 0.047	Acc: 100.0000	 Speed: 1749.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 42.980,1601	LR: 0.000609	Loss: 0.029	Acc: 100.0000	 Speed: 1749.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.007,1602	LR: 0.000609	Loss: 0.037	Acc: 100.0000	 Speed: 1263.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.034,1603	LR: 0.000609	Loss: 0.031	Acc: 100.0000	 Speed: 1203.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.060,1604	LR: 0.000608	Loss: 0.030	Acc: 100.0000	 Speed: 1250.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.087,1605	LR: 0.000608	Loss: 0.024	Acc: 100.0000	 Speed: 1685.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.114,1606	LR: 0.000607	Loss: 0.042	Acc: 100.0000	 Speed: 1923.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.141,1607	LR: 0.000607	Loss: 0.045	Acc: 100.0000	 Speed: 2746.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.168,1608	LR: 0.000606	Loss: 0.021	Acc: 100.0000	 Speed: 1726.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.195,1609	LR: 0.000606	Loss: 0.040	Acc: 100.0000	 Speed: 1176.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.221,1610	LR: 0.000606	Loss: 0.043	Acc: 100.0000	 Speed: 1788.62 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.248,1611	LR: 0.000605	Loss: 0.020	Acc: 100.0000	 Speed: 1954.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.275,1612	LR: 0.000605	Loss: 0.009	Acc: 100.0000	 Speed: 1698.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.302,1613	LR: 0.000604	Loss: 0.058	Acc: 100.0000	 Speed: 1572.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.329,1614	LR: 0.000604	Loss: 0.041	Acc: 100.0000	 Speed: 1400.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.356,1615	LR: 0.000604	Loss: 0.034	Acc: 100.0000	 Speed: 1223.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.383,1616	LR: 0.000603	Loss: 0.030	Acc: 100.0000	 Speed: 1819.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.409,1617	LR: 0.000603	Loss: 0.050	Acc: 100.0000	 Speed: 2668.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.436,1618	LR: 0.000602	Loss: 0.042	Acc: 100.0000	 Speed: 1831.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.463,1619	LR: 0.000602	Loss: 0.022	Acc: 100.0000	 Speed: 1801.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.490,1620	LR: 0.000602	Loss: 0.050	Acc: 100.0000	 Speed: 2490.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.517,1621	LR: 0.000601	Loss: 0.041	Acc: 100.0000	 Speed: 1214.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.544,1622	LR: 0.000601	Loss: 0.053	Acc: 100.0000	 Speed: 1685.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.570,1623	LR: 0.000600	Loss: 0.061	Acc: 100.0000	 Speed: 2119.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.597,1624	LR: 0.000600	Loss: 0.046	Acc: 100.0000	 Speed: 2027.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.624,1625	LR: 0.000599	Loss: 0.028	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.651,1626	LR: 0.000599	Loss: 0.045	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.678,1627	LR: 0.000599	Loss: 0.046	Acc: 100.0000	 Speed: 1846.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.705,1628	LR: 0.000598	Loss: 0.026	Acc: 100.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.732,1629	LR: 0.000598	Loss: 0.025	Acc: 100.0000	 Speed: 1995.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.758,1630	LR: 0.000597	Loss: 0.040	Acc: 100.0000	 Speed: 2334.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.785,1631	LR: 0.000597	Loss: 0.014	Acc: 100.0000	 Speed: 1798.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.812,1632	LR: 0.000597	Loss: 0.038	Acc: 100.0000	 Speed: 2042.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.839,1633	LR: 0.000596	Loss: 0.062	Acc: 100.0000	 Speed: 2260.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.866,1634	LR: 0.000596	Loss: 0.013	Acc: 100.0000	 Speed: 592.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:19 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3439.6686 samples/s	Time: 0.02s
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.893,1635	LR: 0.000595	Loss: 0.037	Acc: 100.0000	 Speed: 51.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.919,1636	LR: 0.000595	Loss: 0.041	Acc: 100.0000	 Speed: 1429.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.946,1637	LR: 0.000595	Loss: 0.020	Acc: 100.0000	 Speed: 1894.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 43.973,1638	LR: 0.000594	Loss: 0.036	Acc: 100.0000	 Speed: 2750.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.000,1639	LR: 0.000594	Loss: 0.016	Acc: 100.0000	 Speed: 1636.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.027,1640	LR: 0.000593	Loss: 0.028	Acc: 100.0000	 Speed: 1952.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.054,1641	LR: 0.000593	Loss: 0.047	Acc: 100.0000	 Speed: 1760.83 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.081,1642	LR: 0.000592	Loss: 0.027	Acc: 100.0000	 Speed: 819.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.107,1643	LR: 0.000592	Loss: 0.028	Acc: 100.0000	 Speed: 1096.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.134,1644	LR: 0.000592	Loss: 0.024	Acc: 100.0000	 Speed: 1610.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.161,1645	LR: 0.000591	Loss: 0.030	Acc: 100.0000	 Speed: 1499.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.188,1646	LR: 0.000591	Loss: 0.049	Acc: 100.0000	 Speed: 1935.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.215,1647	LR: 0.000590	Loss: 0.052	Acc: 100.0000	 Speed: 2134.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.242,1648	LR: 0.000590	Loss: 0.014	Acc: 100.0000	 Speed: 1813.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.268,1649	LR: 0.000590	Loss: 0.042	Acc: 100.0000	 Speed: 1904.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.295,1650	LR: 0.000589	Loss: 0.054	Acc: 100.0000	 Speed: 2466.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.322,1651	LR: 0.000589	Loss: 0.036	Acc: 100.0000	 Speed: 1853.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.349,1652	LR: 0.000588	Loss: 0.044	Acc: 100.0000	 Speed: 1564.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.376,1653	LR: 0.000588	Loss: 0.044	Acc: 100.0000	 Speed: 1482.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.403,1654	LR: 0.000587	Loss: 0.042	Acc: 100.0000	 Speed: 1767.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.430,1655	LR: 0.000587	Loss: 0.042	Acc: 100.0000	 Speed: 1795.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.456,1656	LR: 0.000587	Loss: 0.019	Acc: 100.0000	 Speed: 1819.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.483,1657	LR: 0.000586	Loss: 0.017	Acc: 100.0000	 Speed: 2083.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.510,1658	LR: 0.000586	Loss: 0.026	Acc: 100.0000	 Speed: 1611.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.537,1659	LR: 0.000585	Loss: 0.033	Acc: 100.0000	 Speed: 1549.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.564,1660	LR: 0.000585	Loss: 0.025	Acc: 100.0000	 Speed: 1947.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.591,1661	LR: 0.000585	Loss: 0.034	Acc: 100.0000	 Speed: 1842.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.617,1662	LR: 0.000584	Loss: 0.041	Acc: 100.0000	 Speed: 2364.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.644,1663	LR: 0.000584	Loss: 0.040	Acc: 100.0000	 Speed: 2916.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.671,1664	LR: 0.000583	Loss: 0.023	Acc: 100.0000	 Speed: 1805.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.698,1665	LR: 0.000583	Loss: 0.031	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.725,1666	LR: 0.000582	Loss: 0.041	Acc: 100.0000	 Speed: 2086.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.752,1667	LR: 0.000582	Loss: 0.027	Acc: 100.0000	 Speed: 2187.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.779,1668	LR: 0.000582	Loss: 0.017	Acc: 100.0000	 Speed: 1736.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.805,1669	LR: 0.000581	Loss: 0.037	Acc: 100.0000	 Speed: 2476.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.832,1670	LR: 0.000581	Loss: 0.023	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.859,1671	LR: 0.000580	Loss: 0.049	Acc: 100.0000	 Speed: 1612.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.886,1672	LR: 0.000580	Loss: 0.007	Acc: 100.0000	 Speed: 666.08 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3602.1830 samples/s	Time: 0.02s
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.913,1673	LR: 0.000580	Loss: 0.023	Acc: 100.0000	 Speed: 51.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.940,1674	LR: 0.000579	Loss: 0.062	Acc: 100.0000	 Speed: 2139.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.966,1675	LR: 0.000579	Loss: 0.013	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 44.993,1676	LR: 0.000578	Loss: 0.037	Acc: 100.0000	 Speed: 1888.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.020,1677	LR: 0.000578	Loss: 0.043	Acc: 100.0000	 Speed: 2153.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.047,1678	LR: 0.000577	Loss: 0.024	Acc: 100.0000	 Speed: 2281.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.074,1679	LR: 0.000577	Loss: 0.044	Acc: 100.0000	 Speed: 2478.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.101,1680	LR: 0.000577	Loss: 0.042	Acc: 100.0000	 Speed: 1633.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.128,1681	LR: 0.000576	Loss: 0.035	Acc: 100.0000	 Speed: 2598.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.154,1682	LR: 0.000576	Loss: 0.051	Acc: 100.0000	 Speed: 2336.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.181,1683	LR: 0.000575	Loss: 0.044	Acc: 100.0000	 Speed: 2227.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.208,1684	LR: 0.000575	Loss: 0.017	Acc: 100.0000	 Speed: 1981.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.235,1685	LR: 0.000575	Loss: 0.029	Acc: 100.0000	 Speed: 2025.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.262,1686	LR: 0.000574	Loss: 0.053	Acc: 100.0000	 Speed: 2033.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.289,1687	LR: 0.000574	Loss: 0.026	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.315,1688	LR: 0.000573	Loss: 0.017	Acc: 100.0000	 Speed: 1829.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.342,1689	LR: 0.000573	Loss: 0.066	Acc: 100.0000	 Speed: 1756.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.369,1690	LR: 0.000572	Loss: 0.037	Acc: 100.0000	 Speed: 1840.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.396,1691	LR: 0.000572	Loss: 0.016	Acc: 100.0000	 Speed: 2169.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.423,1692	LR: 0.000572	Loss: 0.033	Acc: 100.0000	 Speed: 1540.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.450,1693	LR: 0.000571	Loss: 0.021	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.477,1694	LR: 0.000571	Loss: 0.027	Acc: 100.0000	 Speed: 2352.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.503,1695	LR: 0.000570	Loss: 0.009	Acc: 100.0000	 Speed: 1501.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.530,1696	LR: 0.000570	Loss: 0.024	Acc: 100.0000	 Speed: 1454.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.557,1697	LR: 0.000570	Loss: 0.023	Acc: 100.0000	 Speed: 1195.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.584,1698	LR: 0.000569	Loss: 0.025	Acc: 100.0000	 Speed: 1764.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.611,1699	LR: 0.000569	Loss: 0.021	Acc: 100.0000	 Speed: 2056.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.638,1700	LR: 0.000568	Loss: 0.059	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.664,1701	LR: 0.000568	Loss: 0.036	Acc: 100.0000	 Speed: 1856.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.691,1702	LR: 0.000567	Loss: 0.015	Acc: 100.0000	 Speed: 1571.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.718,1703	LR: 0.000567	Loss: 0.019	Acc: 100.0000	 Speed: 1491.24 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.745,1704	LR: 0.000567	Loss: 0.027	Acc: 100.0000	 Speed: 2257.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.772,1705	LR: 0.000566	Loss: 0.029	Acc: 100.0000	 Speed: 2156.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.799,1706	LR: 0.000566	Loss: 0.028	Acc: 100.0000	 Speed: 1815.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.826,1707	LR: 0.000565	Loss: 0.023	Acc: 100.0000	 Speed: 2399.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.852,1708	LR: 0.000565	Loss: 0.017	Acc: 100.0000	 Speed: 1909.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.879,1709	LR: 0.000565	Loss: 0.019	Acc: 100.0000	 Speed: 2053.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.906,1710	LR: 0.000564	Loss: 0.029	Acc: 100.0000	 Speed: 570.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3693.3553 samples/s	Time: 0.02s
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.933,1711	LR: 0.000564	Loss: 0.048	Acc: 100.0000	 Speed: 52.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.960,1712	LR: 0.000563	Loss: 0.021	Acc: 100.0000	 Speed: 1477.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 45.987,1713	LR: 0.000563	Loss: 0.028	Acc: 100.0000	 Speed: 1523.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.013,1714	LR: 0.000562	Loss: 0.020	Acc: 100.0000	 Speed: 1249.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.040,1715	LR: 0.000562	Loss: 0.033	Acc: 100.0000	 Speed: 1934.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.067,1716	LR: 0.000562	Loss: 0.022	Acc: 100.0000	 Speed: 2062.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.094,1717	LR: 0.000561	Loss: 0.033	Acc: 100.0000	 Speed: 1786.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.121,1718	LR: 0.000561	Loss: 0.024	Acc: 100.0000	 Speed: 2340.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.148,1719	LR: 0.000560	Loss: 0.045	Acc: 100.0000	 Speed: 2017.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.174,1720	LR: 0.000560	Loss: 0.027	Acc: 100.0000	 Speed: 1940.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.201,1721	LR: 0.000560	Loss: 0.014	Acc: 100.0000	 Speed: 1506.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.228,1722	LR: 0.000559	Loss: 0.042	Acc: 100.0000	 Speed: 2018.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.255,1723	LR: 0.000559	Loss: 0.026	Acc: 100.0000	 Speed: 1598.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.282,1724	LR: 0.000558	Loss: 0.036	Acc: 100.0000	 Speed: 1830.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.309,1725	LR: 0.000558	Loss: 0.028	Acc: 100.0000	 Speed: 2241.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.336,1726	LR: 0.000557	Loss: 0.013	Acc: 100.0000	 Speed: 1649.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.362,1727	LR: 0.000557	Loss: 0.034	Acc: 100.0000	 Speed: 1611.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.389,1728	LR: 0.000557	Loss: 0.027	Acc: 100.0000	 Speed: 2663.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.416,1729	LR: 0.000556	Loss: 0.017	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.443,1730	LR: 0.000556	Loss: 0.047	Acc: 100.0000	 Speed: 1598.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.470,1731	LR: 0.000555	Loss: 0.024	Acc: 100.0000	 Speed: 2665.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.497,1732	LR: 0.000555	Loss: 0.028	Acc: 100.0000	 Speed: 1812.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.523,1733	LR: 0.000555	Loss: 0.012	Acc: 100.0000	 Speed: 2065.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.550,1734	LR: 0.000554	Loss: 0.047	Acc: 100.0000	 Speed: 1936.54 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.577,1735	LR: 0.000554	Loss: 0.021	Acc: 100.0000	 Speed: 2618.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.604,1736	LR: 0.000553	Loss: 0.027	Acc: 100.0000	 Speed: 1736.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.631,1737	LR: 0.000553	Loss: 0.022	Acc: 100.0000	 Speed: 1417.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.658,1738	LR: 0.000552	Loss: 0.013	Acc: 100.0000	 Speed: 2084.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.685,1739	LR: 0.000552	Loss: 0.038	Acc: 100.0000	 Speed: 1653.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.711,1740	LR: 0.000552	Loss: 0.015	Acc: 100.0000	 Speed: 1477.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.738,1741	LR: 0.000551	Loss: 0.025	Acc: 100.0000	 Speed: 2081.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.765,1742	LR: 0.000551	Loss: 0.022	Acc: 100.0000	 Speed: 2663.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.792,1743	LR: 0.000550	Loss: 0.030	Acc: 100.0000	 Speed: 1510.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.819,1744	LR: 0.000550	Loss: 0.025	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.846,1745	LR: 0.000549	Loss: 0.028	Acc: 100.0000	 Speed: 1599.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.872,1746	LR: 0.000549	Loss: 0.049	Acc: 100.0000	 Speed: 2413.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.899,1747	LR: 0.000549	Loss: 0.043	Acc: 100.0000	 Speed: 1283.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.926,1748	LR: 0.000548	Loss: 0.007	Acc: 100.0000	 Speed: 327.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:20 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 56.757	Speed: 3673.3357 samples/s	Time: 0.02s
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.953,1749	LR: 0.000548	Loss: 0.017	Acc: 100.0000	 Speed: 51.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 46.980,1750	LR: 0.000547	Loss: 0.024	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.007,1751	LR: 0.000547	Loss: 0.017	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.034,1752	LR: 0.000547	Loss: 0.032	Acc: 100.0000	 Speed: 1538.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.060,1753	LR: 0.000546	Loss: 0.038	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.087,1754	LR: 0.000546	Loss: 0.013	Acc: 100.0000	 Speed: 1996.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.114,1755	LR: 0.000545	Loss: 0.024	Acc: 100.0000	 Speed: 1764.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.141,1756	LR: 0.000545	Loss: 0.027	Acc: 100.0000	 Speed: 1598.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.168,1757	LR: 0.000544	Loss: 0.018	Acc: 100.0000	 Speed: 1303.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.195,1758	LR: 0.000544	Loss: 0.028	Acc: 100.0000	 Speed: 1455.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.221,1759	LR: 0.000544	Loss: 0.029	Acc: 100.0000	 Speed: 1601.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.248,1760	LR: 0.000543	Loss: 0.017	Acc: 100.0000	 Speed: 1546.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.275,1761	LR: 0.000543	Loss: 0.025	Acc: 100.0000	 Speed: 2530.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.302,1762	LR: 0.000542	Loss: 0.021	Acc: 100.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.329,1763	LR: 0.000542	Loss: 0.028	Acc: 100.0000	 Speed: 1969.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.356,1764	LR: 0.000541	Loss: 0.016	Acc: 100.0000	 Speed: 1735.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.383,1765	LR: 0.000541	Loss: 0.031	Acc: 100.0000	 Speed: 2011.17 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.409,1766	LR: 0.000541	Loss: 0.031	Acc: 100.0000	 Speed: 1524.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.436,1767	LR: 0.000540	Loss: 0.024	Acc: 100.0000	 Speed: 1928.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.463,1768	LR: 0.000540	Loss: 0.044	Acc: 100.0000	 Speed: 1971.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.490,1769	LR: 0.000539	Loss: 0.017	Acc: 100.0000	 Speed: 1235.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.517,1770	LR: 0.000539	Loss: 0.033	Acc: 100.0000	 Speed: 1142.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.544,1771	LR: 0.000539	Loss: 0.023	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.570,1772	LR: 0.000538	Loss: 0.032	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.597,1773	LR: 0.000538	Loss: 0.037	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.624,1774	LR: 0.000537	Loss: 0.027	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.651,1775	LR: 0.000537	Loss: 0.015	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.678,1776	LR: 0.000536	Loss: 0.026	Acc: 100.0000	 Speed: 2668.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.705,1777	LR: 0.000536	Loss: 0.044	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.732,1778	LR: 0.000536	Loss: 0.021	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.758,1779	LR: 0.000535	Loss: 0.031	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.785,1780	LR: 0.000535	Loss: 0.026	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.812,1781	LR: 0.000534	Loss: 0.030	Acc: 100.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.839,1782	LR: 0.000534	Loss: 0.043	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.866,1783	LR: 0.000533	Loss: 0.020	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.893,1784	LR: 0.000533	Loss: 0.032	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.919,1785	LR: 0.000533	Loss: 0.020	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.946,1786	LR: 0.000532	Loss: 0.016	Acc: 100.0000	 Speed: 499.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3872.7119 samples/s	Time: 0.02s
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 47.973,1787	LR: 0.000532	Loss: 0.026	Acc: 100.0000	 Speed: 50.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.000,1788	LR: 0.000531	Loss: 0.031	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.027,1789	LR: 0.000531	Loss: 0.022	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.054,1790	LR: 0.000531	Loss: 0.043	Acc: 100.0000	 Speed: 2665.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.081,1791	LR: 0.000530	Loss: 0.037	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.107,1792	LR: 0.000530	Loss: 0.020	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.134,1793	LR: 0.000529	Loss: 0.027	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.161,1794	LR: 0.000529	Loss: 0.016	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.188,1795	LR: 0.000528	Loss: 0.012	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.215,1796	LR: 0.000528	Loss: 0.022	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.242,1797	LR: 0.000528	Loss: 0.027	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.268,1798	LR: 0.000527	Loss: 0.023	Acc: 100.0000	 Speed: 2197.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.295,1799	LR: 0.000527	Loss: 0.024	Acc: 100.0000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.322,1800	LR: 0.000526	Loss: 0.032	Acc: 100.0000	 Speed: 2663.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.349,1801	LR: 0.000526	Loss: 0.015	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.376,1802	LR: 0.000526	Loss: 0.021	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.403,1803	LR: 0.000525	Loss: 0.030	Acc: 100.0000	 Speed: 1000.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.430,1804	LR: 0.000525	Loss: 0.038	Acc: 100.0000	 Speed: 1340.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.456,1805	LR: 0.000524	Loss: 0.028	Acc: 100.0000	 Speed: 1599.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.483,1806	LR: 0.000524	Loss: 0.031	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.510,1807	LR: 0.000523	Loss: 0.012	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.537,1808	LR: 0.000523	Loss: 0.029	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.564,1809	LR: 0.000523	Loss: 0.025	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.591,1810	LR: 0.000522	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.617,1811	LR: 0.000522	Loss: 0.011	Acc: 100.0000	 Speed: 1333.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.644,1812	LR: 0.000521	Loss: 0.018	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.671,1813	LR: 0.000521	Loss: 0.024	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.698,1814	LR: 0.000520	Loss: 0.020	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.725,1815	LR: 0.000520	Loss: 0.016	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.752,1816	LR: 0.000520	Loss: 0.029	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.779,1817	LR: 0.000519	Loss: 0.017	Acc: 100.0000	 Speed: 1748.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.805,1818	LR: 0.000519	Loss: 0.022	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.832,1819	LR: 0.000518	Loss: 0.009	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.859,1820	LR: 0.000518	Loss: 0.036	Acc: 100.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.886,1821	LR: 0.000517	Loss: 0.029	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.913,1822	LR: 0.000517	Loss: 0.033	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.940,1823	LR: 0.000517	Loss: 0.037	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.966,1824	LR: 0.000516	Loss: 0.017	Acc: 100.0000	 Speed: 499.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3774.8379 samples/s	Time: 0.02s
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 48.993,1825	LR: 0.000516	Loss: 0.028	Acc: 100.0000	 Speed: 53.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.020,1826	LR: 0.000515	Loss: 0.028	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.047,1827	LR: 0.000515	Loss: 0.028	Acc: 100.0000	 Speed: 2666.01 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.074,1828	LR: 0.000515	Loss: 0.017	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.101,1829	LR: 0.000514	Loss: 0.021	Acc: 100.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.128,1830	LR: 0.000514	Loss: 0.033	Acc: 100.0000	 Speed: 2670.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.154,1831	LR: 0.000513	Loss: 0.016	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.181,1832	LR: 0.000513	Loss: 0.022	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.208,1833	LR: 0.000512	Loss: 0.024	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.235,1834	LR: 0.000512	Loss: 0.024	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.262,1835	LR: 0.000512	Loss: 0.017	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.289,1836	LR: 0.000511	Loss: 0.022	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.315,1837	LR: 0.000511	Loss: 0.016	Acc: 100.0000	 Speed: 1333.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.342,1838	LR: 0.000510	Loss: 0.027	Acc: 100.0000	 Speed: 1142.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.369,1839	LR: 0.000510	Loss: 0.025	Acc: 100.0000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.396,1840	LR: 0.000509	Loss: 0.025	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.423,1841	LR: 0.000509	Loss: 0.015	Acc: 100.0000	 Speed: 1418.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.450,1842	LR: 0.000509	Loss: 0.012	Acc: 100.0000	 Speed: 1333.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.477,1843	LR: 0.000508	Loss: 0.012	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.503,1844	LR: 0.000508	Loss: 0.019	Acc: 100.0000	 Speed: 1683.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.530,1845	LR: 0.000507	Loss: 0.024	Acc: 100.0000	 Speed: 2161.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.557,1846	LR: 0.000507	Loss: 0.049	Acc: 100.0000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.584,1847	LR: 0.000507	Loss: 0.026	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.611,1848	LR: 0.000506	Loss: 0.022	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.638,1849	LR: 0.000506	Loss: 0.021	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.664,1850	LR: 0.000505	Loss: 0.033	Acc: 100.0000	 Speed: 2234.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.691,1851	LR: 0.000505	Loss: 0.018	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.718,1852	LR: 0.000504	Loss: 0.015	Acc: 100.0000	 Speed: 1638.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.745,1853	LR: 0.000504	Loss: 0.035	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.772,1854	LR: 0.000504	Loss: 0.034	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.799,1855	LR: 0.000503	Loss: 0.012	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.826,1856	LR: 0.000503	Loss: 0.024	Acc: 100.0000	 Speed: 999.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.852,1857	LR: 0.000502	Loss: 0.028	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.879,1858	LR: 0.000502	Loss: 0.026	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.906,1859	LR: 0.000501	Loss: 0.028	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.933,1860	LR: 0.000501	Loss: 0.017	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.960,1861	LR: 0.000501	Loss: 0.009	Acc: 100.0000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 49.987,1862	LR: 0.000500	Loss: 0.025	Acc: 100.0000	 Speed: 500.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:21 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3523.5449 samples/s	Time: 0.02s
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.013,1863	LR: 0.000500	Loss: 0.029	Acc: 100.0000	 Speed: 51.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.040,1864	LR: 0.000499	Loss: 0.021	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.067,1865	LR: 0.000499	Loss: 0.022	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.094,1866	LR: 0.000499	Loss: 0.019	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.121,1867	LR: 0.000498	Loss: 0.032	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.148,1868	LR: 0.000498	Loss: 0.031	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.174,1869	LR: 0.000497	Loss: 0.011	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.201,1870	LR: 0.000497	Loss: 0.014	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.228,1871	LR: 0.000496	Loss: 0.024	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.255,1872	LR: 0.000496	Loss: 0.004	Acc: 100.0000	 Speed: 1142.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.282,1873	LR: 0.000496	Loss: 0.015	Acc: 100.0000	 Speed: 2370.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.309,1874	LR: 0.000495	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.336,1875	LR: 0.000495	Loss: 0.033	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.362,1876	LR: 0.000494	Loss: 0.021	Acc: 100.0000	 Speed: 1599.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.389,1877	LR: 0.000494	Loss: 0.025	Acc: 100.0000	 Speed: 1600.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.416,1878	LR: 0.000493	Loss: 0.025	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.443,1879	LR: 0.000493	Loss: 0.020	Acc: 100.0000	 Speed: 2200.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.470,1880	LR: 0.000493	Loss: 0.029	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.497,1881	LR: 0.000492	Loss: 0.020	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.523,1882	LR: 0.000492	Loss: 0.024	Acc: 100.0000	 Speed: 1731.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.550,1883	LR: 0.000491	Loss: 0.031	Acc: 100.0000	 Speed: 1332.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.577,1884	LR: 0.000491	Loss: 0.029	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.604,1885	LR: 0.000491	Loss: 0.024	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.631,1886	LR: 0.000490	Loss: 0.028	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.658,1887	LR: 0.000490	Loss: 0.022	Acc: 100.0000	 Speed: 2666.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.685,1888	LR: 0.000489	Loss: 0.020	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.711,1889	LR: 0.000489	Loss: 0.016	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.738,1890	LR: 0.000488	Loss: 0.020	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.765,1891	LR: 0.000488	Loss: 0.023	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.792,1892	LR: 0.000488	Loss: 0.017	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.819,1893	LR: 0.000487	Loss: 0.023	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.846,1894	LR: 0.000487	Loss: 0.017	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.872,1895	LR: 0.000486	Loss: 0.019	Acc: 100.0000	 Speed: 1600.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.899,1896	LR: 0.000486	Loss: 0.019	Acc: 100.0000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.926,1897	LR: 0.000485	Loss: 0.023	Acc: 100.0000	 Speed: 1529.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.953,1898	LR: 0.000485	Loss: 0.016	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 50.980,1899	LR: 0.000485	Loss: 0.024	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.007,1900	LR: 0.000484	Loss: 0.002	Acc: 100.0000	 Speed: 499.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3616.8748 samples/s	Time: 0.02s
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.034,1901	LR: 0.000484	Loss: 0.009	Acc: 100.0000	 Speed: 53.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.060,1902	LR: 0.000483	Loss: 0.024	Acc: 100.0000	 Speed: 2664.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.087,1903	LR: 0.000483	Loss: 0.016	Acc: 100.0000	 Speed: 1656.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.114,1904	LR: 0.000483	Loss: 0.023	Acc: 100.0000	 Speed: 2100.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.141,1905	LR: 0.000482	Loss: 0.012	Acc: 100.0000	 Speed: 2153.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.168,1906	LR: 0.000482	Loss: 0.012	Acc: 100.0000	 Speed: 1651.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.195,1907	LR: 0.000481	Loss: 0.019	Acc: 100.0000	 Speed: 1402.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.221,1908	LR: 0.000481	Loss: 0.017	Acc: 100.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.248,1909	LR: 0.000480	Loss: 0.026	Acc: 100.0000	 Speed: 2029.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.275,1910	LR: 0.000480	Loss: 0.027	Acc: 100.0000	 Speed: 1554.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.302,1911	LR: 0.000480	Loss: 0.022	Acc: 100.0000	 Speed: 2324.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.329,1912	LR: 0.000479	Loss: 0.014	Acc: 100.0000	 Speed: 999.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.356,1913	LR: 0.000479	Loss: 0.016	Acc: 100.0000	 Speed: 1334.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.383,1914	LR: 0.000478	Loss: 0.029	Acc: 100.0000	 Speed: 1623.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.409,1915	LR: 0.000478	Loss: 0.008	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.436,1916	LR: 0.000477	Loss: 0.014	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.463,1917	LR: 0.000477	Loss: 0.031	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.490,1918	LR: 0.000477	Loss: 0.023	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.517,1919	LR: 0.000476	Loss: 0.015	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.544,1920	LR: 0.000476	Loss: 0.022	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.570,1921	LR: 0.000475	Loss: 0.018	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.597,1922	LR: 0.000475	Loss: 0.021	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.624,1923	LR: 0.000474	Loss: 0.023	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.651,1924	LR: 0.000474	Loss: 0.028	Acc: 100.0000	 Speed: 1756.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.678,1925	LR: 0.000474	Loss: 0.015	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.705,1926	LR: 0.000473	Loss: 0.014	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.732,1927	LR: 0.000473	Loss: 0.017	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.758,1928	LR: 0.000472	Loss: 0.017	Acc: 100.0000	 Speed: 2664.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.785,1929	LR: 0.000472	Loss: 0.015	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.812,1930	LR: 0.000472	Loss: 0.020	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.839,1931	LR: 0.000471	Loss: 0.026	Acc: 100.0000	 Speed: 2255.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.866,1932	LR: 0.000471	Loss: 0.025	Acc: 100.0000	 Speed: 2184.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.893,1933	LR: 0.000470	Loss: 0.057	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.919,1934	LR: 0.000470	Loss: 0.022	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.946,1935	LR: 0.000469	Loss: 0.015	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 51.973,1936	LR: 0.000469	Loss: 0.029	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.000,1937	LR: 0.000469	Loss: 0.013	Acc: 100.0000	 Speed: 2250.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.027,1938	LR: 0.000468	Loss: 0.037	Acc: 100.0000	 Speed: 666.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3894.7259 samples/s	Time: 0.02s
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.054,1939	LR: 0.000468	Loss: 0.012	Acc: 100.0000	 Speed: 53.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.081,1940	LR: 0.000467	Loss: 0.008	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.107,1941	LR: 0.000467	Loss: 0.021	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.134,1942	LR: 0.000467	Loss: 0.016	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.161,1943	LR: 0.000466	Loss: 0.034	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.188,1944	LR: 0.000466	Loss: 0.013	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.215,1945	LR: 0.000465	Loss: 0.035	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.242,1946	LR: 0.000465	Loss: 0.015	Acc: 100.0000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.268,1947	LR: 0.000464	Loss: 0.028	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.295,1948	LR: 0.000464	Loss: 0.013	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.322,1949	LR: 0.000464	Loss: 0.009	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.349,1950	LR: 0.000463	Loss: 0.016	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.376,1951	LR: 0.000463	Loss: 0.017	Acc: 100.0000	 Speed: 2666.22 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.403,1952	LR: 0.000462	Loss: 0.023	Acc: 100.0000	 Speed: 2001.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.430,1953	LR: 0.000462	Loss: 0.025	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.456,1954	LR: 0.000461	Loss: 0.010	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.483,1955	LR: 0.000461	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.510,1956	LR: 0.000461	Loss: 0.034	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.537,1957	LR: 0.000460	Loss: 0.022	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.564,1958	LR: 0.000460	Loss: 0.036	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.591,1959	LR: 0.000459	Loss: 0.035	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.617,1960	LR: 0.000459	Loss: 0.021	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.644,1961	LR: 0.000459	Loss: 0.018	Acc: 100.0000	 Speed: 1598.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.671,1962	LR: 0.000458	Loss: 0.012	Acc: 100.0000	 Speed: 1132.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.698,1963	LR: 0.000458	Loss: 0.012	Acc: 100.0000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.725,1964	LR: 0.000457	Loss: 0.017	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.752,1965	LR: 0.000457	Loss: 0.021	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.779,1966	LR: 0.000456	Loss: 0.017	Acc: 100.0000	 Speed: 1412.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.805,1967	LR: 0.000456	Loss: 0.005	Acc: 100.0000	 Speed: 1847.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.832,1968	LR: 0.000456	Loss: 0.014	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.859,1969	LR: 0.000455	Loss: 0.012	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.886,1970	LR: 0.000455	Loss: 0.016	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.913,1971	LR: 0.000454	Loss: 0.017	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.940,1972	LR: 0.000454	Loss: 0.027	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.966,1973	LR: 0.000453	Loss: 0.023	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 52.993,1974	LR: 0.000453	Loss: 0.012	Acc: 100.0000	 Speed: 1975.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.020,1975	LR: 0.000453	Loss: 0.039	Acc: 100.0000	 Speed: 1359.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.047,1976	LR: 0.000452	Loss: 0.014	Acc: 100.0000	 Speed: 500.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:22 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3430.6581 samples/s	Time: 0.02s
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.074,1977	LR: 0.000452	Loss: 0.020	Acc: 100.0000	 Speed: 51.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.101,1978	LR: 0.000451	Loss: 0.010	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.128,1979	LR: 0.000451	Loss: 0.020	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.154,1980	LR: 0.000451	Loss: 0.035	Acc: 100.0000	 Speed: 2001.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.181,1981	LR: 0.000450	Loss: 0.013	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.208,1982	LR: 0.000450	Loss: 0.013	Acc: 100.0000	 Speed: 1599.51 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.235,1983	LR: 0.000449	Loss: 0.023	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.262,1984	LR: 0.000449	Loss: 0.018	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.289,1985	LR: 0.000448	Loss: 0.012	Acc: 100.0000	 Speed: 1409.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.315,1986	LR: 0.000448	Loss: 0.027	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.342,1987	LR: 0.000448	Loss: 0.016	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.369,1988	LR: 0.000447	Loss: 0.033	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.396,1989	LR: 0.000447	Loss: 0.012	Acc: 100.0000	 Speed: 1733.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.423,1990	LR: 0.000446	Loss: 0.027	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.450,1991	LR: 0.000446	Loss: 0.012	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.477,1992	LR: 0.000445	Loss: 0.010	Acc: 100.0000	 Speed: 1678.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.503,1993	LR: 0.000445	Loss: 0.027	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.530,1994	LR: 0.000445	Loss: 0.011	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.557,1995	LR: 0.000444	Loss: 0.029	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.584,1996	LR: 0.000444	Loss: 0.019	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.611,1997	LR: 0.000443	Loss: 0.019	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.638,1998	LR: 0.000443	Loss: 0.010	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.664,1999	LR: 0.000443	Loss: 0.015	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.691,2000	LR: 0.000442	Loss: 0.021	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.718,2001	LR: 0.000442	Loss: 0.017	Acc: 100.0000	 Speed: 2563.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.745,2002	LR: 0.000441	Loss: 0.021	Acc: 100.0000	 Speed: 1723.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.772,2003	LR: 0.000441	Loss: 0.029	Acc: 100.0000	 Speed: 2064.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.799,2004	LR: 0.000440	Loss: 0.016	Acc: 100.0000	 Speed: 1747.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.826,2005	LR: 0.000440	Loss: 0.015	Acc: 100.0000	 Speed: 2282.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.852,2006	LR: 0.000440	Loss: 0.012	Acc: 100.0000	 Speed: 1972.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.879,2007	LR: 0.000439	Loss: 0.014	Acc: 100.0000	 Speed: 2178.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.906,2008	LR: 0.000439	Loss: 0.017	Acc: 100.0000	 Speed: 1792.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.933,2009	LR: 0.000438	Loss: 0.023	Acc: 100.0000	 Speed: 1597.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.960,2010	LR: 0.000438	Loss: 0.018	Acc: 100.0000	 Speed: 1996.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 53.987,2011	LR: 0.000438	Loss: 0.019	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.013,2012	LR: 0.000437	Loss: 0.012	Acc: 100.0000	 Speed: 1884.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.040,2013	LR: 0.000437	Loss: 0.012	Acc: 100.0000	 Speed: 952.41 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.067,2014	LR: 0.000436	Loss: 0.005	Acc: 100.0000	 Speed: 407.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3828.6664 samples/s	Time: 0.02s
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.094,2015	LR: 0.000436	Loss: 0.012	Acc: 100.0000	 Speed: 51.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.121,2016	LR: 0.000435	Loss: 0.014	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.148,2017	LR: 0.000435	Loss: 0.046	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.174,2018	LR: 0.000435	Loss: 0.020	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.201,2019	LR: 0.000434	Loss: 0.012	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.228,2020	LR: 0.000434	Loss: 0.017	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.255,2021	LR: 0.000433	Loss: 0.011	Acc: 100.0000	 Speed: 1333.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.282,2022	LR: 0.000433	Loss: 0.029	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.309,2023	LR: 0.000433	Loss: 0.018	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.336,2024	LR: 0.000432	Loss: 0.009	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.362,2025	LR: 0.000432	Loss: 0.011	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.389,2026	LR: 0.000431	Loss: 0.012	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.416,2027	LR: 0.000431	Loss: 0.013	Acc: 100.0000	 Speed: 2664.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.443,2028	LR: 0.000430	Loss: 0.023	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.470,2029	LR: 0.000430	Loss: 0.026	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.497,2030	LR: 0.000430	Loss: 0.011	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.523,2031	LR: 0.000429	Loss: 0.010	Acc: 100.0000	 Speed: 1535.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.550,2032	LR: 0.000429	Loss: 0.015	Acc: 100.0000	 Speed: 1332.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.577,2033	LR: 0.000428	Loss: 0.009	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.604,2034	LR: 0.000428	Loss: 0.022	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.631,2035	LR: 0.000428	Loss: 0.025	Acc: 100.0000	 Speed: 1871.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.658,2036	LR: 0.000427	Loss: 0.013	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.685,2037	LR: 0.000427	Loss: 0.014	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.711,2038	LR: 0.000426	Loss: 0.015	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.738,2039	LR: 0.000426	Loss: 0.013	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.765,2040	LR: 0.000425	Loss: 0.010	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.792,2041	LR: 0.000425	Loss: 0.027	Acc: 100.0000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.819,2042	LR: 0.000425	Loss: 0.025	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.846,2043	LR: 0.000424	Loss: 0.025	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.872,2044	LR: 0.000424	Loss: 0.027	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.899,2045	LR: 0.000423	Loss: 0.016	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.926,2046	LR: 0.000423	Loss: 0.012	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.953,2047	LR: 0.000423	Loss: 0.018	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 54.980,2048	LR: 0.000422	Loss: 0.019	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.007,2049	LR: 0.000422	Loss: 0.013	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.034,2050	LR: 0.000421	Loss: 0.032	Acc: 100.0000	 Speed: 2105.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.060,2051	LR: 0.000421	Loss: 0.009	Acc: 100.0000	 Speed: 2002.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.087,2052	LR: 0.000420	Loss: 0.002	Acc: 100.0000	 Speed: 499.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3699.8271 samples/s	Time: 0.02s
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.114,2053	LR: 0.000420	Loss: 0.015	Acc: 100.0000	 Speed: 52.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.141,2054	LR: 0.000420	Loss: 0.013	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.168,2055	LR: 0.000419	Loss: 0.014	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.195,2056	LR: 0.000419	Loss: 0.013	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.221,2057	LR: 0.000418	Loss: 0.010	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.248,2058	LR: 0.000418	Loss: 0.016	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.275,2059	LR: 0.000418	Loss: 0.018	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.302,2060	LR: 0.000417	Loss: 0.020	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.329,2061	LR: 0.000417	Loss: 0.016	Acc: 100.0000	 Speed: 2666.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.356,2062	LR: 0.000416	Loss: 0.013	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.383,2063	LR: 0.000416	Loss: 0.014	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.409,2064	LR: 0.000415	Loss: 0.008	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.436,2065	LR: 0.000415	Loss: 0.026	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.463,2066	LR: 0.000415	Loss: 0.028	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.490,2067	LR: 0.000414	Loss: 0.029	Acc: 100.0000	 Speed: 1276.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.517,2068	LR: 0.000414	Loss: 0.008	Acc: 100.0000	 Speed: 2121.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.544,2069	LR: 0.000413	Loss: 0.012	Acc: 100.0000	 Speed: 1600.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.570,2070	LR: 0.000413	Loss: 0.016	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.597,2071	LR: 0.000413	Loss: 0.030	Acc: 100.0000	 Speed: 2325.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.624,2072	LR: 0.000412	Loss: 0.017	Acc: 100.0000	 Speed: 1175.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.651,2073	LR: 0.000412	Loss: 0.015	Acc: 100.0000	 Speed: 1142.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.678,2074	LR: 0.000411	Loss: 0.008	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.705,2075	LR: 0.000411	Loss: 0.015	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.732,2076	LR: 0.000410	Loss: 0.017	Acc: 100.0000	 Speed: 2240.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.758,2077	LR: 0.000410	Loss: 0.014	Acc: 100.0000	 Speed: 1752.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.785,2078	LR: 0.000410	Loss: 0.015	Acc: 100.0000	 Speed: 1851.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.812,2079	LR: 0.000409	Loss: 0.017	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.839,2080	LR: 0.000409	Loss: 0.012	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.866,2081	LR: 0.000408	Loss: 0.023	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.893,2082	LR: 0.000408	Loss: 0.011	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.919,2083	LR: 0.000408	Loss: 0.012	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.946,2084	LR: 0.000407	Loss: 0.023	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 55.973,2085	LR: 0.000407	Loss: 0.017	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.000,2086	LR: 0.000406	Loss: 0.032	Acc: 100.0000	 Speed: 1730.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.027,2087	LR: 0.000406	Loss: 0.022	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.054,2088	LR: 0.000405	Loss: 0.008	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.081,2089	LR: 0.000405	Loss: 0.021	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:23 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.107,2090	LR: 0.000405	Loss: 0.015	Acc: 100.0000	 Speed: 499.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3523.7849 samples/s	Time: 0.02s
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.134,2091	LR: 0.000404	Loss: 0.012	Acc: 100.0000	 Speed: 53.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.161,2092	LR: 0.000404	Loss: 0.010	Acc: 100.0000	 Speed: 2192.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.188,2093	LR: 0.000403	Loss: 0.015	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.215,2094	LR: 0.000403	Loss: 0.021	Acc: 100.0000	 Speed: 2425.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.242,2095	LR: 0.000403	Loss: 0.010	Acc: 100.0000	 Speed: 1713.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.268,2096	LR: 0.000402	Loss: 0.012	Acc: 100.0000	 Speed: 1525.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.295,2097	LR: 0.000402	Loss: 0.015	Acc: 100.0000	 Speed: 1779.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.322,2098	LR: 0.000401	Loss: 0.018	Acc: 100.0000	 Speed: 1544.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.349,2099	LR: 0.000401	Loss: 0.014	Acc: 100.0000	 Speed: 2681.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.376,2100	LR: 0.000401	Loss: 0.013	Acc: 100.0000	 Speed: 1983.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.403,2101	LR: 0.000400	Loss: 0.026	Acc: 100.0000	 Speed: 2208.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.430,2102	LR: 0.000400	Loss: 0.008	Acc: 100.0000	 Speed: 2058.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.456,2103	LR: 0.000399	Loss: 0.018	Acc: 100.0000	 Speed: 1857.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.483,2104	LR: 0.000399	Loss: 0.013	Acc: 100.0000	 Speed: 2664.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.510,2105	LR: 0.000398	Loss: 0.017	Acc: 100.0000	 Speed: 1430.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.537,2106	LR: 0.000398	Loss: 0.025	Acc: 100.0000	 Speed: 1598.97 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.564,2107	LR: 0.000398	Loss: 0.012	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.591,2108	LR: 0.000397	Loss: 0.011	Acc: 100.0000	 Speed: 2064.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.617,2109	LR: 0.000397	Loss: 0.019	Acc: 100.0000	 Speed: 1939.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.644,2110	LR: 0.000396	Loss: 0.029	Acc: 100.0000	 Speed: 1717.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.671,2111	LR: 0.000396	Loss: 0.017	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.698,2112	LR: 0.000396	Loss: 0.017	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.725,2113	LR: 0.000395	Loss: 0.030	Acc: 100.0000	 Speed: 2113.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.752,2114	LR: 0.000395	Loss: 0.022	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.779,2115	LR: 0.000394	Loss: 0.014	Acc: 100.0000	 Speed: 2001.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.805,2116	LR: 0.000394	Loss: 0.017	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.832,2117	LR: 0.000394	Loss: 0.018	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.859,2118	LR: 0.000393	Loss: 0.011	Acc: 100.0000	 Speed: 1276.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.886,2119	LR: 0.000393	Loss: 0.009	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.913,2120	LR: 0.000392	Loss: 0.018	Acc: 100.0000	 Speed: 1603.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.940,2121	LR: 0.000392	Loss: 0.021	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.966,2122	LR: 0.000391	Loss: 0.011	Acc: 100.0000	 Speed: 1452.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 56.993,2123	LR: 0.000391	Loss: 0.008	Acc: 100.0000	 Speed: 2532.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.020,2124	LR: 0.000391	Loss: 0.014	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.047,2125	LR: 0.000390	Loss: 0.013	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.074,2126	LR: 0.000390	Loss: 0.015	Acc: 100.0000	 Speed: 1925.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.101,2127	LR: 0.000389	Loss: 0.016	Acc: 100.0000	 Speed: 2614.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.128,2128	LR: 0.000389	Loss: 0.022	Acc: 100.0000	 Speed: 500.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3483.1330 samples/s	Time: 0.02s
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.154,2129	LR: 0.000389	Loss: 0.016	Acc: 100.0000	 Speed: 49.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.181,2130	LR: 0.000388	Loss: 0.021	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.208,2131	LR: 0.000388	Loss: 0.015	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.235,2132	LR: 0.000387	Loss: 0.017	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.262,2133	LR: 0.000387	Loss: 0.016	Acc: 100.0000	 Speed: 2119.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.289,2134	LR: 0.000387	Loss: 0.021	Acc: 100.0000	 Speed: 1452.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.315,2135	LR: 0.000386	Loss: 0.014	Acc: 100.0000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.342,2136	LR: 0.000386	Loss: 0.006	Acc: 100.0000	 Speed: 2667.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.369,2137	LR: 0.000385	Loss: 0.027	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.396,2138	LR: 0.000385	Loss: 0.016	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.423,2139	LR: 0.000384	Loss: 0.012	Acc: 100.0000	 Speed: 1899.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.450,2140	LR: 0.000384	Loss: 0.013	Acc: 100.0000	 Speed: 1721.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.477,2141	LR: 0.000384	Loss: 0.014	Acc: 100.0000	 Speed: 1858.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.503,2142	LR: 0.000383	Loss: 0.014	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.530,2143	LR: 0.000383	Loss: 0.012	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.557,2144	LR: 0.000382	Loss: 0.010	Acc: 100.0000	 Speed: 1434.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.584,2145	LR: 0.000382	Loss: 0.019	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.611,2146	LR: 0.000382	Loss: 0.008	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.638,2147	LR: 0.000381	Loss: 0.016	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.664,2148	LR: 0.000381	Loss: 0.008	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.691,2149	LR: 0.000380	Loss: 0.011	Acc: 100.0000	 Speed: 2635.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.718,2150	LR: 0.000380	Loss: 0.016	Acc: 100.0000	 Speed: 1218.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.745,2151	LR: 0.000380	Loss: 0.010	Acc: 100.0000	 Speed: 1600.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.772,2152	LR: 0.000379	Loss: 0.012	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.799,2153	LR: 0.000379	Loss: 0.015	Acc: 100.0000	 Speed: 1332.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.826,2154	LR: 0.000378	Loss: 0.016	Acc: 100.0000	 Speed: 2668.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.852,2155	LR: 0.000378	Loss: 0.013	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.879,2156	LR: 0.000377	Loss: 0.014	Acc: 100.0000	 Speed: 1781.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.906,2157	LR: 0.000377	Loss: 0.015	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.933,2158	LR: 0.000377	Loss: 0.040	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.960,2159	LR: 0.000376	Loss: 0.008	Acc: 100.0000	 Speed: 2413.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 57.987,2160	LR: 0.000376	Loss: 0.012	Acc: 100.0000	 Speed: 2030.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.013,2161	LR: 0.000375	Loss: 0.019	Acc: 100.0000	 Speed: 1599.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.040,2162	LR: 0.000375	Loss: 0.024	Acc: 100.0000	 Speed: 2072.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.067,2163	LR: 0.000375	Loss: 0.022	Acc: 100.0000	 Speed: 1801.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.094,2164	LR: 0.000374	Loss: 0.022	Acc: 100.0000	 Speed: 1973.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.121,2165	LR: 0.000374	Loss: 0.009	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.148,2166	LR: 0.000373	Loss: 0.005	Acc: 100.0000	 Speed: 400.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3359.0019 samples/s	Time: 0.02s
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.174,2167	LR: 0.000373	Loss: 0.020	Acc: 100.0000	 Speed: 53.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.201,2168	LR: 0.000373	Loss: 0.018	Acc: 100.0000	 Speed: 1503.60 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.228,2169	LR: 0.000372	Loss: 0.013	Acc: 100.0000	 Speed: 1382.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.255,2170	LR: 0.000372	Loss: 0.032	Acc: 100.0000	 Speed: 1599.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.282,2171	LR: 0.000371	Loss: 0.010	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.309,2172	LR: 0.000371	Loss: 0.014	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.336,2173	LR: 0.000371	Loss: 0.009	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.362,2174	LR: 0.000370	Loss: 0.012	Acc: 100.0000	 Speed: 2662.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.389,2175	LR: 0.000370	Loss: 0.030	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.416,2176	LR: 0.000369	Loss: 0.022	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.443,2177	LR: 0.000369	Loss: 0.016	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.470,2178	LR: 0.000369	Loss: 0.010	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.497,2179	LR: 0.000368	Loss: 0.014	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.523,2180	LR: 0.000368	Loss: 0.010	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.550,2181	LR: 0.000367	Loss: 0.009	Acc: 100.0000	 Speed: 1591.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.577,2182	LR: 0.000367	Loss: 0.017	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.604,2183	LR: 0.000366	Loss: 0.007	Acc: 100.0000	 Speed: 2281.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.631,2184	LR: 0.000366	Loss: 0.007	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.658,2185	LR: 0.000366	Loss: 0.013	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.685,2186	LR: 0.000365	Loss: 0.018	Acc: 100.0000	 Speed: 1967.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.711,2187	LR: 0.000365	Loss: 0.013	Acc: 100.0000	 Speed: 1146.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.738,2188	LR: 0.000364	Loss: 0.013	Acc: 100.0000	 Speed: 1598.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.765,2189	LR: 0.000364	Loss: 0.012	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.792,2190	LR: 0.000364	Loss: 0.013	Acc: 100.0000	 Speed: 1868.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.819,2191	LR: 0.000363	Loss: 0.014	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.846,2192	LR: 0.000363	Loss: 0.014	Acc: 100.0000	 Speed: 1928.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.872,2193	LR: 0.000362	Loss: 0.018	Acc: 100.0000	 Speed: 1600.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.899,2194	LR: 0.000362	Loss: 0.015	Acc: 100.0000	 Speed: 1333.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.926,2195	LR: 0.000362	Loss: 0.009	Acc: 100.0000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.953,2196	LR: 0.000361	Loss: 0.015	Acc: 100.0000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 58.980,2197	LR: 0.000361	Loss: 0.014	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.007,2198	LR: 0.000360	Loss: 0.012	Acc: 100.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.034,2199	LR: 0.000360	Loss: 0.014	Acc: 100.0000	 Speed: 1815.03 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.060,2200	LR: 0.000360	Loss: 0.014	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.087,2201	LR: 0.000359	Loss: 0.015	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.114,2202	LR: 0.000359	Loss: 0.021	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.141,2203	LR: 0.000358	Loss: 0.018	Acc: 100.0000	 Speed: 1784.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:24 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.168,2204	LR: 0.000358	Loss: 0.010	Acc: 100.0000	 Speed: 399.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3324.5340 samples/s	Time: 0.02s
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.195,2205	LR: 0.000358	Loss: 0.011	Acc: 100.0000	 Speed: 52.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.221,2206	LR: 0.000357	Loss: 0.007	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.248,2207	LR: 0.000357	Loss: 0.013	Acc: 100.0000	 Speed: 1839.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.275,2208	LR: 0.000356	Loss: 0.009	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.302,2209	LR: 0.000356	Loss: 0.010	Acc: 100.0000	 Speed: 1785.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.329,2210	LR: 0.000356	Loss: 0.013	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.356,2211	LR: 0.000355	Loss: 0.012	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.383,2212	LR: 0.000355	Loss: 0.020	Acc: 100.0000	 Speed: 2401.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.409,2213	LR: 0.000354	Loss: 0.005	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.436,2214	LR: 0.000354	Loss: 0.012	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.463,2215	LR: 0.000354	Loss: 0.012	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.490,2216	LR: 0.000353	Loss: 0.019	Acc: 100.0000	 Speed: 2323.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.517,2217	LR: 0.000353	Loss: 0.013	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.544,2218	LR: 0.000352	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.570,2219	LR: 0.000352	Loss: 0.007	Acc: 100.0000	 Speed: 1663.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.597,2220	LR: 0.000352	Loss: 0.021	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.624,2221	LR: 0.000351	Loss: 0.013	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.651,2222	LR: 0.000351	Loss: 0.016	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.678,2223	LR: 0.000350	Loss: 0.029	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.705,2224	LR: 0.000350	Loss: 0.014	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.732,2225	LR: 0.000350	Loss: 0.009	Acc: 100.0000	 Speed: 1620.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.758,2226	LR: 0.000349	Loss: 0.017	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.785,2227	LR: 0.000349	Loss: 0.017	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.812,2228	LR: 0.000348	Loss: 0.015	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.839,2229	LR: 0.000348	Loss: 0.015	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.866,2230	LR: 0.000347	Loss: 0.029	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.893,2231	LR: 0.000347	Loss: 0.012	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.919,2232	LR: 0.000347	Loss: 0.013	Acc: 100.0000	 Speed: 1831.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.946,2233	LR: 0.000346	Loss: 0.019	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 59.973,2234	LR: 0.000346	Loss: 0.007	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.000,2235	LR: 0.000345	Loss: 0.026	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.027,2236	LR: 0.000345	Loss: 0.020	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.054,2237	LR: 0.000345	Loss: 0.012	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.081,2238	LR: 0.000344	Loss: 0.014	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.107,2239	LR: 0.000344	Loss: 0.009	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.134,2240	LR: 0.000343	Loss: 0.012	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.161,2241	LR: 0.000343	Loss: 0.010	Acc: 100.0000	 Speed: 2053.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.188,2242	LR: 0.000343	Loss: 0.023	Acc: 100.0000	 Speed: 499.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3476.4227 samples/s	Time: 0.02s
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.215,2243	LR: 0.000342	Loss: 0.014	Acc: 100.0000	 Speed: 51.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.242,2244	LR: 0.000342	Loss: 0.013	Acc: 100.0000	 Speed: 2042.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.268,2245	LR: 0.000341	Loss: 0.017	Acc: 100.0000	 Speed: 1221.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.295,2246	LR: 0.000341	Loss: 0.017	Acc: 100.0000	 Speed: 1881.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.322,2247	LR: 0.000341	Loss: 0.008	Acc: 100.0000	 Speed: 2501.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.349,2248	LR: 0.000340	Loss: 0.011	Acc: 100.0000	 Speed: 2038.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.376,2249	LR: 0.000340	Loss: 0.010	Acc: 100.0000	 Speed: 2143.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.403,2250	LR: 0.000339	Loss: 0.013	Acc: 100.0000	 Speed: 2114.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.430,2251	LR: 0.000339	Loss: 0.011	Acc: 100.0000	 Speed: 1599.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.456,2252	LR: 0.000339	Loss: 0.011	Acc: 100.0000	 Speed: 2298.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.483,2253	LR: 0.000338	Loss: 0.016	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.510,2254	LR: 0.000338	Loss: 0.011	Acc: 100.0000	 Speed: 1791.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.537,2255	LR: 0.000337	Loss: 0.011	Acc: 100.0000	 Speed: 1391.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.564,2256	LR: 0.000337	Loss: 0.013	Acc: 100.0000	 Speed: 1757.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.591,2257	LR: 0.000337	Loss: 0.013	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.617,2258	LR: 0.000336	Loss: 0.015	Acc: 100.0000	 Speed: 1758.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.644,2259	LR: 0.000336	Loss: 0.011	Acc: 100.0000	 Speed: 2664.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.671,2260	LR: 0.000336	Loss: 0.011	Acc: 100.0000	 Speed: 2349.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.698,2261	LR: 0.000335	Loss: 0.012	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.725,2262	LR: 0.000335	Loss: 0.021	Acc: 100.0000	 Speed: 2411.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.752,2263	LR: 0.000334	Loss: 0.009	Acc: 100.0000	 Speed: 1276.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.779,2264	LR: 0.000334	Loss: 0.010	Acc: 100.0000	 Speed: 1768.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.805,2265	LR: 0.000334	Loss: 0.016	Acc: 100.0000	 Speed: 2216.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.832,2266	LR: 0.000333	Loss: 0.010	Acc: 100.0000	 Speed: 1946.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.859,2267	LR: 0.000333	Loss: 0.019	Acc: 100.0000	 Speed: 1295.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.886,2268	LR: 0.000332	Loss: 0.013	Acc: 100.0000	 Speed: 1598.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.913,2269	LR: 0.000332	Loss: 0.011	Acc: 100.0000	 Speed: 1851.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.940,2270	LR: 0.000332	Loss: 0.013	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.966,2271	LR: 0.000331	Loss: 0.012	Acc: 100.0000	 Speed: 1675.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 60.993,2272	LR: 0.000331	Loss: 0.024	Acc: 100.0000	 Speed: 2215.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.020,2273	LR: 0.000330	Loss: 0.006	Acc: 100.0000	 Speed: 2039.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.047,2274	LR: 0.000330	Loss: 0.035	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.074,2275	LR: 0.000330	Loss: 0.017	Acc: 100.0000	 Speed: 2225.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.101,2276	LR: 0.000329	Loss: 0.010	Acc: 100.0000	 Speed: 1899.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.128,2277	LR: 0.000329	Loss: 0.005	Acc: 100.0000	 Speed: 1730.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.154,2278	LR: 0.000328	Loss: 0.021	Acc: 100.0000	 Speed: 2749.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.181,2279	LR: 0.000328	Loss: 0.018	Acc: 100.0000	 Speed: 1743.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.208,2280	LR: 0.000328	Loss: 0.017	Acc: 100.0000	 Speed: 513.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3773.1400 samples/s	Time: 0.02s
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.235,2281	LR: 0.000327	Loss: 0.014	Acc: 100.0000	 Speed: 52.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.262,2282	LR: 0.000327	Loss: 0.010	Acc: 100.0000	 Speed: 1600.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.289,2283	LR: 0.000326	Loss: 0.011	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.315,2284	LR: 0.000326	Loss: 0.014	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.342,2285	LR: 0.000326	Loss: 0.008	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.369,2286	LR: 0.000325	Loss: 0.011	Acc: 100.0000	 Speed: 3055.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.396,2287	LR: 0.000325	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.423,2288	LR: 0.000324	Loss: 0.009	Acc: 100.0000	 Speed: 2403.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.450,2289	LR: 0.000324	Loss: 0.012	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.477,2290	LR: 0.000324	Loss: 0.014	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.503,2291	LR: 0.000323	Loss: 0.008	Acc: 100.0000	 Speed: 1850.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.530,2292	LR: 0.000323	Loss: 0.013	Acc: 100.0000	 Speed: 1536.73 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.557,2293	LR: 0.000322	Loss: 0.008	Acc: 100.0000	 Speed: 1867.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.584,2294	LR: 0.000322	Loss: 0.013	Acc: 100.0000	 Speed: 1598.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.611,2295	LR: 0.000322	Loss: 0.016	Acc: 100.0000	 Speed: 1729.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.638,2296	LR: 0.000321	Loss: 0.017	Acc: 100.0000	 Speed: 1977.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.664,2297	LR: 0.000321	Loss: 0.010	Acc: 100.0000	 Speed: 2136.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.691,2298	LR: 0.000320	Loss: 0.010	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.718,2299	LR: 0.000320	Loss: 0.015	Acc: 100.0000	 Speed: 1045.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.745,2300	LR: 0.000320	Loss: 0.009	Acc: 100.0000	 Speed: 1111.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.772,2301	LR: 0.000319	Loss: 0.014	Acc: 100.0000	 Speed: 1688.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.799,2302	LR: 0.000319	Loss: 0.014	Acc: 100.0000	 Speed: 1804.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.826,2303	LR: 0.000318	Loss: 0.014	Acc: 100.0000	 Speed: 2664.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.852,2304	LR: 0.000318	Loss: 0.032	Acc: 100.0000	 Speed: 1619.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.879,2305	LR: 0.000318	Loss: 0.007	Acc: 100.0000	 Speed: 1875.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.906,2306	LR: 0.000317	Loss: 0.020	Acc: 100.0000	 Speed: 2389.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.933,2307	LR: 0.000317	Loss: 0.012	Acc: 100.0000	 Speed: 1600.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.960,2308	LR: 0.000317	Loss: 0.010	Acc: 100.0000	 Speed: 1664.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 61.987,2309	LR: 0.000316	Loss: 0.008	Acc: 100.0000	 Speed: 1911.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.013,2310	LR: 0.000316	Loss: 0.010	Acc: 100.0000	 Speed: 2281.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.040,2311	LR: 0.000315	Loss: 0.015	Acc: 100.0000	 Speed: 2065.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.067,2312	LR: 0.000315	Loss: 0.023	Acc: 100.0000	 Speed: 1790.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.094,2313	LR: 0.000315	Loss: 0.017	Acc: 100.0000	 Speed: 2343.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.121,2314	LR: 0.000314	Loss: 0.020	Acc: 100.0000	 Speed: 1681.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.148,2315	LR: 0.000314	Loss: 0.013	Acc: 100.0000	 Speed: 1825.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.174,2316	LR: 0.000313	Loss: 0.006	Acc: 100.0000	 Speed: 1816.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.201,2317	LR: 0.000313	Loss: 0.021	Acc: 100.0000	 Speed: 2232.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:25 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.228,2318	LR: 0.000313	Loss: 0.014	Acc: 100.0000	 Speed: 439.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3526.7879 samples/s	Time: 0.02s
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.255,2319	LR: 0.000312	Loss: 0.014	Acc: 100.0000	 Speed: 51.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.282,2320	LR: 0.000312	Loss: 0.011	Acc: 100.0000	 Speed: 2079.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.309,2321	LR: 0.000311	Loss: 0.021	Acc: 100.0000	 Speed: 2298.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.336,2322	LR: 0.000311	Loss: 0.027	Acc: 100.0000	 Speed: 1924.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.362,2323	LR: 0.000311	Loss: 0.012	Acc: 100.0000	 Speed: 2366.65 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.389,2324	LR: 0.000310	Loss: 0.018	Acc: 100.0000	 Speed: 2168.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.416,2325	LR: 0.000310	Loss: 0.010	Acc: 100.0000	 Speed: 1125.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.443,2326	LR: 0.000309	Loss: 0.020	Acc: 100.0000	 Speed: 2223.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.470,2327	LR: 0.000309	Loss: 0.008	Acc: 100.0000	 Speed: 1724.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.497,2328	LR: 0.000309	Loss: 0.011	Acc: 100.0000	 Speed: 1983.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.523,2329	LR: 0.000308	Loss: 0.011	Acc: 100.0000	 Speed: 1667.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.550,2330	LR: 0.000308	Loss: 0.005	Acc: 100.0000	 Speed: 1647.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.577,2331	LR: 0.000308	Loss: 0.007	Acc: 100.0000	 Speed: 1766.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.604,2332	LR: 0.000307	Loss: 0.010	Acc: 100.0000	 Speed: 1149.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.631,2333	LR: 0.000307	Loss: 0.006	Acc: 100.0000	 Speed: 1441.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.658,2334	LR: 0.000306	Loss: 0.013	Acc: 100.0000	 Speed: 1547.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.685,2335	LR: 0.000306	Loss: 0.009	Acc: 100.0000	 Speed: 1578.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.711,2336	LR: 0.000306	Loss: 0.012	Acc: 100.0000	 Speed: 1637.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.738,2337	LR: 0.000305	Loss: 0.020	Acc: 100.0000	 Speed: 2395.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.765,2338	LR: 0.000305	Loss: 0.008	Acc: 100.0000	 Speed: 1832.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.792,2339	LR: 0.000304	Loss: 0.011	Acc: 100.0000	 Speed: 1893.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.819,2340	LR: 0.000304	Loss: 0.013	Acc: 100.0000	 Speed: 1951.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.846,2341	LR: 0.000304	Loss: 0.022	Acc: 100.0000	 Speed: 1916.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.872,2342	LR: 0.000303	Loss: 0.015	Acc: 100.0000	 Speed: 2111.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.899,2343	LR: 0.000303	Loss: 0.017	Acc: 100.0000	 Speed: 1661.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.926,2344	LR: 0.000302	Loss: 0.014	Acc: 100.0000	 Speed: 1865.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.953,2345	LR: 0.000302	Loss: 0.012	Acc: 100.0000	 Speed: 2528.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 62.980,2346	LR: 0.000302	Loss: 0.014	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.007,2347	LR: 0.000301	Loss: 0.017	Acc: 100.0000	 Speed: 2123.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.034,2348	LR: 0.000301	Loss: 0.011	Acc: 100.0000	 Speed: 1890.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.060,2349	LR: 0.000301	Loss: 0.008	Acc: 100.0000	 Speed: 2036.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.087,2350	LR: 0.000300	Loss: 0.012	Acc: 100.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.114,2351	LR: 0.000300	Loss: 0.006	Acc: 100.0000	 Speed: 1923.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.141,2352	LR: 0.000299	Loss: 0.016	Acc: 100.0000	 Speed: 1720.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.168,2353	LR: 0.000299	Loss: 0.010	Acc: 100.0000	 Speed: 1996.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.195,2354	LR: 0.000299	Loss: 0.013	Acc: 100.0000	 Speed: 1564.82 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.221,2355	LR: 0.000298	Loss: 0.010	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.248,2356	LR: 0.000298	Loss: 0.040	Acc: 100.0000	 Speed: 242.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3714.1275 samples/s	Time: 0.02s
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.275,2357	LR: 0.000297	Loss: 0.006	Acc: 100.0000	 Speed: 52.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.302,2358	LR: 0.000297	Loss: 0.011	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.329,2359	LR: 0.000297	Loss: 0.010	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.356,2360	LR: 0.000296	Loss: 0.011	Acc: 100.0000	 Speed: 1599.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.383,2361	LR: 0.000296	Loss: 0.014	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.409,2362	LR: 0.000296	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.436,2363	LR: 0.000295	Loss: 0.012	Acc: 100.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.463,2364	LR: 0.000295	Loss: 0.012	Acc: 100.0000	 Speed: 2001.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.490,2365	LR: 0.000294	Loss: 0.014	Acc: 100.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.517,2366	LR: 0.000294	Loss: 0.017	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.544,2367	LR: 0.000294	Loss: 0.009	Acc: 100.0000	 Speed: 2240.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.570,2368	LR: 0.000293	Loss: 0.018	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.597,2369	LR: 0.000293	Loss: 0.016	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.624,2370	LR: 0.000292	Loss: 0.015	Acc: 100.0000	 Speed: 1333.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.651,2371	LR: 0.000292	Loss: 0.018	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.678,2372	LR: 0.000292	Loss: 0.009	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.705,2373	LR: 0.000291	Loss: 0.012	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.732,2374	LR: 0.000291	Loss: 0.017	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.758,2375	LR: 0.000291	Loss: 0.013	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.785,2376	LR: 0.000290	Loss: 0.009	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.812,2377	LR: 0.000290	Loss: 0.008	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.839,2378	LR: 0.000289	Loss: 0.019	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.866,2379	LR: 0.000289	Loss: 0.014	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.893,2380	LR: 0.000289	Loss: 0.014	Acc: 100.0000	 Speed: 1753.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.919,2381	LR: 0.000288	Loss: 0.007	Acc: 100.0000	 Speed: 1533.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.946,2382	LR: 0.000288	Loss: 0.012	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 63.973,2383	LR: 0.000287	Loss: 0.008	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.000,2384	LR: 0.000287	Loss: 0.015	Acc: 100.0000	 Speed: 1142.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.027,2385	LR: 0.000287	Loss: 0.010	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.054,2386	LR: 0.000286	Loss: 0.010	Acc: 100.0000	 Speed: 1333.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.081,2387	LR: 0.000286	Loss: 0.007	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.107,2388	LR: 0.000286	Loss: 0.013	Acc: 100.0000	 Speed: 1965.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.134,2389	LR: 0.000285	Loss: 0.013	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.161,2390	LR: 0.000285	Loss: 0.012	Acc: 100.0000	 Speed: 1353.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.188,2391	LR: 0.000284	Loss: 0.014	Acc: 100.0000	 Speed: 2187.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.215,2392	LR: 0.000284	Loss: 0.024	Acc: 100.0000	 Speed: 1805.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.242,2393	LR: 0.000284	Loss: 0.014	Acc: 100.0000	 Speed: 1916.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.268,2394	LR: 0.000283	Loss: 0.003	Acc: 100.0000	 Speed: 624.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3658.3981 samples/s	Time: 0.02s
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.295,2395	LR: 0.000283	Loss: 0.011	Acc: 100.0000	 Speed: 52.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.322,2396	LR: 0.000283	Loss: 0.008	Acc: 100.0000	 Speed: 2453.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.349,2397	LR: 0.000282	Loss: 0.015	Acc: 100.0000	 Speed: 1797.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.376,2398	LR: 0.000282	Loss: 0.010	Acc: 100.0000	 Speed: 1936.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.403,2399	LR: 0.000281	Loss: 0.009	Acc: 100.0000	 Speed: 1958.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.430,2400	LR: 0.000281	Loss: 0.015	Acc: 100.0000	 Speed: 1839.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.456,2401	LR: 0.000281	Loss: 0.010	Acc: 100.0000	 Speed: 1628.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.483,2402	LR: 0.000280	Loss: 0.017	Acc: 100.0000	 Speed: 2664.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.510,2403	LR: 0.000280	Loss: 0.009	Acc: 100.0000	 Speed: 1854.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.537,2404	LR: 0.000280	Loss: 0.011	Acc: 100.0000	 Speed: 1798.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.564,2405	LR: 0.000279	Loss: 0.008	Acc: 100.0000	 Speed: 2089.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.591,2406	LR: 0.000279	Loss: 0.019	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.617,2407	LR: 0.000278	Loss: 0.006	Acc: 100.0000	 Speed: 1776.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.644,2408	LR: 0.000278	Loss: 0.014	Acc: 100.0000	 Speed: 2469.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.671,2409	LR: 0.000278	Loss: 0.009	Acc: 100.0000	 Speed: 2050.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.698,2410	LR: 0.000277	Loss: 0.013	Acc: 100.0000	 Speed: 1851.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.725,2411	LR: 0.000277	Loss: 0.014	Acc: 100.0000	 Speed: 2029.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.752,2412	LR: 0.000276	Loss: 0.015	Acc: 100.0000	 Speed: 2175.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.779,2413	LR: 0.000276	Loss: 0.021	Acc: 100.0000	 Speed: 1857.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.805,2414	LR: 0.000276	Loss: 0.010	Acc: 100.0000	 Speed: 1368.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.832,2415	LR: 0.000275	Loss: 0.016	Acc: 100.0000	 Speed: 1306.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.859,2416	LR: 0.000275	Loss: 0.009	Acc: 100.0000	 Speed: 2210.44 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.886,2417	LR: 0.000275	Loss: 0.006	Acc: 100.0000	 Speed: 2281.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.913,2418	LR: 0.000274	Loss: 0.016	Acc: 100.0000	 Speed: 1560.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.940,2419	LR: 0.000274	Loss: 0.019	Acc: 100.0000	 Speed: 971.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.966,2420	LR: 0.000273	Loss: 0.013	Acc: 100.0000	 Speed: 1492.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 64.993,2421	LR: 0.000273	Loss: 0.009	Acc: 100.0000	 Speed: 1446.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.020,2422	LR: 0.000273	Loss: 0.010	Acc: 100.0000	 Speed: 1379.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.047,2423	LR: 0.000272	Loss: 0.013	Acc: 100.0000	 Speed: 1838.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.074,2424	LR: 0.000272	Loss: 0.014	Acc: 100.0000	 Speed: 2164.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.101,2425	LR: 0.000272	Loss: 0.021	Acc: 100.0000	 Speed: 1817.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:26 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.128,2426	LR: 0.000271	Loss: 0.009	Acc: 100.0000	 Speed: 1436.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.154,2427	LR: 0.000271	Loss: 0.009	Acc: 100.0000	 Speed: 1956.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.181,2428	LR: 0.000270	Loss: 0.009	Acc: 100.0000	 Speed: 2668.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.208,2429	LR: 0.000270	Loss: 0.014	Acc: 100.0000	 Speed: 1781.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.235,2430	LR: 0.000270	Loss: 0.011	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.262,2431	LR: 0.000269	Loss: 0.018	Acc: 100.0000	 Speed: 1863.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.289,2432	LR: 0.000269	Loss: 0.006	Acc: 100.0000	 Speed: 521.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3015.6086 samples/s	Time: 0.02s
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.315,2433	LR: 0.000269	Loss: 0.011	Acc: 100.0000	 Speed: 51.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.342,2434	LR: 0.000268	Loss: 0.009	Acc: 100.0000	 Speed: 1954.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.369,2435	LR: 0.000268	Loss: 0.014	Acc: 100.0000	 Speed: 1364.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.396,2436	LR: 0.000267	Loss: 0.012	Acc: 100.0000	 Speed: 1898.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.423,2437	LR: 0.000267	Loss: 0.015	Acc: 100.0000	 Speed: 2546.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.450,2438	LR: 0.000267	Loss: 0.017	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.477,2439	LR: 0.000266	Loss: 0.015	Acc: 100.0000	 Speed: 1716.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.503,2440	LR: 0.000266	Loss: 0.007	Acc: 100.0000	 Speed: 2281.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.530,2441	LR: 0.000266	Loss: 0.009	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.557,2442	LR: 0.000265	Loss: 0.007	Acc: 100.0000	 Speed: 2054.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.584,2443	LR: 0.000265	Loss: 0.005	Acc: 100.0000	 Speed: 2578.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.611,2444	LR: 0.000264	Loss: 0.011	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.638,2445	LR: 0.000264	Loss: 0.012	Acc: 100.0000	 Speed: 1837.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.664,2446	LR: 0.000264	Loss: 0.011	Acc: 100.0000	 Speed: 2055.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.691,2447	LR: 0.000263	Loss: 0.011	Acc: 100.0000	 Speed: 1559.87 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.718,2448	LR: 0.000263	Loss: 0.026	Acc: 100.0000	 Speed: 1831.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.745,2449	LR: 0.000263	Loss: 0.010	Acc: 100.0000	 Speed: 1807.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.772,2450	LR: 0.000262	Loss: 0.016	Acc: 100.0000	 Speed: 1536.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.799,2451	LR: 0.000262	Loss: 0.009	Acc: 100.0000	 Speed: 1953.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.826,2452	LR: 0.000262	Loss: 0.018	Acc: 100.0000	 Speed: 1475.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.852,2453	LR: 0.000261	Loss: 0.007	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.879,2454	LR: 0.000261	Loss: 0.006	Acc: 100.0000	 Speed: 2053.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.906,2455	LR: 0.000260	Loss: 0.015	Acc: 100.0000	 Speed: 1081.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.933,2456	LR: 0.000260	Loss: 0.013	Acc: 100.0000	 Speed: 1476.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.960,2457	LR: 0.000260	Loss: 0.009	Acc: 100.0000	 Speed: 1657.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 65.987,2458	LR: 0.000259	Loss: 0.018	Acc: 100.0000	 Speed: 1618.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.013,2459	LR: 0.000259	Loss: 0.011	Acc: 100.0000	 Speed: 1827.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.040,2460	LR: 0.000259	Loss: 0.011	Acc: 100.0000	 Speed: 1882.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.067,2461	LR: 0.000258	Loss: 0.016	Acc: 100.0000	 Speed: 1727.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.094,2462	LR: 0.000258	Loss: 0.021	Acc: 100.0000	 Speed: 1609.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.121,2463	LR: 0.000257	Loss: 0.010	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.148,2464	LR: 0.000257	Loss: 0.012	Acc: 100.0000	 Speed: 2175.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.174,2465	LR: 0.000257	Loss: 0.010	Acc: 100.0000	 Speed: 2072.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.201,2466	LR: 0.000256	Loss: 0.009	Acc: 100.0000	 Speed: 1588.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.228,2467	LR: 0.000256	Loss: 0.010	Acc: 100.0000	 Speed: 2168.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.255,2468	LR: 0.000256	Loss: 0.008	Acc: 100.0000	 Speed: 1343.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.282,2469	LR: 0.000255	Loss: 0.009	Acc: 100.0000	 Speed: 1581.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.309,2470	LR: 0.000255	Loss: 0.032	Acc: 100.0000	 Speed: 455.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3776.6292 samples/s	Time: 0.02s
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.336,2471	LR: 0.000255	Loss: 0.007	Acc: 100.0000	 Speed: 51.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.362,2472	LR: 0.000254	Loss: 0.008	Acc: 100.0000	 Speed: 1833.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.389,2473	LR: 0.000254	Loss: 0.008	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.416,2474	LR: 0.000253	Loss: 0.018	Acc: 100.0000	 Speed: 2471.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.443,2475	LR: 0.000253	Loss: 0.009	Acc: 100.0000	 Speed: 1903.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.470,2476	LR: 0.000253	Loss: 0.009	Acc: 100.0000	 Speed: 1899.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.497,2477	LR: 0.000252	Loss: 0.008	Acc: 100.0000	 Speed: 1630.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.523,2478	LR: 0.000252	Loss: 0.012	Acc: 100.0000	 Speed: 2806.73 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.550,2479	LR: 0.000252	Loss: 0.014	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.577,2480	LR: 0.000251	Loss: 0.007	Acc: 100.0000	 Speed: 1761.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.604,2481	LR: 0.000251	Loss: 0.013	Acc: 100.0000	 Speed: 1401.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.631,2482	LR: 0.000250	Loss: 0.020	Acc: 100.0000	 Speed: 837.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.658,2483	LR: 0.000250	Loss: 0.010	Acc: 100.0000	 Speed: 1257.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.685,2484	LR: 0.000250	Loss: 0.012	Acc: 100.0000	 Speed: 1598.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.711,2485	LR: 0.000249	Loss: 0.018	Acc: 100.0000	 Speed: 1927.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.738,2486	LR: 0.000249	Loss: 0.012	Acc: 100.0000	 Speed: 1744.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.765,2487	LR: 0.000249	Loss: 0.008	Acc: 100.0000	 Speed: 1884.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.792,2488	LR: 0.000248	Loss: 0.016	Acc: 100.0000	 Speed: 1945.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.819,2489	LR: 0.000248	Loss: 0.009	Acc: 100.0000	 Speed: 1818.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.846,2490	LR: 0.000248	Loss: 0.013	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.872,2491	LR: 0.000247	Loss: 0.006	Acc: 100.0000	 Speed: 1857.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.899,2492	LR: 0.000247	Loss: 0.017	Acc: 100.0000	 Speed: 2355.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.926,2493	LR: 0.000246	Loss: 0.008	Acc: 100.0000	 Speed: 1500.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.953,2494	LR: 0.000246	Loss: 0.015	Acc: 100.0000	 Speed: 1501.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 66.980,2495	LR: 0.000246	Loss: 0.013	Acc: 100.0000	 Speed: 1482.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.007,2496	LR: 0.000245	Loss: 0.010	Acc: 100.0000	 Speed: 1807.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.034,2497	LR: 0.000245	Loss: 0.006	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.060,2498	LR: 0.000245	Loss: 0.011	Acc: 100.0000	 Speed: 1705.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.087,2499	LR: 0.000244	Loss: 0.013	Acc: 100.0000	 Speed: 1332.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.114,2500	LR: 0.000244	Loss: 0.017	Acc: 100.0000	 Speed: 2192.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.141,2501	LR: 0.000244	Loss: 0.014	Acc: 100.0000	 Speed: 1411.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.168,2502	LR: 0.000243	Loss: 0.016	Acc: 100.0000	 Speed: 2136.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.195,2503	LR: 0.000243	Loss: 0.008	Acc: 100.0000	 Speed: 2136.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.221,2504	LR: 0.000242	Loss: 0.016	Acc: 100.0000	 Speed: 2210.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.248,2505	LR: 0.000242	Loss: 0.010	Acc: 100.0000	 Speed: 1732.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.275,2506	LR: 0.000242	Loss: 0.007	Acc: 100.0000	 Speed: 1915.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.302,2507	LR: 0.000241	Loss: 0.013	Acc: 100.0000	 Speed: 2392.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.329,2508	LR: 0.000241	Loss: 0.010	Acc: 100.0000	 Speed: 481.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3856.0646 samples/s	Time: 0.02s
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.356,2509	LR: 0.000241	Loss: 0.011	Acc: 100.0000	 Speed: 53.59 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.383,2510	LR: 0.000240	Loss: 0.018	Acc: 100.0000	 Speed: 1801.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.409,2511	LR: 0.000240	Loss: 0.015	Acc: 100.0000	 Speed: 1608.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.436,2512	LR: 0.000240	Loss: 0.006	Acc: 100.0000	 Speed: 1601.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.463,2513	LR: 0.000239	Loss: 0.015	Acc: 100.0000	 Speed: 1975.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.490,2514	LR: 0.000239	Loss: 0.012	Acc: 100.0000	 Speed: 1472.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.517,2515	LR: 0.000239	Loss: 0.009	Acc: 100.0000	 Speed: 1623.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.544,2516	LR: 0.000238	Loss: 0.011	Acc: 100.0000	 Speed: 1686.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.570,2517	LR: 0.000238	Loss: 0.011	Acc: 100.0000	 Speed: 1767.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.597,2518	LR: 0.000237	Loss: 0.015	Acc: 100.0000	 Speed: 1361.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.624,2519	LR: 0.000237	Loss: 0.015	Acc: 100.0000	 Speed: 2271.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.651,2520	LR: 0.000237	Loss: 0.009	Acc: 100.0000	 Speed: 1370.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.678,2521	LR: 0.000236	Loss: 0.008	Acc: 100.0000	 Speed: 1823.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.705,2522	LR: 0.000236	Loss: 0.012	Acc: 100.0000	 Speed: 1653.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.732,2523	LR: 0.000236	Loss: 0.014	Acc: 100.0000	 Speed: 2281.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.758,2524	LR: 0.000235	Loss: 0.008	Acc: 100.0000	 Speed: 1435.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.785,2525	LR: 0.000235	Loss: 0.007	Acc: 100.0000	 Speed: 1703.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.812,2526	LR: 0.000235	Loss: 0.005	Acc: 100.0000	 Speed: 1528.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.839,2527	LR: 0.000234	Loss: 0.017	Acc: 100.0000	 Speed: 1967.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.866,2528	LR: 0.000234	Loss: 0.012	Acc: 100.0000	 Speed: 2171.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.893,2529	LR: 0.000234	Loss: 0.011	Acc: 100.0000	 Speed: 1613.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.919,2530	LR: 0.000233	Loss: 0.005	Acc: 100.0000	 Speed: 2716.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.946,2531	LR: 0.000233	Loss: 0.014	Acc: 100.0000	 Speed: 2022.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 67.973,2532	LR: 0.000232	Loss: 0.020	Acc: 100.0000	 Speed: 1552.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:27 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.000,2533	LR: 0.000232	Loss: 0.025	Acc: 100.0000	 Speed: 1775.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.027,2534	LR: 0.000232	Loss: 0.008	Acc: 100.0000	 Speed: 2131.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.054,2535	LR: 0.000231	Loss: 0.014	Acc: 100.0000	 Speed: 2159.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.081,2536	LR: 0.000231	Loss: 0.011	Acc: 100.0000	 Speed: 1906.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.107,2537	LR: 0.000231	Loss: 0.012	Acc: 100.0000	 Speed: 1802.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.134,2538	LR: 0.000230	Loss: 0.006	Acc: 100.0000	 Speed: 1832.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.161,2539	LR: 0.000230	Loss: 0.014	Acc: 100.0000	 Speed: 1786.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.188,2540	LR: 0.000230	Loss: 0.007	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.215,2541	LR: 0.000229	Loss: 0.010	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.242,2542	LR: 0.000229	Loss: 0.004	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.268,2543	LR: 0.000229	Loss: 0.014	Acc: 100.0000	 Speed: 1511.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.295,2544	LR: 0.000228	Loss: 0.009	Acc: 100.0000	 Speed: 2283.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.322,2545	LR: 0.000228	Loss: 0.013	Acc: 100.0000	 Speed: 1830.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.349,2546	LR: 0.000227	Loss: 0.011	Acc: 100.0000	 Speed: 439.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3412.4027 samples/s	Time: 0.02s
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.376,2547	LR: 0.000227	Loss: 0.008	Acc: 100.0000	 Speed: 49.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.403,2548	LR: 0.000227	Loss: 0.014	Acc: 100.0000	 Speed: 1659.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.430,2549	LR: 0.000226	Loss: 0.014	Acc: 100.0000	 Speed: 2170.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.456,2550	LR: 0.000226	Loss: 0.013	Acc: 100.0000	 Speed: 1987.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.483,2551	LR: 0.000226	Loss: 0.010	Acc: 100.0000	 Speed: 1776.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.510,2552	LR: 0.000225	Loss: 0.016	Acc: 100.0000	 Speed: 1345.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.537,2553	LR: 0.000225	Loss: 0.010	Acc: 100.0000	 Speed: 1695.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.564,2554	LR: 0.000225	Loss: 0.011	Acc: 100.0000	 Speed: 2021.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.591,2555	LR: 0.000224	Loss: 0.006	Acc: 100.0000	 Speed: 1728.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.617,2556	LR: 0.000224	Loss: 0.012	Acc: 100.0000	 Speed: 1779.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.644,2557	LR: 0.000224	Loss: 0.008	Acc: 100.0000	 Speed: 2438.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.671,2558	LR: 0.000223	Loss: 0.004	Acc: 100.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.698,2559	LR: 0.000223	Loss: 0.006	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.725,2560	LR: 0.000223	Loss: 0.010	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.752,2561	LR: 0.000222	Loss: 0.009	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.779,2562	LR: 0.000222	Loss: 0.011	Acc: 100.0000	 Speed: 1333.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.805,2563	LR: 0.000221	Loss: 0.012	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.832,2564	LR: 0.000221	Loss: 0.007	Acc: 100.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.859,2565	LR: 0.000221	Loss: 0.008	Acc: 100.0000	 Speed: 2471.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.886,2566	LR: 0.000220	Loss: 0.012	Acc: 100.0000	 Speed: 2395.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.913,2567	LR: 0.000220	Loss: 0.010	Acc: 100.0000	 Speed: 1692.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.940,2568	LR: 0.000220	Loss: 0.011	Acc: 100.0000	 Speed: 2977.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.966,2569	LR: 0.000219	Loss: 0.015	Acc: 100.0000	 Speed: 2360.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 68.993,2570	LR: 0.000219	Loss: 0.012	Acc: 100.0000	 Speed: 1444.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.020,2571	LR: 0.000219	Loss: 0.005	Acc: 100.0000	 Speed: 1248.35 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.047,2572	LR: 0.000218	Loss: 0.015	Acc: 100.0000	 Speed: 2301.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.074,2573	LR: 0.000218	Loss: 0.016	Acc: 100.0000	 Speed: 1670.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.101,2574	LR: 0.000218	Loss: 0.021	Acc: 100.0000	 Speed: 1832.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.128,2575	LR: 0.000217	Loss: 0.017	Acc: 100.0000	 Speed: 2990.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.154,2576	LR: 0.000217	Loss: 0.015	Acc: 100.0000	 Speed: 1733.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.181,2577	LR: 0.000217	Loss: 0.015	Acc: 100.0000	 Speed: 1593.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.208,2578	LR: 0.000216	Loss: 0.008	Acc: 100.0000	 Speed: 1759.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.235,2579	LR: 0.000216	Loss: 0.008	Acc: 100.0000	 Speed: 2663.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.262,2580	LR: 0.000216	Loss: 0.011	Acc: 100.0000	 Speed: 1618.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.289,2581	LR: 0.000215	Loss: 0.013	Acc: 100.0000	 Speed: 2089.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.315,2582	LR: 0.000215	Loss: 0.011	Acc: 100.0000	 Speed: 2563.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.342,2583	LR: 0.000215	Loss: 0.011	Acc: 100.0000	 Speed: 1348.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.369,2584	LR: 0.000214	Loss: 0.018	Acc: 100.0000	 Speed: 508.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3281.8239 samples/s	Time: 0.02s
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.396,2585	LR: 0.000214	Loss: 0.012	Acc: 100.0000	 Speed: 52.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.423,2586	LR: 0.000213	Loss: 0.008	Acc: 100.0000	 Speed: 2021.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.450,2587	LR: 0.000213	Loss: 0.013	Acc: 100.0000	 Speed: 2225.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.477,2588	LR: 0.000213	Loss: 0.015	Acc: 100.0000	 Speed: 1181.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.503,2589	LR: 0.000212	Loss: 0.010	Acc: 100.0000	 Speed: 1915.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.530,2590	LR: 0.000212	Loss: 0.014	Acc: 100.0000	 Speed: 1621.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.557,2591	LR: 0.000212	Loss: 0.010	Acc: 100.0000	 Speed: 1946.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.584,2592	LR: 0.000211	Loss: 0.006	Acc: 100.0000	 Speed: 2236.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.611,2593	LR: 0.000211	Loss: 0.012	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.638,2594	LR: 0.000211	Loss: 0.016	Acc: 100.0000	 Speed: 1799.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.664,2595	LR: 0.000210	Loss: 0.006	Acc: 100.0000	 Speed: 2064.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.691,2596	LR: 0.000210	Loss: 0.019	Acc: 100.0000	 Speed: 1170.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.718,2597	LR: 0.000210	Loss: 0.011	Acc: 100.0000	 Speed: 2663.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.745,2598	LR: 0.000209	Loss: 0.017	Acc: 100.0000	 Speed: 1640.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.772,2599	LR: 0.000209	Loss: 0.008	Acc: 100.0000	 Speed: 1504.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.799,2600	LR: 0.000209	Loss: 0.017	Acc: 100.0000	 Speed: 2130.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.826,2601	LR: 0.000208	Loss: 0.006	Acc: 100.0000	 Speed: 1450.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.852,2602	LR: 0.000208	Loss: 0.010	Acc: 100.0000	 Speed: 1674.04 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.879,2603	LR: 0.000208	Loss: 0.008	Acc: 100.0000	 Speed: 1491.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.906,2604	LR: 0.000207	Loss: 0.009	Acc: 100.0000	 Speed: 842.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.933,2605	LR: 0.000207	Loss: 0.008	Acc: 100.0000	 Speed: 1598.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.960,2606	LR: 0.000207	Loss: 0.011	Acc: 100.0000	 Speed: 1250.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 69.987,2607	LR: 0.000206	Loss: 0.012	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.013,2608	LR: 0.000206	Loss: 0.008	Acc: 100.0000	 Speed: 1747.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.040,2609	LR: 0.000206	Loss: 0.011	Acc: 100.0000	 Speed: 2322.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.067,2610	LR: 0.000205	Loss: 0.009	Acc: 100.0000	 Speed: 2032.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.094,2611	LR: 0.000205	Loss: 0.010	Acc: 100.0000	 Speed: 1953.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.121,2612	LR: 0.000205	Loss: 0.011	Acc: 100.0000	 Speed: 1849.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.148,2613	LR: 0.000204	Loss: 0.011	Acc: 100.0000	 Speed: 1440.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.174,2614	LR: 0.000204	Loss: 0.021	Acc: 100.0000	 Speed: 1677.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.201,2615	LR: 0.000204	Loss: 0.012	Acc: 100.0000	 Speed: 1226.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.228,2616	LR: 0.000203	Loss: 0.011	Acc: 100.0000	 Speed: 1956.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.255,2617	LR: 0.000203	Loss: 0.007	Acc: 100.0000	 Speed: 2382.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.282,2618	LR: 0.000203	Loss: 0.009	Acc: 100.0000	 Speed: 1774.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.309,2619	LR: 0.000202	Loss: 0.006	Acc: 100.0000	 Speed: 1807.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.336,2620	LR: 0.000202	Loss: 0.014	Acc: 100.0000	 Speed: 1755.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.362,2621	LR: 0.000202	Loss: 0.016	Acc: 100.0000	 Speed: 2073.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.389,2622	LR: 0.000201	Loss: 0.007	Acc: 100.0000	 Speed: 361.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3642.8118 samples/s	Time: 0.02s
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.416,2623	LR: 0.000201	Loss: 0.009	Acc: 100.0000	 Speed: 54.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.443,2624	LR: 0.000201	Loss: 0.006	Acc: 100.0000	 Speed: 1919.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.470,2625	LR: 0.000200	Loss: 0.019	Acc: 100.0000	 Speed: 1461.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.497,2626	LR: 0.000200	Loss: 0.007	Acc: 100.0000	 Speed: 1243.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.523,2627	LR: 0.000199	Loss: 0.005	Acc: 100.0000	 Speed: 1840.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.550,2628	LR: 0.000199	Loss: 0.008	Acc: 100.0000	 Speed: 2073.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.577,2629	LR: 0.000199	Loss: 0.012	Acc: 100.0000	 Speed: 1692.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.604,2630	LR: 0.000198	Loss: 0.009	Acc: 100.0000	 Speed: 2234.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.631,2631	LR: 0.000198	Loss: 0.011	Acc: 100.0000	 Speed: 1874.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.658,2632	LR: 0.000198	Loss: 0.011	Acc: 100.0000	 Speed: 1908.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.685,2633	LR: 0.000197	Loss: 0.012	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.711,2634	LR: 0.000197	Loss: 0.010	Acc: 100.0000	 Speed: 1638.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.738,2635	LR: 0.000197	Loss: 0.005	Acc: 100.0000	 Speed: 1865.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.765,2636	LR: 0.000196	Loss: 0.017	Acc: 100.0000	 Speed: 2064.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.792,2637	LR: 0.000196	Loss: 0.012	Acc: 100.0000	 Speed: 2012.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.819,2638	LR: 0.000196	Loss: 0.009	Acc: 100.0000	 Speed: 1865.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.846,2639	LR: 0.000195	Loss: 0.007	Acc: 100.0000	 Speed: 2092.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.872,2640	LR: 0.000195	Loss: 0.018	Acc: 100.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:28 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.899,2641	LR: 0.000195	Loss: 0.012	Acc: 100.0000	 Speed: 2159.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.926,2642	LR: 0.000194	Loss: 0.012	Acc: 100.0000	 Speed: 1852.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.953,2643	LR: 0.000194	Loss: 0.008	Acc: 100.0000	 Speed: 1811.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 70.980,2644	LR: 0.000194	Loss: 0.012	Acc: 100.0000	 Speed: 1521.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.007,2645	LR: 0.000193	Loss: 0.011	Acc: 100.0000	 Speed: 1666.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.034,2646	LR: 0.000193	Loss: 0.017	Acc: 100.0000	 Speed: 1873.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.060,2647	LR: 0.000193	Loss: 0.012	Acc: 100.0000	 Speed: 1650.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.087,2648	LR: 0.000192	Loss: 0.014	Acc: 100.0000	 Speed: 2012.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.114,2649	LR: 0.000192	Loss: 0.009	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.141,2650	LR: 0.000192	Loss: 0.015	Acc: 100.0000	 Speed: 1635.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.168,2651	LR: 0.000191	Loss: 0.007	Acc: 100.0000	 Speed: 1837.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.195,2652	LR: 0.000191	Loss: 0.009	Acc: 100.0000	 Speed: 1776.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.221,2653	LR: 0.000191	Loss: 0.007	Acc: 100.0000	 Speed: 1492.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.248,2654	LR: 0.000190	Loss: 0.016	Acc: 100.0000	 Speed: 2289.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.275,2655	LR: 0.000190	Loss: 0.010	Acc: 100.0000	 Speed: 1141.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.302,2656	LR: 0.000190	Loss: 0.009	Acc: 100.0000	 Speed: 1640.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.329,2657	LR: 0.000189	Loss: 0.014	Acc: 100.0000	 Speed: 2153.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.356,2658	LR: 0.000189	Loss: 0.007	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.383,2659	LR: 0.000189	Loss: 0.013	Acc: 100.0000	 Speed: 2190.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.409,2660	LR: 0.000188	Loss: 0.006	Acc: 100.0000	 Speed: 526.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3587.5271 samples/s	Time: 0.02s
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.436,2661	LR: 0.000188	Loss: 0.013	Acc: 100.0000	 Speed: 52.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.463,2662	LR: 0.000188	Loss: 0.007	Acc: 100.0000	 Speed: 1719.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.490,2663	LR: 0.000188	Loss: 0.008	Acc: 100.0000	 Speed: 1822.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.517,2664	LR: 0.000187	Loss: 0.008	Acc: 100.0000	 Speed: 2174.62 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.544,2665	LR: 0.000187	Loss: 0.012	Acc: 100.0000	 Speed: 1674.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.570,2666	LR: 0.000187	Loss: 0.007	Acc: 100.0000	 Speed: 1512.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.597,2667	LR: 0.000186	Loss: 0.009	Acc: 100.0000	 Speed: 2397.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.624,2668	LR: 0.000186	Loss: 0.007	Acc: 100.0000	 Speed: 1832.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.651,2669	LR: 0.000186	Loss: 0.014	Acc: 100.0000	 Speed: 2225.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.678,2670	LR: 0.000185	Loss: 0.011	Acc: 100.0000	 Speed: 1724.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.705,2671	LR: 0.000185	Loss: 0.013	Acc: 100.0000	 Speed: 1524.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.732,2672	LR: 0.000185	Loss: 0.009	Acc: 100.0000	 Speed: 1369.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.758,2673	LR: 0.000184	Loss: 0.011	Acc: 100.0000	 Speed: 1720.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.785,2674	LR: 0.000184	Loss: 0.007	Acc: 100.0000	 Speed: 1508.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.812,2675	LR: 0.000184	Loss: 0.020	Acc: 100.0000	 Speed: 1728.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.839,2676	LR: 0.000183	Loss: 0.011	Acc: 100.0000	 Speed: 2005.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.866,2677	LR: 0.000183	Loss: 0.017	Acc: 100.0000	 Speed: 1867.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.893,2678	LR: 0.000183	Loss: 0.017	Acc: 100.0000	 Speed: 1442.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.919,2679	LR: 0.000182	Loss: 0.008	Acc: 100.0000	 Speed: 1606.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.946,2680	LR: 0.000182	Loss: 0.012	Acc: 100.0000	 Speed: 1608.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 71.973,2681	LR: 0.000182	Loss: 0.008	Acc: 100.0000	 Speed: 1595.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.000,2682	LR: 0.000181	Loss: 0.013	Acc: 100.0000	 Speed: 2162.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.027,2683	LR: 0.000181	Loss: 0.002	Acc: 100.0000	 Speed: 1608.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.054,2684	LR: 0.000181	Loss: 0.005	Acc: 100.0000	 Speed: 1865.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.081,2685	LR: 0.000180	Loss: 0.012	Acc: 100.0000	 Speed: 2661.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.107,2686	LR: 0.000180	Loss: 0.015	Acc: 100.0000	 Speed: 1798.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.134,2687	LR: 0.000180	Loss: 0.013	Acc: 100.0000	 Speed: 1610.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.161,2688	LR: 0.000179	Loss: 0.010	Acc: 100.0000	 Speed: 1853.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.188,2689	LR: 0.000179	Loss: 0.007	Acc: 100.0000	 Speed: 1992.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.215,2690	LR: 0.000179	Loss: 0.011	Acc: 100.0000	 Speed: 1373.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.242,2691	LR: 0.000178	Loss: 0.006	Acc: 100.0000	 Speed: 1792.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.268,2692	LR: 0.000178	Loss: 0.009	Acc: 100.0000	 Speed: 1636.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.295,2693	LR: 0.000178	Loss: 0.004	Acc: 100.0000	 Speed: 2163.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.322,2694	LR: 0.000177	Loss: 0.010	Acc: 100.0000	 Speed: 1728.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.349,2695	LR: 0.000177	Loss: 0.016	Acc: 100.0000	 Speed: 1861.86 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.376,2696	LR: 0.000177	Loss: 0.021	Acc: 100.0000	 Speed: 2069.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.403,2697	LR: 0.000176	Loss: 0.016	Acc: 100.0000	 Speed: 2101.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.430,2698	LR: 0.000176	Loss: 0.002	Acc: 100.0000	 Speed: 456.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3653.2309 samples/s	Time: 0.02s
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.456,2699	LR: 0.000176	Loss: 0.010	Acc: 100.0000	 Speed: 52.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.483,2700	LR: 0.000175	Loss: 0.015	Acc: 100.0000	 Speed: 2153.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.510,2701	LR: 0.000175	Loss: 0.009	Acc: 100.0000	 Speed: 2266.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.537,2702	LR: 0.000175	Loss: 0.005	Acc: 100.0000	 Speed: 2149.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.564,2703	LR: 0.000175	Loss: 0.014	Acc: 100.0000	 Speed: 2282.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.591,2704	LR: 0.000174	Loss: 0.011	Acc: 100.0000	 Speed: 1342.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.617,2705	LR: 0.000174	Loss: 0.012	Acc: 100.0000	 Speed: 1786.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.644,2706	LR: 0.000174	Loss: 0.014	Acc: 100.0000	 Speed: 1934.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.671,2707	LR: 0.000173	Loss: 0.022	Acc: 100.0000	 Speed: 2531.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.698,2708	LR: 0.000173	Loss: 0.012	Acc: 100.0000	 Speed: 2141.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.725,2709	LR: 0.000173	Loss: 0.024	Acc: 100.0000	 Speed: 1811.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.752,2710	LR: 0.000172	Loss: 0.004	Acc: 100.0000	 Speed: 1723.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.779,2711	LR: 0.000172	Loss: 0.008	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.805,2712	LR: 0.000172	Loss: 0.007	Acc: 100.0000	 Speed: 2047.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.832,2713	LR: 0.000171	Loss: 0.004	Acc: 100.0000	 Speed: 1469.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.859,2714	LR: 0.000171	Loss: 0.010	Acc: 100.0000	 Speed: 1567.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.886,2715	LR: 0.000171	Loss: 0.005	Acc: 100.0000	 Speed: 2077.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.913,2716	LR: 0.000170	Loss: 0.010	Acc: 100.0000	 Speed: 1545.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.940,2717	LR: 0.000170	Loss: 0.018	Acc: 100.0000	 Speed: 1353.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.966,2718	LR: 0.000170	Loss: 0.006	Acc: 100.0000	 Speed: 1484.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 72.993,2719	LR: 0.000169	Loss: 0.009	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.020,2720	LR: 0.000169	Loss: 0.010	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.047,2721	LR: 0.000169	Loss: 0.015	Acc: 100.0000	 Speed: 1642.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.074,2722	LR: 0.000168	Loss: 0.005	Acc: 100.0000	 Speed: 1866.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.101,2723	LR: 0.000168	Loss: 0.011	Acc: 100.0000	 Speed: 2919.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.128,2724	LR: 0.000168	Loss: 0.014	Acc: 100.0000	 Speed: 1651.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.154,2725	LR: 0.000168	Loss: 0.009	Acc: 100.0000	 Speed: 1417.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.181,2726	LR: 0.000167	Loss: 0.009	Acc: 100.0000	 Speed: 1504.21 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.208,2727	LR: 0.000167	Loss: 0.007	Acc: 100.0000	 Speed: 1341.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.235,2728	LR: 0.000167	Loss: 0.007	Acc: 100.0000	 Speed: 2054.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.262,2729	LR: 0.000166	Loss: 0.015	Acc: 100.0000	 Speed: 2247.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.289,2730	LR: 0.000166	Loss: 0.008	Acc: 100.0000	 Speed: 1869.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.315,2731	LR: 0.000166	Loss: 0.011	Acc: 100.0000	 Speed: 2233.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.342,2732	LR: 0.000165	Loss: 0.011	Acc: 100.0000	 Speed: 2066.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.369,2733	LR: 0.000165	Loss: 0.008	Acc: 100.0000	 Speed: 1413.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.396,2734	LR: 0.000165	Loss: 0.011	Acc: 100.0000	 Speed: 1391.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.423,2735	LR: 0.000164	Loss: 0.009	Acc: 100.0000	 Speed: 1661.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.450,2736	LR: 0.000164	Loss: 0.007	Acc: 100.0000	 Speed: 375.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3509.5206 samples/s	Time: 0.02s
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.477,2737	LR: 0.000164	Loss: 0.006	Acc: 100.0000	 Speed: 50.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.503,2738	LR: 0.000163	Loss: 0.011	Acc: 100.0000	 Speed: 2664.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.530,2739	LR: 0.000163	Loss: 0.009	Acc: 100.0000	 Speed: 1539.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.557,2740	LR: 0.000163	Loss: 0.007	Acc: 100.0000	 Speed: 1428.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.584,2741	LR: 0.000163	Loss: 0.010	Acc: 100.0000	 Speed: 1950.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.611,2742	LR: 0.000162	Loss: 0.008	Acc: 100.0000	 Speed: 1491.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.638,2743	LR: 0.000162	Loss: 0.016	Acc: 100.0000	 Speed: 1312.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.664,2744	LR: 0.000162	Loss: 0.014	Acc: 100.0000	 Speed: 1572.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.691,2745	LR: 0.000161	Loss: 0.010	Acc: 100.0000	 Speed: 1964.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:29 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.718,2746	LR: 0.000161	Loss: 0.010	Acc: 100.0000	 Speed: 1644.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.745,2747	LR: 0.000161	Loss: 0.012	Acc: 100.0000	 Speed: 2193.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.772,2748	LR: 0.000160	Loss: 0.006	Acc: 100.0000	 Speed: 1677.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.799,2749	LR: 0.000160	Loss: 0.008	Acc: 100.0000	 Speed: 1421.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.826,2750	LR: 0.000160	Loss: 0.013	Acc: 100.0000	 Speed: 1719.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.852,2751	LR: 0.000159	Loss: 0.017	Acc: 100.0000	 Speed: 1426.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.879,2752	LR: 0.000159	Loss: 0.016	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.906,2753	LR: 0.000159	Loss: 0.017	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.933,2754	LR: 0.000158	Loss: 0.005	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.960,2755	LR: 0.000158	Loss: 0.017	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 73.987,2756	LR: 0.000158	Loss: 0.010	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.013,2757	LR: 0.000158	Loss: 0.012	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.040,2758	LR: 0.000157	Loss: 0.007	Acc: 100.0000	 Speed: 1832.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.067,2759	LR: 0.000157	Loss: 0.013	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.094,2760	LR: 0.000157	Loss: 0.006	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.121,2761	LR: 0.000156	Loss: 0.009	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.148,2762	LR: 0.000156	Loss: 0.006	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.174,2763	LR: 0.000156	Loss: 0.016	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.201,2764	LR: 0.000155	Loss: 0.008	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.228,2765	LR: 0.000155	Loss: 0.011	Acc: 100.0000	 Speed: 1259.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.255,2766	LR: 0.000155	Loss: 0.014	Acc: 100.0000	 Speed: 2663.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.282,2767	LR: 0.000155	Loss: 0.013	Acc: 100.0000	 Speed: 1248.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.309,2768	LR: 0.000154	Loss: 0.009	Acc: 100.0000	 Speed: 1273.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.336,2769	LR: 0.000154	Loss: 0.005	Acc: 100.0000	 Speed: 1316.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.362,2770	LR: 0.000154	Loss: 0.008	Acc: 100.0000	 Speed: 1575.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.389,2771	LR: 0.000153	Loss: 0.008	Acc: 100.0000	 Speed: 1517.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.416,2772	LR: 0.000153	Loss: 0.007	Acc: 100.0000	 Speed: 1981.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.443,2773	LR: 0.000153	Loss: 0.013	Acc: 100.0000	 Speed: 2128.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.470,2774	LR: 0.000152	Loss: 0.008	Acc: 100.0000	 Speed: 521.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3339.3062 samples/s	Time: 0.02s
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.497,2775	LR: 0.000152	Loss: 0.011	Acc: 100.0000	 Speed: 51.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.523,2776	LR: 0.000152	Loss: 0.009	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.550,2777	LR: 0.000151	Loss: 0.015	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.577,2778	LR: 0.000151	Loss: 0.011	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.604,2779	LR: 0.000151	Loss: 0.010	Acc: 100.0000	 Speed: 2230.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.631,2780	LR: 0.000151	Loss: 0.004	Acc: 100.0000	 Speed: 1826.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.658,2781	LR: 0.000150	Loss: 0.006	Acc: 100.0000	 Speed: 1277.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.685,2782	LR: 0.000150	Loss: 0.006	Acc: 100.0000	 Speed: 1227.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.711,2783	LR: 0.000150	Loss: 0.010	Acc: 100.0000	 Speed: 2666.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.738,2784	LR: 0.000149	Loss: 0.019	Acc: 100.0000	 Speed: 2007.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.765,2785	LR: 0.000149	Loss: 0.008	Acc: 100.0000	 Speed: 1944.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.792,2786	LR: 0.000149	Loss: 0.016	Acc: 100.0000	 Speed: 2238.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.819,2787	LR: 0.000148	Loss: 0.009	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.846,2788	LR: 0.000148	Loss: 0.009	Acc: 100.0000	 Speed: 1706.82 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.872,2789	LR: 0.000148	Loss: 0.010	Acc: 100.0000	 Speed: 2053.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.899,2790	LR: 0.000148	Loss: 0.009	Acc: 100.0000	 Speed: 1866.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.926,2791	LR: 0.000147	Loss: 0.009	Acc: 100.0000	 Speed: 1550.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.953,2792	LR: 0.000147	Loss: 0.008	Acc: 100.0000	 Speed: 2381.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 74.980,2793	LR: 0.000147	Loss: 0.013	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.007,2794	LR: 0.000146	Loss: 0.007	Acc: 100.0000	 Speed: 1908.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.034,2795	LR: 0.000146	Loss: 0.004	Acc: 100.0000	 Speed: 2239.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.060,2796	LR: 0.000146	Loss: 0.012	Acc: 100.0000	 Speed: 1642.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.087,2797	LR: 0.000145	Loss: 0.008	Acc: 100.0000	 Speed: 1931.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.114,2798	LR: 0.000145	Loss: 0.009	Acc: 100.0000	 Speed: 1848.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.141,2799	LR: 0.000145	Loss: 0.021	Acc: 100.0000	 Speed: 1865.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.168,2800	LR: 0.000145	Loss: 0.009	Acc: 100.0000	 Speed: 1700.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.195,2801	LR: 0.000144	Loss: 0.009	Acc: 100.0000	 Speed: 1132.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.221,2802	LR: 0.000144	Loss: 0.016	Acc: 100.0000	 Speed: 1333.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.248,2803	LR: 0.000144	Loss: 0.005	Acc: 100.0000	 Speed: 1230.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.275,2804	LR: 0.000143	Loss: 0.014	Acc: 100.0000	 Speed: 1314.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.302,2805	LR: 0.000143	Loss: 0.004	Acc: 100.0000	 Speed: 1782.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.329,2806	LR: 0.000143	Loss: 0.011	Acc: 100.0000	 Speed: 1421.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.356,2807	LR: 0.000143	Loss: 0.010	Acc: 100.0000	 Speed: 1762.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.383,2808	LR: 0.000142	Loss: 0.010	Acc: 100.0000	 Speed: 1535.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.409,2809	LR: 0.000142	Loss: 0.008	Acc: 100.0000	 Speed: 1611.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.436,2810	LR: 0.000142	Loss: 0.013	Acc: 100.0000	 Speed: 1313.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.463,2811	LR: 0.000141	Loss: 0.015	Acc: 100.0000	 Speed: 1598.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.490,2812	LR: 0.000141	Loss: 0.027	Acc: 100.0000	 Speed: 687.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3461.3415 samples/s	Time: 0.02s
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.517,2813	LR: 0.000141	Loss: 0.010	Acc: 100.0000	 Speed: 52.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.544,2814	LR: 0.000140	Loss: 0.005	Acc: 100.0000	 Speed: 2313.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.570,2815	LR: 0.000140	Loss: 0.014	Acc: 100.0000	 Speed: 1869.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.597,2816	LR: 0.000140	Loss: 0.007	Acc: 100.0000	 Speed: 2186.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.624,2817	LR: 0.000140	Loss: 0.007	Acc: 100.0000	 Speed: 1807.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.651,2818	LR: 0.000139	Loss: 0.008	Acc: 100.0000	 Speed: 1724.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.678,2819	LR: 0.000139	Loss: 0.014	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.705,2820	LR: 0.000139	Loss: 0.007	Acc: 100.0000	 Speed: 1834.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.732,2821	LR: 0.000138	Loss: 0.013	Acc: 100.0000	 Speed: 1267.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.758,2822	LR: 0.000138	Loss: 0.008	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.785,2823	LR: 0.000138	Loss: 0.007	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.812,2824	LR: 0.000138	Loss: 0.017	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.839,2825	LR: 0.000137	Loss: 0.014	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.866,2826	LR: 0.000137	Loss: 0.006	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.893,2827	LR: 0.000137	Loss: 0.014	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.919,2828	LR: 0.000136	Loss: 0.008	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.946,2829	LR: 0.000136	Loss: 0.019	Acc: 100.0000	 Speed: 1838.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 75.973,2830	LR: 0.000136	Loss: 0.011	Acc: 100.0000	 Speed: 1753.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.000,2831	LR: 0.000136	Loss: 0.010	Acc: 100.0000	 Speed: 2142.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.027,2832	LR: 0.000135	Loss: 0.007	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.054,2833	LR: 0.000135	Loss: 0.019	Acc: 100.0000	 Speed: 2011.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.081,2834	LR: 0.000135	Loss: 0.007	Acc: 100.0000	 Speed: 1933.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.107,2835	LR: 0.000134	Loss: 0.012	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.134,2836	LR: 0.000134	Loss: 0.007	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.161,2837	LR: 0.000134	Loss: 0.014	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.188,2838	LR: 0.000134	Loss: 0.005	Acc: 100.0000	 Speed: 2298.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.215,2839	LR: 0.000133	Loss: 0.009	Acc: 100.0000	 Speed: 1998.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.242,2840	LR: 0.000133	Loss: 0.008	Acc: 100.0000	 Speed: 2002.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.268,2841	LR: 0.000133	Loss: 0.005	Acc: 100.0000	 Speed: 2202.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.295,2842	LR: 0.000132	Loss: 0.007	Acc: 100.0000	 Speed: 2280.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.322,2843	LR: 0.000132	Loss: 0.008	Acc: 100.0000	 Speed: 1528.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.349,2844	LR: 0.000132	Loss: 0.009	Acc: 100.0000	 Speed: 2219.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.376,2845	LR: 0.000131	Loss: 0.014	Acc: 100.0000	 Speed: 2060.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.403,2846	LR: 0.000131	Loss: 0.015	Acc: 100.0000	 Speed: 1928.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.430,2847	LR: 0.000131	Loss: 0.009	Acc: 100.0000	 Speed: 1908.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.456,2848	LR: 0.000131	Loss: 0.012	Acc: 100.0000	 Speed: 1547.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.483,2849	LR: 0.000130	Loss: 0.009	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.510,2850	LR: 0.000130	Loss: 0.011	Acc: 100.0000	 Speed: 527.12 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3691.9494 samples/s	Time: 0.02s
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.537,2851	LR: 0.000130	Loss: 0.011	Acc: 100.0000	 Speed: 52.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.564,2852	LR: 0.000130	Loss: 0.010	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.591,2853	LR: 0.000129	Loss: 0.012	Acc: 100.0000	 Speed: 2141.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.617,2854	LR: 0.000129	Loss: 0.008	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:30 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.644,2855	LR: 0.000129	Loss: 0.007	Acc: 100.0000	 Speed: 1523.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.671,2856	LR: 0.000128	Loss: 0.012	Acc: 100.0000	 Speed: 1688.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.698,2857	LR: 0.000128	Loss: 0.010	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.725,2858	LR: 0.000128	Loss: 0.010	Acc: 100.0000	 Speed: 1252.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.752,2859	LR: 0.000128	Loss: 0.008	Acc: 100.0000	 Speed: 2119.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.779,2860	LR: 0.000127	Loss: 0.008	Acc: 100.0000	 Speed: 1231.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.805,2861	LR: 0.000127	Loss: 0.022	Acc: 100.0000	 Speed: 1667.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.832,2862	LR: 0.000127	Loss: 0.005	Acc: 100.0000	 Speed: 1773.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.859,2863	LR: 0.000126	Loss: 0.007	Acc: 100.0000	 Speed: 1684.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.886,2864	LR: 0.000126	Loss: 0.016	Acc: 100.0000	 Speed: 2500.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.913,2865	LR: 0.000126	Loss: 0.012	Acc: 100.0000	 Speed: 1649.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.940,2866	LR: 0.000126	Loss: 0.008	Acc: 100.0000	 Speed: 1917.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.966,2867	LR: 0.000125	Loss: 0.013	Acc: 100.0000	 Speed: 970.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 76.993,2868	LR: 0.000125	Loss: 0.008	Acc: 100.0000	 Speed: 2031.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.020,2869	LR: 0.000125	Loss: 0.012	Acc: 100.0000	 Speed: 1581.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.047,2870	LR: 0.000124	Loss: 0.010	Acc: 100.0000	 Speed: 1572.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.074,2871	LR: 0.000124	Loss: 0.006	Acc: 100.0000	 Speed: 1467.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.101,2872	LR: 0.000124	Loss: 0.010	Acc: 100.0000	 Speed: 1315.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.128,2873	LR: 0.000124	Loss: 0.009	Acc: 100.0000	 Speed: 1831.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.154,2874	LR: 0.000123	Loss: 0.007	Acc: 100.0000	 Speed: 2033.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.181,2875	LR: 0.000123	Loss: 0.013	Acc: 100.0000	 Speed: 1888.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.208,2876	LR: 0.000123	Loss: 0.008	Acc: 100.0000	 Speed: 2680.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.235,2877	LR: 0.000123	Loss: 0.008	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.262,2878	LR: 0.000122	Loss: 0.010	Acc: 100.0000	 Speed: 1613.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.289,2879	LR: 0.000122	Loss: 0.012	Acc: 100.0000	 Speed: 1514.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.315,2880	LR: 0.000122	Loss: 0.007	Acc: 100.0000	 Speed: 1956.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.342,2881	LR: 0.000121	Loss: 0.010	Acc: 100.0000	 Speed: 1961.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.369,2882	LR: 0.000121	Loss: 0.013	Acc: 100.0000	 Speed: 2136.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.396,2883	LR: 0.000121	Loss: 0.007	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.423,2884	LR: 0.000121	Loss: 0.013	Acc: 100.0000	 Speed: 1473.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.450,2885	LR: 0.000120	Loss: 0.008	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.477,2886	LR: 0.000120	Loss: 0.010	Acc: 100.0000	 Speed: 1999.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.503,2887	LR: 0.000120	Loss: 0.016	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.530,2888	LR: 0.000119	Loss: 0.003	Acc: 100.0000	 Speed: 404.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3472.5721 samples/s	Time: 0.02s
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.557,2889	LR: 0.000119	Loss: 0.011	Acc: 100.0000	 Speed: 52.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.584,2890	LR: 0.000119	Loss: 0.008	Acc: 100.0000	 Speed: 1866.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.611,2891	LR: 0.000119	Loss: 0.010	Acc: 100.0000	 Speed: 2663.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.638,2892	LR: 0.000118	Loss: 0.016	Acc: 100.0000	 Speed: 2026.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.664,2893	LR: 0.000118	Loss: 0.010	Acc: 100.0000	 Speed: 1821.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.691,2894	LR: 0.000118	Loss: 0.005	Acc: 100.0000	 Speed: 2108.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.718,2895	LR: 0.000118	Loss: 0.005	Acc: 100.0000	 Speed: 1929.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.745,2896	LR: 0.000117	Loss: 0.012	Acc: 100.0000	 Speed: 1567.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.772,2897	LR: 0.000117	Loss: 0.007	Acc: 100.0000	 Speed: 1514.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.799,2898	LR: 0.000117	Loss: 0.015	Acc: 100.0000	 Speed: 2138.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.826,2899	LR: 0.000116	Loss: 0.011	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.852,2900	LR: 0.000116	Loss: 0.006	Acc: 100.0000	 Speed: 1946.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.879,2901	LR: 0.000116	Loss: 0.016	Acc: 100.0000	 Speed: 2066.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.906,2902	LR: 0.000116	Loss: 0.012	Acc: 100.0000	 Speed: 1832.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.933,2903	LR: 0.000115	Loss: 0.012	Acc: 100.0000	 Speed: 1625.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.960,2904	LR: 0.000115	Loss: 0.010	Acc: 100.0000	 Speed: 1971.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 77.987,2905	LR: 0.000115	Loss: 0.006	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.013,2906	LR: 0.000115	Loss: 0.008	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.040,2907	LR: 0.000114	Loss: 0.011	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.067,2908	LR: 0.000114	Loss: 0.005	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.094,2909	LR: 0.000114	Loss: 0.010	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.121,2910	LR: 0.000114	Loss: 0.006	Acc: 100.0000	 Speed: 1999.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.148,2911	LR: 0.000113	Loss: 0.010	Acc: 100.0000	 Speed: 2172.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.174,2912	LR: 0.000113	Loss: 0.011	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.201,2913	LR: 0.000113	Loss: 0.012	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.228,2914	LR: 0.000112	Loss: 0.014	Acc: 100.0000	 Speed: 1193.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.255,2915	LR: 0.000112	Loss: 0.004	Acc: 100.0000	 Speed: 2279.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.282,2916	LR: 0.000112	Loss: 0.008	Acc: 100.0000	 Speed: 1142.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.309,2917	LR: 0.000112	Loss: 0.014	Acc: 100.0000	 Speed: 1774.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.336,2918	LR: 0.000111	Loss: 0.010	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.362,2919	LR: 0.000111	Loss: 0.007	Acc: 100.0000	 Speed: 2093.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.389,2920	LR: 0.000111	Loss: 0.006	Acc: 100.0000	 Speed: 1582.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.416,2921	LR: 0.000111	Loss: 0.019	Acc: 100.0000	 Speed: 1868.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.443,2922	LR: 0.000110	Loss: 0.010	Acc: 100.0000	 Speed: 1226.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.470,2923	LR: 0.000110	Loss: 0.016	Acc: 100.0000	 Speed: 1769.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.497,2924	LR: 0.000110	Loss: 0.005	Acc: 100.0000	 Speed: 1992.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.523,2925	LR: 0.000110	Loss: 0.007	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.550,2926	LR: 0.000109	Loss: 0.014	Acc: 100.0000	 Speed: 666.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3681.1340 samples/s	Time: 0.02s
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.577,2927	LR: 0.000109	Loss: 0.010	Acc: 100.0000	 Speed: 53.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.604,2928	LR: 0.000109	Loss: 0.012	Acc: 100.0000	 Speed: 1869.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.631,2929	LR: 0.000109	Loss: 0.008	Acc: 100.0000	 Speed: 1291.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.658,2930	LR: 0.000108	Loss: 0.018	Acc: 100.0000	 Speed: 2218.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.685,2931	LR: 0.000108	Loss: 0.015	Acc: 100.0000	 Speed: 1806.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.711,2932	LR: 0.000108	Loss: 0.008	Acc: 100.0000	 Speed: 2393.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.738,2933	LR: 0.000107	Loss: 0.006	Acc: 100.0000	 Speed: 2296.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.765,2934	LR: 0.000107	Loss: 0.005	Acc: 100.0000	 Speed: 1897.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.792,2935	LR: 0.000107	Loss: 0.006	Acc: 100.0000	 Speed: 1439.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.819,2936	LR: 0.000107	Loss: 0.005	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.846,2937	LR: 0.000106	Loss: 0.009	Acc: 100.0000	 Speed: 963.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.872,2938	LR: 0.000106	Loss: 0.007	Acc: 100.0000	 Speed: 1446.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.899,2939	LR: 0.000106	Loss: 0.007	Acc: 100.0000	 Speed: 1334.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.926,2940	LR: 0.000106	Loss: 0.015	Acc: 100.0000	 Speed: 1602.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.953,2941	LR: 0.000105	Loss: 0.012	Acc: 100.0000	 Speed: 1825.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 78.980,2942	LR: 0.000105	Loss: 0.014	Acc: 100.0000	 Speed: 1827.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.007,2943	LR: 0.000105	Loss: 0.004	Acc: 100.0000	 Speed: 2134.78 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.034,2944	LR: 0.000105	Loss: 0.010	Acc: 100.0000	 Speed: 1985.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.060,2945	LR: 0.000104	Loss: 0.010	Acc: 100.0000	 Speed: 1383.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.087,2946	LR: 0.000104	Loss: 0.011	Acc: 100.0000	 Speed: 1716.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.114,2947	LR: 0.000104	Loss: 0.007	Acc: 100.0000	 Speed: 2042.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.141,2948	LR: 0.000104	Loss: 0.007	Acc: 100.0000	 Speed: 1789.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.168,2949	LR: 0.000103	Loss: 0.007	Acc: 100.0000	 Speed: 2156.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.195,2950	LR: 0.000103	Loss: 0.017	Acc: 100.0000	 Speed: 1419.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.221,2951	LR: 0.000103	Loss: 0.008	Acc: 100.0000	 Speed: 1841.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.248,2952	LR: 0.000103	Loss: 0.008	Acc: 100.0000	 Speed: 1747.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.275,2953	LR: 0.000102	Loss: 0.010	Acc: 100.0000	 Speed: 1575.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.302,2954	LR: 0.000102	Loss: 0.008	Acc: 100.0000	 Speed: 1677.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.329,2955	LR: 0.000102	Loss: 0.015	Acc: 100.0000	 Speed: 1840.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.356,2956	LR: 0.000102	Loss: 0.020	Acc: 100.0000	 Speed: 1728.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.383,2957	LR: 0.000101	Loss: 0.005	Acc: 100.0000	 Speed: 2015.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.409,2958	LR: 0.000101	Loss: 0.009	Acc: 100.0000	 Speed: 1713.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.436,2959	LR: 0.000101	Loss: 0.010	Acc: 100.0000	 Speed: 1820.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.463,2960	LR: 0.000101	Loss: 0.008	Acc: 100.0000	 Speed: 1559.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.490,2961	LR: 0.000100	Loss: 0.009	Acc: 100.0000	 Speed: 2039.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.517,2962	LR: 0.000100	Loss: 0.009	Acc: 100.0000	 Speed: 2166.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.544,2963	LR: 0.000100	Loss: 0.011	Acc: 100.0000	 Speed: 1997.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.570,2964	LR: 0.000099	Loss: 0.019	Acc: 100.0000	 Speed: 691.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:31 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3516.7977 samples/s	Time: 0.02s
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.597,2965	LR: 0.000099	Loss: 0.016	Acc: 100.0000	 Speed: 51.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.624,2966	LR: 0.000099	Loss: 0.009	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.651,2967	LR: 0.000099	Loss: 0.010	Acc: 100.0000	 Speed: 1507.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.678,2968	LR: 0.000098	Loss: 0.007	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.705,2969	LR: 0.000098	Loss: 0.004	Acc: 100.0000	 Speed: 2001.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.732,2970	LR: 0.000098	Loss: 0.015	Acc: 100.0000	 Speed: 1566.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.758,2971	LR: 0.000098	Loss: 0.012	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.785,2972	LR: 0.000097	Loss: 0.011	Acc: 100.0000	 Speed: 2164.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.812,2973	LR: 0.000097	Loss: 0.014	Acc: 100.0000	 Speed: 1680.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.839,2974	LR: 0.000097	Loss: 0.008	Acc: 100.0000	 Speed: 2074.46 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.866,2975	LR: 0.000097	Loss: 0.019	Acc: 100.0000	 Speed: 2259.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.893,2976	LR: 0.000096	Loss: 0.004	Acc: 100.0000	 Speed: 1932.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.919,2977	LR: 0.000096	Loss: 0.005	Acc: 100.0000	 Speed: 1776.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.946,2978	LR: 0.000096	Loss: 0.006	Acc: 100.0000	 Speed: 2666.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 79.973,2979	LR: 0.000096	Loss: 0.008	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.000,2980	LR: 0.000095	Loss: 0.009	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.027,2981	LR: 0.000095	Loss: 0.009	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.054,2982	LR: 0.000095	Loss: 0.009	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.081,2983	LR: 0.000095	Loss: 0.010	Acc: 100.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.107,2984	LR: 0.000095	Loss: 0.014	Acc: 100.0000	 Speed: 1075.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.134,2985	LR: 0.000094	Loss: 0.017	Acc: 100.0000	 Speed: 1461.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.161,2986	LR: 0.000094	Loss: 0.005	Acc: 100.0000	 Speed: 1954.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.188,2987	LR: 0.000094	Loss: 0.009	Acc: 100.0000	 Speed: 2001.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.215,2988	LR: 0.000094	Loss: 0.007	Acc: 100.0000	 Speed: 1713.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.242,2989	LR: 0.000093	Loss: 0.011	Acc: 100.0000	 Speed: 1598.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.268,2990	LR: 0.000093	Loss: 0.004	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.295,2991	LR: 0.000093	Loss: 0.007	Acc: 100.0000	 Speed: 1187.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.322,2992	LR: 0.000093	Loss: 0.008	Acc: 100.0000	 Speed: 1518.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.349,2993	LR: 0.000092	Loss: 0.010	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.376,2994	LR: 0.000092	Loss: 0.008	Acc: 100.0000	 Speed: 1523.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.403,2995	LR: 0.000092	Loss: 0.007	Acc: 100.0000	 Speed: 2679.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.430,2996	LR: 0.000092	Loss: 0.018	Acc: 100.0000	 Speed: 1851.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.456,2997	LR: 0.000091	Loss: 0.016	Acc: 100.0000	 Speed: 1387.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.483,2998	LR: 0.000091	Loss: 0.008	Acc: 100.0000	 Speed: 1533.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.510,2999	LR: 0.000091	Loss: 0.010	Acc: 100.0000	 Speed: 1395.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.537,3000	LR: 0.000091	Loss: 0.011	Acc: 100.0000	 Speed: 2164.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.564,3001	LR: 0.000090	Loss: 0.007	Acc: 100.0000	 Speed: 950.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.591,3002	LR: 0.000090	Loss: 0.010	Acc: 100.0000	 Speed: 443.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3797.6544 samples/s	Time: 0.02s
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.617,3003	LR: 0.000090	Loss: 0.019	Acc: 100.0000	 Speed: 51.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.644,3004	LR: 0.000090	Loss: 0.015	Acc: 100.0000	 Speed: 2281.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.671,3005	LR: 0.000089	Loss: 0.011	Acc: 100.0000	 Speed: 1746.26 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.698,3006	LR: 0.000089	Loss: 0.010	Acc: 100.0000	 Speed: 1388.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.725,3007	LR: 0.000089	Loss: 0.012	Acc: 100.0000	 Speed: 1693.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.752,3008	LR: 0.000089	Loss: 0.009	Acc: 100.0000	 Speed: 1718.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.779,3009	LR: 0.000088	Loss: 0.010	Acc: 100.0000	 Speed: 1274.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.805,3010	LR: 0.000088	Loss: 0.010	Acc: 100.0000	 Speed: 2077.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.832,3011	LR: 0.000088	Loss: 0.008	Acc: 100.0000	 Speed: 2062.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.859,3012	LR: 0.000088	Loss: 0.007	Acc: 100.0000	 Speed: 2221.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.886,3013	LR: 0.000087	Loss: 0.011	Acc: 100.0000	 Speed: 1379.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.913,3014	LR: 0.000087	Loss: 0.008	Acc: 100.0000	 Speed: 2281.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.940,3015	LR: 0.000087	Loss: 0.013	Acc: 100.0000	 Speed: 2367.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.966,3016	LR: 0.000087	Loss: 0.006	Acc: 100.0000	 Speed: 1736.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 80.993,3017	LR: 0.000087	Loss: 0.004	Acc: 100.0000	 Speed: 1886.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.020,3018	LR: 0.000086	Loss: 0.009	Acc: 100.0000	 Speed: 1781.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.047,3019	LR: 0.000086	Loss: 0.010	Acc: 100.0000	 Speed: 2232.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.074,3020	LR: 0.000086	Loss: 0.012	Acc: 100.0000	 Speed: 2316.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.101,3021	LR: 0.000086	Loss: 0.006	Acc: 100.0000	 Speed: 1567.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.128,3022	LR: 0.000085	Loss: 0.006	Acc: 100.0000	 Speed: 1181.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.154,3023	LR: 0.000085	Loss: 0.006	Acc: 100.0000	 Speed: 2094.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.181,3024	LR: 0.000085	Loss: 0.005	Acc: 100.0000	 Speed: 1828.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.208,3025	LR: 0.000085	Loss: 0.014	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.235,3026	LR: 0.000084	Loss: 0.012	Acc: 100.0000	 Speed: 1955.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.262,3027	LR: 0.000084	Loss: 0.010	Acc: 100.0000	 Speed: 1195.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.289,3028	LR: 0.000084	Loss: 0.009	Acc: 100.0000	 Speed: 1478.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.315,3029	LR: 0.000084	Loss: 0.004	Acc: 100.0000	 Speed: 1512.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.342,3030	LR: 0.000083	Loss: 0.006	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.369,3031	LR: 0.000083	Loss: 0.009	Acc: 100.0000	 Speed: 2156.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.396,3032	LR: 0.000083	Loss: 0.011	Acc: 100.0000	 Speed: 1881.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.423,3033	LR: 0.000083	Loss: 0.007	Acc: 100.0000	 Speed: 2011.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.450,3034	LR: 0.000083	Loss: 0.009	Acc: 100.0000	 Speed: 1962.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.477,3035	LR: 0.000082	Loss: 0.006	Acc: 100.0000	 Speed: 2086.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.503,3036	LR: 0.000082	Loss: 0.016	Acc: 100.0000	 Speed: 2289.00 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.530,3037	LR: 0.000082	Loss: 0.009	Acc: 100.0000	 Speed: 1745.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.557,3038	LR: 0.000082	Loss: 0.015	Acc: 100.0000	 Speed: 1828.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.584,3039	LR: 0.000081	Loss: 0.012	Acc: 100.0000	 Speed: 1561.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.611,3040	LR: 0.000081	Loss: 0.018	Acc: 100.0000	 Speed: 437.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3219.3266 samples/s	Time: 0.02s
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.638,3041	LR: 0.000081	Loss: 0.013	Acc: 100.0000	 Speed: 52.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.664,3042	LR: 0.000081	Loss: 0.011	Acc: 100.0000	 Speed: 1960.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.691,3043	LR: 0.000080	Loss: 0.011	Acc: 100.0000	 Speed: 2436.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.718,3044	LR: 0.000080	Loss: 0.011	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.745,3045	LR: 0.000080	Loss: 0.005	Acc: 100.0000	 Speed: 1961.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.772,3046	LR: 0.000080	Loss: 0.010	Acc: 100.0000	 Speed: 1774.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.799,3047	LR: 0.000080	Loss: 0.004	Acc: 100.0000	 Speed: 1563.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.826,3048	LR: 0.000079	Loss: 0.009	Acc: 100.0000	 Speed: 1850.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.852,3049	LR: 0.000079	Loss: 0.005	Acc: 100.0000	 Speed: 1823.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.879,3050	LR: 0.000079	Loss: 0.019	Acc: 100.0000	 Speed: 1716.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.906,3051	LR: 0.000079	Loss: 0.009	Acc: 100.0000	 Speed: 2664.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.933,3052	LR: 0.000078	Loss: 0.010	Acc: 100.0000	 Speed: 2133.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.960,3053	LR: 0.000078	Loss: 0.009	Acc: 100.0000	 Speed: 1813.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 81.987,3054	LR: 0.000078	Loss: 0.012	Acc: 100.0000	 Speed: 2580.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.013,3055	LR: 0.000078	Loss: 0.017	Acc: 100.0000	 Speed: 1816.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.040,3056	LR: 0.000077	Loss: 0.009	Acc: 100.0000	 Speed: 1667.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.067,3057	LR: 0.000077	Loss: 0.010	Acc: 100.0000	 Speed: 2665.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.094,3058	LR: 0.000077	Loss: 0.008	Acc: 100.0000	 Speed: 2100.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.121,3059	LR: 0.000077	Loss: 0.008	Acc: 100.0000	 Speed: 1661.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.148,3060	LR: 0.000077	Loss: 0.004	Acc: 100.0000	 Speed: 1878.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.174,3061	LR: 0.000076	Loss: 0.010	Acc: 100.0000	 Speed: 2176.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.201,3062	LR: 0.000076	Loss: 0.010	Acc: 100.0000	 Speed: 1786.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.228,3063	LR: 0.000076	Loss: 0.004	Acc: 100.0000	 Speed: 2099.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.255,3064	LR: 0.000076	Loss: 0.003	Acc: 100.0000	 Speed: 1675.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.282,3065	LR: 0.000075	Loss: 0.007	Acc: 100.0000	 Speed: 1235.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.309,3066	LR: 0.000075	Loss: 0.014	Acc: 100.0000	 Speed: 1660.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.336,3067	LR: 0.000075	Loss: 0.009	Acc: 100.0000	 Speed: 1629.88 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.362,3068	LR: 0.000075	Loss: 0.015	Acc: 100.0000	 Speed: 2035.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.389,3069	LR: 0.000075	Loss: 0.006	Acc: 100.0000	 Speed: 2128.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.416,3070	LR: 0.000074	Loss: 0.005	Acc: 100.0000	 Speed: 1348.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.443,3071	LR: 0.000074	Loss: 0.012	Acc: 100.0000	 Speed: 1384.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.470,3072	LR: 0.000074	Loss: 0.018	Acc: 100.0000	 Speed: 1395.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.497,3073	LR: 0.000074	Loss: 0.007	Acc: 100.0000	 Speed: 1452.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.523,3074	LR: 0.000073	Loss: 0.017	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.550,3075	LR: 0.000073	Loss: 0.008	Acc: 100.0000	 Speed: 1618.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.577,3076	LR: 0.000073	Loss: 0.008	Acc: 100.0000	 Speed: 1770.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.604,3077	LR: 0.000073	Loss: 0.010	Acc: 100.0000	 Speed: 1807.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.631,3078	LR: 0.000073	Loss: 0.011	Acc: 100.0000	 Speed: 666.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:32 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3801.9341 samples/s	Time: 0.02s
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.658,3079	LR: 0.000072	Loss: 0.007	Acc: 100.0000	 Speed: 52.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.685,3080	LR: 0.000072	Loss: 0.010	Acc: 100.0000	 Speed: 1095.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.711,3081	LR: 0.000072	Loss: 0.006	Acc: 100.0000	 Speed: 2459.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.738,3082	LR: 0.000072	Loss: 0.005	Acc: 100.0000	 Speed: 1674.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.765,3083	LR: 0.000072	Loss: 0.010	Acc: 100.0000	 Speed: 2333.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.792,3084	LR: 0.000071	Loss: 0.012	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.819,3085	LR: 0.000071	Loss: 0.009	Acc: 100.0000	 Speed: 1561.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.846,3086	LR: 0.000071	Loss: 0.002	Acc: 100.0000	 Speed: 1682.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.872,3087	LR: 0.000071	Loss: 0.009	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.899,3088	LR: 0.000070	Loss: 0.007	Acc: 100.0000	 Speed: 2282.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.926,3089	LR: 0.000070	Loss: 0.013	Acc: 100.0000	 Speed: 2506.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.953,3090	LR: 0.000070	Loss: 0.015	Acc: 100.0000	 Speed: 2001.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 82.980,3091	LR: 0.000070	Loss: 0.004	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.007,3092	LR: 0.000070	Loss: 0.007	Acc: 100.0000	 Speed: 1902.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.034,3093	LR: 0.000069	Loss: 0.010	Acc: 100.0000	 Speed: 1855.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.060,3094	LR: 0.000069	Loss: 0.012	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.087,3095	LR: 0.000069	Loss: 0.015	Acc: 100.0000	 Speed: 2035.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.114,3096	LR: 0.000069	Loss: 0.012	Acc: 100.0000	 Speed: 1619.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.141,3097	LR: 0.000069	Loss: 0.004	Acc: 100.0000	 Speed: 1945.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.168,3098	LR: 0.000068	Loss: 0.010	Acc: 100.0000	 Speed: 2114.06 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.195,3099	LR: 0.000068	Loss: 0.008	Acc: 100.0000	 Speed: 2188.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.221,3100	LR: 0.000068	Loss: 0.011	Acc: 100.0000	 Speed: 2680.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.248,3101	LR: 0.000068	Loss: 0.010	Acc: 100.0000	 Speed: 1854.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.275,3102	LR: 0.000067	Loss: 0.006	Acc: 100.0000	 Speed: 1537.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.302,3103	LR: 0.000067	Loss: 0.007	Acc: 100.0000	 Speed: 2195.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.329,3104	LR: 0.000067	Loss: 0.015	Acc: 100.0000	 Speed: 2099.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.356,3105	LR: 0.000067	Loss: 0.009	Acc: 100.0000	 Speed: 1175.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.383,3106	LR: 0.000067	Loss: 0.013	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.409,3107	LR: 0.000066	Loss: 0.009	Acc: 100.0000	 Speed: 2026.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.436,3108	LR: 0.000066	Loss: 0.008	Acc: 100.0000	 Speed: 2302.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.463,3109	LR: 0.000066	Loss: 0.009	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.490,3110	LR: 0.000066	Loss: 0.012	Acc: 100.0000	 Speed: 1920.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.517,3111	LR: 0.000066	Loss: 0.014	Acc: 100.0000	 Speed: 2377.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.544,3112	LR: 0.000065	Loss: 0.011	Acc: 100.0000	 Speed: 1723.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.570,3113	LR: 0.000065	Loss: 0.008	Acc: 100.0000	 Speed: 1780.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.597,3114	LR: 0.000065	Loss: 0.017	Acc: 100.0000	 Speed: 2529.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.624,3115	LR: 0.000065	Loss: 0.009	Acc: 100.0000	 Speed: 2061.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.651,3116	LR: 0.000065	Loss: 0.009	Acc: 100.0000	 Speed: 519.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3597.5485 samples/s	Time: 0.02s
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.678,3117	LR: 0.000064	Loss: 0.012	Acc: 100.0000	 Speed: 51.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.705,3118	LR: 0.000064	Loss: 0.017	Acc: 100.0000	 Speed: 2670.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.732,3119	LR: 0.000064	Loss: 0.022	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.758,3120	LR: 0.000064	Loss: 0.007	Acc: 100.0000	 Speed: 2057.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.785,3121	LR: 0.000063	Loss: 0.006	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.812,3122	LR: 0.000063	Loss: 0.007	Acc: 100.0000	 Speed: 2036.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.839,3123	LR: 0.000063	Loss: 0.010	Acc: 100.0000	 Speed: 2341.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.866,3124	LR: 0.000063	Loss: 0.012	Acc: 100.0000	 Speed: 1671.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.893,3125	LR: 0.000063	Loss: 0.013	Acc: 100.0000	 Speed: 1925.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.919,3126	LR: 0.000062	Loss: 0.007	Acc: 100.0000	 Speed: 2183.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.946,3127	LR: 0.000062	Loss: 0.011	Acc: 100.0000	 Speed: 2442.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 83.973,3128	LR: 0.000062	Loss: 0.011	Acc: 100.0000	 Speed: 1975.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.000,3129	LR: 0.000062	Loss: 0.006	Acc: 100.0000	 Speed: 1914.55 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.027,3130	LR: 0.000062	Loss: 0.007	Acc: 100.0000	 Speed: 1452.70 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.054,3131	LR: 0.000061	Loss: 0.005	Acc: 100.0000	 Speed: 1852.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.081,3132	LR: 0.000061	Loss: 0.009	Acc: 100.0000	 Speed: 2013.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.107,3133	LR: 0.000061	Loss: 0.011	Acc: 100.0000	 Speed: 1764.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.134,3134	LR: 0.000061	Loss: 0.015	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.161,3135	LR: 0.000061	Loss: 0.008	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.188,3136	LR: 0.000060	Loss: 0.009	Acc: 100.0000	 Speed: 2310.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.215,3137	LR: 0.000060	Loss: 0.008	Acc: 100.0000	 Speed: 2222.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.242,3138	LR: 0.000060	Loss: 0.005	Acc: 100.0000	 Speed: 2001.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.268,3139	LR: 0.000060	Loss: 0.011	Acc: 100.0000	 Speed: 1946.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.295,3140	LR: 0.000060	Loss: 0.013	Acc: 100.0000	 Speed: 1811.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.322,3141	LR: 0.000059	Loss: 0.012	Acc: 100.0000	 Speed: 2091.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.349,3142	LR: 0.000059	Loss: 0.005	Acc: 100.0000	 Speed: 1801.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.376,3143	LR: 0.000059	Loss: 0.009	Acc: 100.0000	 Speed: 1791.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.403,3144	LR: 0.000059	Loss: 0.005	Acc: 100.0000	 Speed: 1950.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.430,3145	LR: 0.000059	Loss: 0.008	Acc: 100.0000	 Speed: 1925.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.456,3146	LR: 0.000058	Loss: 0.007	Acc: 100.0000	 Speed: 1584.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.483,3147	LR: 0.000058	Loss: 0.009	Acc: 100.0000	 Speed: 2408.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.510,3148	LR: 0.000058	Loss: 0.010	Acc: 100.0000	 Speed: 2512.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.537,3149	LR: 0.000058	Loss: 0.014	Acc: 100.0000	 Speed: 988.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.564,3150	LR: 0.000058	Loss: 0.007	Acc: 100.0000	 Speed: 1436.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.591,3151	LR: 0.000057	Loss: 0.008	Acc: 100.0000	 Speed: 1459.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.617,3152	LR: 0.000057	Loss: 0.006	Acc: 100.0000	 Speed: 1215.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.644,3153	LR: 0.000057	Loss: 0.012	Acc: 100.0000	 Speed: 2052.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.671,3154	LR: 0.000057	Loss: 0.010	Acc: 100.0000	 Speed: 542.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3364.1719 samples/s	Time: 0.02s
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.698,3155	LR: 0.000057	Loss: 0.007	Acc: 100.0000	 Speed: 53.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.725,3156	LR: 0.000056	Loss: 0.013	Acc: 100.0000	 Speed: 1150.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.752,3157	LR: 0.000056	Loss: 0.008	Acc: 100.0000	 Speed: 2054.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.779,3158	LR: 0.000056	Loss: 0.004	Acc: 100.0000	 Speed: 2499.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.805,3159	LR: 0.000056	Loss: 0.013	Acc: 100.0000	 Speed: 1534.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.832,3160	LR: 0.000056	Loss: 0.012	Acc: 100.0000	 Speed: 1793.11 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.859,3161	LR: 0.000056	Loss: 0.009	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.886,3162	LR: 0.000055	Loss: 0.013	Acc: 100.0000	 Speed: 2021.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.913,3163	LR: 0.000055	Loss: 0.012	Acc: 100.0000	 Speed: 1873.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.940,3164	LR: 0.000055	Loss: 0.007	Acc: 100.0000	 Speed: 1815.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.966,3165	LR: 0.000055	Loss: 0.013	Acc: 100.0000	 Speed: 1496.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 84.993,3166	LR: 0.000055	Loss: 0.012	Acc: 100.0000	 Speed: 1851.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.020,3167	LR: 0.000054	Loss: 0.010	Acc: 100.0000	 Speed: 1879.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.047,3168	LR: 0.000054	Loss: 0.012	Acc: 100.0000	 Speed: 2085.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.074,3169	LR: 0.000054	Loss: 0.009	Acc: 100.0000	 Speed: 2065.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.101,3170	LR: 0.000054	Loss: 0.010	Acc: 100.0000	 Speed: 2175.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.128,3171	LR: 0.000054	Loss: 0.007	Acc: 100.0000	 Speed: 2227.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.154,3172	LR: 0.000053	Loss: 0.005	Acc: 100.0000	 Speed: 2278.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.181,3173	LR: 0.000053	Loss: 0.013	Acc: 100.0000	 Speed: 1863.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.208,3174	LR: 0.000053	Loss: 0.006	Acc: 100.0000	 Speed: 1909.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.235,3175	LR: 0.000053	Loss: 0.012	Acc: 100.0000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.262,3176	LR: 0.000053	Loss: 0.009	Acc: 100.0000	 Speed: 1957.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.289,3177	LR: 0.000052	Loss: 0.005	Acc: 100.0000	 Speed: 1598.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.315,3178	LR: 0.000052	Loss: 0.006	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.342,3179	LR: 0.000052	Loss: 0.014	Acc: 100.0000	 Speed: 1901.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.369,3180	LR: 0.000052	Loss: 0.010	Acc: 100.0000	 Speed: 2002.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.396,3181	LR: 0.000052	Loss: 0.012	Acc: 100.0000	 Speed: 1968.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.423,3182	LR: 0.000052	Loss: 0.010	Acc: 100.0000	 Speed: 2025.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.450,3183	LR: 0.000051	Loss: 0.009	Acc: 100.0000	 Speed: 1648.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.477,3184	LR: 0.000051	Loss: 0.006	Acc: 100.0000	 Speed: 1717.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.503,3185	LR: 0.000051	Loss: 0.007	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.530,3186	LR: 0.000051	Loss: 0.009	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.557,3187	LR: 0.000051	Loss: 0.009	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.584,3188	LR: 0.000050	Loss: 0.016	Acc: 100.0000	 Speed: 2667.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.611,3189	LR: 0.000050	Loss: 0.008	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.638,3190	LR: 0.000050	Loss: 0.006	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.664,3191	LR: 0.000050	Loss: 0.009	Acc: 100.0000	 Speed: 1806.53 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.691,3192	LR: 0.000050	Loss: 0.008	Acc: 100.0000	 Speed: 477.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:33 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3713.0612 samples/s	Time: 0.02s
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.718,3193	LR: 0.000049	Loss: 0.008	Acc: 100.0000	 Speed: 51.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.745,3194	LR: 0.000049	Loss: 0.011	Acc: 100.0000	 Speed: 2374.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.772,3195	LR: 0.000049	Loss: 0.007	Acc: 100.0000	 Speed: 1486.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.799,3196	LR: 0.000049	Loss: 0.008	Acc: 100.0000	 Speed: 2134.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.826,3197	LR: 0.000049	Loss: 0.009	Acc: 100.0000	 Speed: 1191.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.852,3198	LR: 0.000049	Loss: 0.011	Acc: 100.0000	 Speed: 2297.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.879,3199	LR: 0.000048	Loss: 0.012	Acc: 100.0000	 Speed: 2110.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.906,3200	LR: 0.000048	Loss: 0.009	Acc: 100.0000	 Speed: 2176.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.933,3201	LR: 0.000048	Loss: 0.008	Acc: 100.0000	 Speed: 1748.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.960,3202	LR: 0.000048	Loss: 0.010	Acc: 100.0000	 Speed: 2394.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 85.987,3203	LR: 0.000048	Loss: 0.010	Acc: 100.0000	 Speed: 2025.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.013,3204	LR: 0.000047	Loss: 0.009	Acc: 100.0000	 Speed: 1755.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.040,3205	LR: 0.000047	Loss: 0.007	Acc: 100.0000	 Speed: 1898.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.067,3206	LR: 0.000047	Loss: 0.008	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.094,3207	LR: 0.000047	Loss: 0.008	Acc: 100.0000	 Speed: 1831.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.121,3208	LR: 0.000047	Loss: 0.006	Acc: 100.0000	 Speed: 2013.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.148,3209	LR: 0.000047	Loss: 0.011	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.174,3210	LR: 0.000046	Loss: 0.005	Acc: 100.0000	 Speed: 1706.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.201,3211	LR: 0.000046	Loss: 0.012	Acc: 100.0000	 Speed: 2641.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.228,3212	LR: 0.000046	Loss: 0.012	Acc: 100.0000	 Speed: 2164.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.255,3213	LR: 0.000046	Loss: 0.014	Acc: 100.0000	 Speed: 1913.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.282,3214	LR: 0.000046	Loss: 0.013	Acc: 100.0000	 Speed: 1942.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.309,3215	LR: 0.000046	Loss: 0.010	Acc: 100.0000	 Speed: 1930.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.336,3216	LR: 0.000045	Loss: 0.007	Acc: 100.0000	 Speed: 1541.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.362,3217	LR: 0.000045	Loss: 0.016	Acc: 100.0000	 Speed: 2375.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.389,3218	LR: 0.000045	Loss: 0.013	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.416,3219	LR: 0.000045	Loss: 0.006	Acc: 100.0000	 Speed: 1345.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.443,3220	LR: 0.000045	Loss: 0.008	Acc: 100.0000	 Speed: 1502.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.470,3221	LR: 0.000044	Loss: 0.011	Acc: 100.0000	 Speed: 1393.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.497,3222	LR: 0.000044	Loss: 0.012	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.523,3223	LR: 0.000044	Loss: 0.011	Acc: 100.0000	 Speed: 1348.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.550,3224	LR: 0.000044	Loss: 0.007	Acc: 100.0000	 Speed: 1217.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.577,3225	LR: 0.000044	Loss: 0.009	Acc: 100.0000	 Speed: 1374.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.604,3226	LR: 0.000044	Loss: 0.013	Acc: 100.0000	 Speed: 1476.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.631,3227	LR: 0.000043	Loss: 0.005	Acc: 100.0000	 Speed: 1907.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.658,3228	LR: 0.000043	Loss: 0.004	Acc: 100.0000	 Speed: 1850.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.685,3229	LR: 0.000043	Loss: 0.010	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.711,3230	LR: 0.000043	Loss: 0.007	Acc: 100.0000	 Speed: 412.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3586.9052 samples/s	Time: 0.02s
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.738,3231	LR: 0.000043	Loss: 0.005	Acc: 100.0000	 Speed: 52.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.765,3232	LR: 0.000043	Loss: 0.008	Acc: 100.0000	 Speed: 2279.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.792,3233	LR: 0.000042	Loss: 0.009	Acc: 100.0000	 Speed: 1600.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.819,3234	LR: 0.000042	Loss: 0.013	Acc: 100.0000	 Speed: 1333.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.846,3235	LR: 0.000042	Loss: 0.006	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.872,3236	LR: 0.000042	Loss: 0.010	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.899,3237	LR: 0.000042	Loss: 0.007	Acc: 100.0000	 Speed: 1942.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.926,3238	LR: 0.000042	Loss: 0.013	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.953,3239	LR: 0.000041	Loss: 0.007	Acc: 100.0000	 Speed: 2207.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 86.980,3240	LR: 0.000041	Loss: 0.006	Acc: 100.0000	 Speed: 1996.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.007,3241	LR: 0.000041	Loss: 0.007	Acc: 100.0000	 Speed: 2259.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.034,3242	LR: 0.000041	Loss: 0.016	Acc: 100.0000	 Speed: 2282.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.060,3243	LR: 0.000041	Loss: 0.012	Acc: 100.0000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.087,3244	LR: 0.000041	Loss: 0.008	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.114,3245	LR: 0.000040	Loss: 0.010	Acc: 100.0000	 Speed: 2264.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.141,3246	LR: 0.000040	Loss: 0.019	Acc: 100.0000	 Speed: 2192.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.168,3247	LR: 0.000040	Loss: 0.009	Acc: 100.0000	 Speed: 1856.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.195,3248	LR: 0.000040	Loss: 0.004	Acc: 100.0000	 Speed: 2285.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.221,3249	LR: 0.000040	Loss: 0.007	Acc: 100.0000	 Speed: 1888.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.248,3250	LR: 0.000040	Loss: 0.008	Acc: 100.0000	 Speed: 1984.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.275,3251	LR: 0.000039	Loss: 0.008	Acc: 100.0000	 Speed: 1469.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.302,3252	LR: 0.000039	Loss: 0.016	Acc: 100.0000	 Speed: 1786.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.329,3253	LR: 0.000039	Loss: 0.010	Acc: 100.0000	 Speed: 1924.99 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.356,3254	LR: 0.000039	Loss: 0.010	Acc: 100.0000	 Speed: 1917.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.383,3255	LR: 0.000039	Loss: 0.004	Acc: 100.0000	 Speed: 1900.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.409,3256	LR: 0.000039	Loss: 0.008	Acc: 100.0000	 Speed: 1598.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.436,3257	LR: 0.000038	Loss: 0.012	Acc: 100.0000	 Speed: 1596.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.463,3258	LR: 0.000038	Loss: 0.017	Acc: 100.0000	 Speed: 1519.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.490,3259	LR: 0.000038	Loss: 0.006	Acc: 100.0000	 Speed: 2145.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.517,3260	LR: 0.000038	Loss: 0.015	Acc: 100.0000	 Speed: 2077.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.544,3261	LR: 0.000038	Loss: 0.009	Acc: 100.0000	 Speed: 1964.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.570,3262	LR: 0.000038	Loss: 0.006	Acc: 100.0000	 Speed: 2434.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.597,3263	LR: 0.000037	Loss: 0.011	Acc: 100.0000	 Speed: 2010.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.624,3264	LR: 0.000037	Loss: 0.010	Acc: 100.0000	 Speed: 1907.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.651,3265	LR: 0.000037	Loss: 0.008	Acc: 100.0000	 Speed: 1757.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.678,3266	LR: 0.000037	Loss: 0.006	Acc: 100.0000	 Speed: 1599.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.705,3267	LR: 0.000037	Loss: 0.012	Acc: 100.0000	 Speed: 1695.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.732,3268	LR: 0.000037	Loss: 0.003	Acc: 100.0000	 Speed: 629.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3522.3053 samples/s	Time: 0.02s
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.758,3269	LR: 0.000037	Loss: 0.010	Acc: 100.0000	 Speed: 52.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.785,3270	LR: 0.000036	Loss: 0.006	Acc: 100.0000	 Speed: 2142.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.812,3271	LR: 0.000036	Loss: 0.008	Acc: 100.0000	 Speed: 2030.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.839,3272	LR: 0.000036	Loss: 0.015	Acc: 100.0000	 Speed: 1859.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.866,3273	LR: 0.000036	Loss: 0.012	Acc: 100.0000	 Speed: 1858.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.893,3274	LR: 0.000036	Loss: 0.006	Acc: 100.0000	 Speed: 1867.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.919,3275	LR: 0.000036	Loss: 0.010	Acc: 100.0000	 Speed: 2278.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.946,3276	LR: 0.000035	Loss: 0.014	Acc: 100.0000	 Speed: 1965.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 87.973,3277	LR: 0.000035	Loss: 0.006	Acc: 100.0000	 Speed: 1718.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.000,3278	LR: 0.000035	Loss: 0.015	Acc: 100.0000	 Speed: 1536.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.027,3279	LR: 0.000035	Loss: 0.012	Acc: 100.0000	 Speed: 1527.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.054,3280	LR: 0.000035	Loss: 0.008	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.081,3281	LR: 0.000035	Loss: 0.008	Acc: 100.0000	 Speed: 1215.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.107,3282	LR: 0.000034	Loss: 0.004	Acc: 100.0000	 Speed: 1630.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.134,3283	LR: 0.000034	Loss: 0.019	Acc: 100.0000	 Speed: 1883.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.161,3284	LR: 0.000034	Loss: 0.014	Acc: 100.0000	 Speed: 1562.92 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.188,3285	LR: 0.000034	Loss: 0.004	Acc: 100.0000	 Speed: 1998.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.215,3286	LR: 0.000034	Loss: 0.005	Acc: 100.0000	 Speed: 1648.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.242,3287	LR: 0.000034	Loss: 0.010	Acc: 100.0000	 Speed: 1774.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.268,3288	LR: 0.000034	Loss: 0.007	Acc: 100.0000	 Speed: 1863.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.295,3289	LR: 0.000033	Loss: 0.011	Acc: 100.0000	 Speed: 2328.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.322,3290	LR: 0.000033	Loss: 0.009	Acc: 100.0000	 Speed: 1578.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.349,3291	LR: 0.000033	Loss: 0.006	Acc: 100.0000	 Speed: 1507.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.376,3292	LR: 0.000033	Loss: 0.008	Acc: 100.0000	 Speed: 2168.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.403,3293	LR: 0.000033	Loss: 0.005	Acc: 100.0000	 Speed: 2052.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.430,3294	LR: 0.000033	Loss: 0.013	Acc: 100.0000	 Speed: 1786.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.456,3295	LR: 0.000033	Loss: 0.011	Acc: 100.0000	 Speed: 1460.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.483,3296	LR: 0.000032	Loss: 0.006	Acc: 100.0000	 Speed: 1816.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.510,3297	LR: 0.000032	Loss: 0.012	Acc: 100.0000	 Speed: 2324.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.537,3298	LR: 0.000032	Loss: 0.011	Acc: 100.0000	 Speed: 1774.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.564,3299	LR: 0.000032	Loss: 0.006	Acc: 100.0000	 Speed: 2282.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.591,3300	LR: 0.000032	Loss: 0.008	Acc: 100.0000	 Speed: 2281.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.617,3301	LR: 0.000032	Loss: 0.015	Acc: 100.0000	 Speed: 1775.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.644,3302	LR: 0.000031	Loss: 0.011	Acc: 100.0000	 Speed: 1659.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.671,3303	LR: 0.000031	Loss: 0.004	Acc: 100.0000	 Speed: 1004.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.698,3304	LR: 0.000031	Loss: 0.013	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.725,3305	LR: 0.000031	Loss: 0.006	Acc: 100.0000	 Speed: 1329.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.752,3306	LR: 0.000031	Loss: 0.013	Acc: 100.0000	 Speed: 551.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:34 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3469.0402 samples/s	Time: 0.02s
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.779,3307	LR: 0.000031	Loss: 0.008	Acc: 100.0000	 Speed: 52.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.805,3308	LR: 0.000031	Loss: 0.005	Acc: 100.0000	 Speed: 2139.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.832,3309	LR: 0.000030	Loss: 0.019	Acc: 100.0000	 Speed: 1558.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.859,3310	LR: 0.000030	Loss: 0.010	Acc: 100.0000	 Speed: 1692.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.886,3311	LR: 0.000030	Loss: 0.009	Acc: 100.0000	 Speed: 2136.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.913,3312	LR: 0.000030	Loss: 0.012	Acc: 100.0000	 Speed: 1477.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.940,3313	LR: 0.000030	Loss: 0.011	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.966,3314	LR: 0.000030	Loss: 0.009	Acc: 100.0000	 Speed: 1797.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 88.993,3315	LR: 0.000030	Loss: 0.006	Acc: 100.0000	 Speed: 2358.84 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.020,3316	LR: 0.000029	Loss: 0.008	Acc: 100.0000	 Speed: 1981.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.047,3317	LR: 0.000029	Loss: 0.006	Acc: 100.0000	 Speed: 1998.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.074,3318	LR: 0.000029	Loss: 0.007	Acc: 100.0000	 Speed: 2105.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.101,3319	LR: 0.000029	Loss: 0.008	Acc: 100.0000	 Speed: 1829.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.128,3320	LR: 0.000029	Loss: 0.012	Acc: 100.0000	 Speed: 1286.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.154,3321	LR: 0.000029	Loss: 0.009	Acc: 100.0000	 Speed: 1576.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.181,3322	LR: 0.000029	Loss: 0.013	Acc: 100.0000	 Speed: 1757.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.208,3323	LR: 0.000028	Loss: 0.014	Acc: 100.0000	 Speed: 2157.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.235,3324	LR: 0.000028	Loss: 0.013	Acc: 100.0000	 Speed: 1776.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.262,3325	LR: 0.000028	Loss: 0.006	Acc: 100.0000	 Speed: 1691.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.289,3326	LR: 0.000028	Loss: 0.007	Acc: 100.0000	 Speed: 1923.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.315,3327	LR: 0.000028	Loss: 0.009	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.342,3328	LR: 0.000028	Loss: 0.007	Acc: 100.0000	 Speed: 1869.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.369,3329	LR: 0.000028	Loss: 0.006	Acc: 100.0000	 Speed: 2506.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.396,3330	LR: 0.000027	Loss: 0.006	Acc: 100.0000	 Speed: 2208.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.423,3331	LR: 0.000027	Loss: 0.015	Acc: 100.0000	 Speed: 2000.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.450,3332	LR: 0.000027	Loss: 0.006	Acc: 100.0000	 Speed: 2490.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.477,3333	LR: 0.000027	Loss: 0.013	Acc: 100.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.503,3334	LR: 0.000027	Loss: 0.008	Acc: 100.0000	 Speed: 1724.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.530,3335	LR: 0.000027	Loss: 0.013	Acc: 100.0000	 Speed: 2448.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.557,3336	LR: 0.000027	Loss: 0.009	Acc: 100.0000	 Speed: 1631.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.584,3337	LR: 0.000027	Loss: 0.010	Acc: 100.0000	 Speed: 1373.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.611,3338	LR: 0.000026	Loss: 0.012	Acc: 100.0000	 Speed: 2150.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.638,3339	LR: 0.000026	Loss: 0.012	Acc: 100.0000	 Speed: 1988.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.664,3340	LR: 0.000026	Loss: 0.009	Acc: 100.0000	 Speed: 1134.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.691,3341	LR: 0.000026	Loss: 0.009	Acc: 100.0000	 Speed: 1793.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.718,3342	LR: 0.000026	Loss: 0.006	Acc: 100.0000	 Speed: 1752.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.745,3343	LR: 0.000026	Loss: 0.006	Acc: 100.0000	 Speed: 1932.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.772,3344	LR: 0.000026	Loss: 0.006	Acc: 100.0000	 Speed: 654.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3302.1799 samples/s	Time: 0.02s
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.799,3345	LR: 0.000025	Loss: 0.008	Acc: 100.0000	 Speed: 52.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.826,3346	LR: 0.000025	Loss: 0.008	Acc: 100.0000	 Speed: 1777.91 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.852,3347	LR: 0.000025	Loss: 0.006	Acc: 100.0000	 Speed: 1424.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.879,3348	LR: 0.000025	Loss: 0.009	Acc: 100.0000	 Speed: 2705.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.906,3349	LR: 0.000025	Loss: 0.011	Acc: 100.0000	 Speed: 1574.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.933,3350	LR: 0.000025	Loss: 0.008	Acc: 100.0000	 Speed: 1774.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.960,3351	LR: 0.000025	Loss: 0.014	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 89.987,3352	LR: 0.000025	Loss: 0.006	Acc: 100.0000	 Speed: 2036.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.013,3353	LR: 0.000024	Loss: 0.008	Acc: 100.0000	 Speed: 1743.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.040,3354	LR: 0.000024	Loss: 0.011	Acc: 100.0000	 Speed: 2111.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.067,3355	LR: 0.000024	Loss: 0.010	Acc: 100.0000	 Speed: 2061.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.094,3356	LR: 0.000024	Loss: 0.009	Acc: 100.0000	 Speed: 1811.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.121,3357	LR: 0.000024	Loss: 0.007	Acc: 100.0000	 Speed: 1405.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.148,3358	LR: 0.000024	Loss: 0.008	Acc: 100.0000	 Speed: 1795.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.174,3359	LR: 0.000024	Loss: 0.015	Acc: 100.0000	 Speed: 1707.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.201,3360	LR: 0.000024	Loss: 0.007	Acc: 100.0000	 Speed: 2159.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.228,3361	LR: 0.000023	Loss: 0.008	Acc: 100.0000	 Speed: 1721.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.255,3362	LR: 0.000023	Loss: 0.011	Acc: 100.0000	 Speed: 1645.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.282,3363	LR: 0.000023	Loss: 0.010	Acc: 100.0000	 Speed: 2366.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.309,3364	LR: 0.000023	Loss: 0.009	Acc: 100.0000	 Speed: 1876.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.336,3365	LR: 0.000023	Loss: 0.007	Acc: 100.0000	 Speed: 1676.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.362,3366	LR: 0.000023	Loss: 0.004	Acc: 100.0000	 Speed: 1453.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.389,3367	LR: 0.000023	Loss: 0.010	Acc: 100.0000	 Speed: 2113.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.416,3368	LR: 0.000022	Loss: 0.014	Acc: 100.0000	 Speed: 1943.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.443,3369	LR: 0.000022	Loss: 0.010	Acc: 100.0000	 Speed: 2282.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.470,3370	LR: 0.000022	Loss: 0.011	Acc: 100.0000	 Speed: 1599.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.497,3371	LR: 0.000022	Loss: 0.011	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.523,3372	LR: 0.000022	Loss: 0.016	Acc: 100.0000	 Speed: 2279.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.550,3373	LR: 0.000022	Loss: 0.010	Acc: 100.0000	 Speed: 761.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.577,3374	LR: 0.000022	Loss: 0.012	Acc: 100.0000	 Speed: 1407.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.604,3375	LR: 0.000022	Loss: 0.007	Acc: 100.0000	 Speed: 1676.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.631,3376	LR: 0.000022	Loss: 0.014	Acc: 100.0000	 Speed: 1866.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.658,3377	LR: 0.000021	Loss: 0.009	Acc: 100.0000	 Speed: 1845.17 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.685,3378	LR: 0.000021	Loss: 0.009	Acc: 100.0000	 Speed: 2241.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.711,3379	LR: 0.000021	Loss: 0.003	Acc: 100.0000	 Speed: 2667.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.738,3380	LR: 0.000021	Loss: 0.007	Acc: 100.0000	 Speed: 1606.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.765,3381	LR: 0.000021	Loss: 0.012	Acc: 100.0000	 Speed: 1893.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.792,3382	LR: 0.000021	Loss: 0.002	Acc: 100.0000	 Speed: 647.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3661.4191 samples/s	Time: 0.02s
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.819,3383	LR: 0.000021	Loss: 0.007	Acc: 100.0000	 Speed: 53.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.846,3384	LR: 0.000021	Loss: 0.007	Acc: 100.0000	 Speed: 1903.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.872,3385	LR: 0.000020	Loss: 0.013	Acc: 100.0000	 Speed: 1925.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.899,3386	LR: 0.000020	Loss: 0.010	Acc: 100.0000	 Speed: 1970.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.926,3387	LR: 0.000020	Loss: 0.006	Acc: 100.0000	 Speed: 1687.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.953,3388	LR: 0.000020	Loss: 0.007	Acc: 100.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 90.980,3389	LR: 0.000020	Loss: 0.016	Acc: 100.0000	 Speed: 1737.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.007,3390	LR: 0.000020	Loss: 0.012	Acc: 100.0000	 Speed: 1948.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.034,3391	LR: 0.000020	Loss: 0.006	Acc: 100.0000	 Speed: 2458.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.060,3392	LR: 0.000020	Loss: 0.007	Acc: 100.0000	 Speed: 1514.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.087,3393	LR: 0.000019	Loss: 0.014	Acc: 100.0000	 Speed: 1522.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.114,3394	LR: 0.000019	Loss: 0.011	Acc: 100.0000	 Speed: 1818.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.141,3395	LR: 0.000019	Loss: 0.010	Acc: 100.0000	 Speed: 1900.99 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.168,3396	LR: 0.000019	Loss: 0.010	Acc: 100.0000	 Speed: 2384.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.195,3397	LR: 0.000019	Loss: 0.011	Acc: 100.0000	 Speed: 2145.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.221,3398	LR: 0.000019	Loss: 0.011	Acc: 100.0000	 Speed: 1919.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.248,3399	LR: 0.000019	Loss: 0.004	Acc: 100.0000	 Speed: 1948.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.275,3400	LR: 0.000019	Loss: 0.012	Acc: 100.0000	 Speed: 1932.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.302,3401	LR: 0.000019	Loss: 0.005	Acc: 100.0000	 Speed: 1598.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.329,3402	LR: 0.000018	Loss: 0.009	Acc: 100.0000	 Speed: 1403.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.356,3403	LR: 0.000018	Loss: 0.011	Acc: 100.0000	 Speed: 1590.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.383,3404	LR: 0.000018	Loss: 0.009	Acc: 100.0000	 Speed: 1413.18 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.409,3405	LR: 0.000018	Loss: 0.005	Acc: 100.0000	 Speed: 1917.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.436,3406	LR: 0.000018	Loss: 0.008	Acc: 100.0000	 Speed: 1664.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.463,3407	LR: 0.000018	Loss: 0.011	Acc: 100.0000	 Speed: 1740.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.490,3408	LR: 0.000018	Loss: 0.007	Acc: 100.0000	 Speed: 1357.76 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.517,3409	LR: 0.000018	Loss: 0.011	Acc: 100.0000	 Speed: 1803.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.544,3410	LR: 0.000018	Loss: 0.016	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.570,3411	LR: 0.000017	Loss: 0.010	Acc: 100.0000	 Speed: 1611.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.597,3412	LR: 0.000017	Loss: 0.012	Acc: 100.0000	 Speed: 2080.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.624,3413	LR: 0.000017	Loss: 0.007	Acc: 100.0000	 Speed: 2233.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.651,3414	LR: 0.000017	Loss: 0.008	Acc: 100.0000	 Speed: 1780.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.678,3415	LR: 0.000017	Loss: 0.015	Acc: 100.0000	 Speed: 2074.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.705,3416	LR: 0.000017	Loss: 0.005	Acc: 100.0000	 Speed: 1836.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.732,3417	LR: 0.000017	Loss: 0.005	Acc: 100.0000	 Speed: 1295.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.758,3418	LR: 0.000017	Loss: 0.005	Acc: 100.0000	 Speed: 1594.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.785,3419	LR: 0.000017	Loss: 0.011	Acc: 100.0000	 Speed: 2103.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:35 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.812,3420	LR: 0.000016	Loss: 0.016	Acc: 100.0000	 Speed: 666.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3538.0849 samples/s	Time: 0.02s
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.839,3421	LR: 0.000016	Loss: 0.007	Acc: 100.0000	 Speed: 51.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.866,3422	LR: 0.000016	Loss: 0.012	Acc: 100.0000	 Speed: 1536.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.893,3423	LR: 0.000016	Loss: 0.008	Acc: 100.0000	 Speed: 1317.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.919,3424	LR: 0.000016	Loss: 0.012	Acc: 100.0000	 Speed: 2193.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.946,3425	LR: 0.000016	Loss: 0.014	Acc: 100.0000	 Speed: 1852.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 91.973,3426	LR: 0.000016	Loss: 0.010	Acc: 100.0000	 Speed: 1563.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.000,3427	LR: 0.000016	Loss: 0.007	Acc: 100.0000	 Speed: 2211.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.027,3428	LR: 0.000016	Loss: 0.005	Acc: 100.0000	 Speed: 1729.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.054,3429	LR: 0.000015	Loss: 0.009	Acc: 100.0000	 Speed: 2048.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.081,3430	LR: 0.000015	Loss: 0.009	Acc: 100.0000	 Speed: 1732.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.107,3431	LR: 0.000015	Loss: 0.007	Acc: 100.0000	 Speed: 1523.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.134,3432	LR: 0.000015	Loss: 0.007	Acc: 100.0000	 Speed: 1582.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.161,3433	LR: 0.000015	Loss: 0.007	Acc: 100.0000	 Speed: 1537.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.188,3434	LR: 0.000015	Loss: 0.007	Acc: 100.0000	 Speed: 1850.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.215,3435	LR: 0.000015	Loss: 0.012	Acc: 100.0000	 Speed: 1841.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.242,3436	LR: 0.000015	Loss: 0.010	Acc: 100.0000	 Speed: 2146.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.268,3437	LR: 0.000015	Loss: 0.007	Acc: 100.0000	 Speed: 2296.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.295,3438	LR: 0.000015	Loss: 0.010	Acc: 100.0000	 Speed: 1785.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.322,3439	LR: 0.000014	Loss: 0.012	Acc: 100.0000	 Speed: 1905.09 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.349,3440	LR: 0.000014	Loss: 0.015	Acc: 100.0000	 Speed: 1675.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.376,3441	LR: 0.000014	Loss: 0.009	Acc: 100.0000	 Speed: 1711.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.403,3442	LR: 0.000014	Loss: 0.009	Acc: 100.0000	 Speed: 857.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.430,3443	LR: 0.000014	Loss: 0.011	Acc: 100.0000	 Speed: 1829.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.456,3444	LR: 0.000014	Loss: 0.010	Acc: 100.0000	 Speed: 1910.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.483,3445	LR: 0.000014	Loss: 0.015	Acc: 100.0000	 Speed: 2075.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.510,3446	LR: 0.000014	Loss: 0.010	Acc: 100.0000	 Speed: 1314.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.537,3447	LR: 0.000014	Loss: 0.006	Acc: 100.0000	 Speed: 1069.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.564,3448	LR: 0.000014	Loss: 0.007	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.591,3449	LR: 0.000013	Loss: 0.015	Acc: 100.0000	 Speed: 1793.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.617,3450	LR: 0.000013	Loss: 0.011	Acc: 100.0000	 Speed: 1856.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.644,3451	LR: 0.000013	Loss: 0.006	Acc: 100.0000	 Speed: 2273.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.671,3452	LR: 0.000013	Loss: 0.007	Acc: 100.0000	 Speed: 2313.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.698,3453	LR: 0.000013	Loss: 0.009	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.725,3454	LR: 0.000013	Loss: 0.011	Acc: 100.0000	 Speed: 1753.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.752,3455	LR: 0.000013	Loss: 0.006	Acc: 100.0000	 Speed: 1974.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.779,3456	LR: 0.000013	Loss: 0.013	Acc: 100.0000	 Speed: 1888.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.805,3457	LR: 0.000013	Loss: 0.006	Acc: 100.0000	 Speed: 1560.45 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.832,3458	LR: 0.000013	Loss: 0.005	Acc: 100.0000	 Speed: 730.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3448.1902 samples/s	Time: 0.02s
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.859,3459	LR: 0.000013	Loss: 0.007	Acc: 100.0000	 Speed: 53.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.886,3460	LR: 0.000012	Loss: 0.006	Acc: 100.0000	 Speed: 1791.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.913,3461	LR: 0.000012	Loss: 0.007	Acc: 100.0000	 Speed: 1831.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.940,3462	LR: 0.000012	Loss: 0.008	Acc: 100.0000	 Speed: 1598.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.966,3463	LR: 0.000012	Loss: 0.013	Acc: 100.0000	 Speed: 1798.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 92.993,3464	LR: 0.000012	Loss: 0.008	Acc: 100.0000	 Speed: 1881.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.020,3465	LR: 0.000012	Loss: 0.014	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.047,3466	LR: 0.000012	Loss: 0.012	Acc: 100.0000	 Speed: 2664.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.074,3467	LR: 0.000012	Loss: 0.007	Acc: 100.0000	 Speed: 2421.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.101,3468	LR: 0.000012	Loss: 0.008	Acc: 100.0000	 Speed: 1678.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.128,3469	LR: 0.000012	Loss: 0.008	Acc: 100.0000	 Speed: 2396.23 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.154,3470	LR: 0.000012	Loss: 0.010	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.181,3471	LR: 0.000011	Loss: 0.016	Acc: 100.0000	 Speed: 1776.49 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.208,3472	LR: 0.000011	Loss: 0.008	Acc: 100.0000	 Speed: 1834.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.235,3473	LR: 0.000011	Loss: 0.008	Acc: 100.0000	 Speed: 2558.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.262,3474	LR: 0.000011	Loss: 0.009	Acc: 100.0000	 Speed: 1901.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.289,3475	LR: 0.000011	Loss: 0.006	Acc: 100.0000	 Speed: 2595.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.315,3476	LR: 0.000011	Loss: 0.006	Acc: 100.0000	 Speed: 1808.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.342,3477	LR: 0.000011	Loss: 0.011	Acc: 100.0000	 Speed: 1948.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.369,3478	LR: 0.000011	Loss: 0.010	Acc: 100.0000	 Speed: 2203.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.396,3479	LR: 0.000011	Loss: 0.013	Acc: 100.0000	 Speed: 1889.01 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.423,3480	LR: 0.000011	Loss: 0.003	Acc: 100.0000	 Speed: 1959.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.450,3481	LR: 0.000011	Loss: 0.010	Acc: 100.0000	 Speed: 2663.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.477,3482	LR: 0.000010	Loss: 0.008	Acc: 100.0000	 Speed: 2132.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.503,3483	LR: 0.000010	Loss: 0.015	Acc: 100.0000	 Speed: 2102.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.530,3484	LR: 0.000010	Loss: 0.009	Acc: 100.0000	 Speed: 2069.73 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.557,3485	LR: 0.000010	Loss: 0.010	Acc: 100.0000	 Speed: 1697.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.584,3486	LR: 0.000010	Loss: 0.008	Acc: 100.0000	 Speed: 2040.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.611,3487	LR: 0.000010	Loss: 0.009	Acc: 100.0000	 Speed: 1972.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.638,3488	LR: 0.000010	Loss: 0.012	Acc: 100.0000	 Speed: 1887.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.664,3489	LR: 0.000010	Loss: 0.008	Acc: 100.0000	 Speed: 1666.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.691,3490	LR: 0.000010	Loss: 0.005	Acc: 100.0000	 Speed: 1899.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.718,3491	LR: 0.000010	Loss: 0.006	Acc: 100.0000	 Speed: 1814.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.745,3492	LR: 0.000010	Loss: 0.010	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.772,3493	LR: 0.000010	Loss: 0.008	Acc: 100.0000	 Speed: 1817.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.799,3494	LR: 0.000009	Loss: 0.018	Acc: 100.0000	 Speed: 2342.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.826,3495	LR: 0.000009	Loss: 0.007	Acc: 100.0000	 Speed: 2219.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.852,3496	LR: 0.000009	Loss: 0.024	Acc: 100.0000	 Speed: 600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3449.6082 samples/s	Time: 0.02s
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.879,3497	LR: 0.000009	Loss: 0.007	Acc: 100.0000	 Speed: 53.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.906,3498	LR: 0.000009	Loss: 0.013	Acc: 100.0000	 Speed: 2178.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.933,3499	LR: 0.000009	Loss: 0.005	Acc: 100.0000	 Speed: 1538.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.960,3500	LR: 0.000009	Loss: 0.014	Acc: 100.0000	 Speed: 2176.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 93.987,3501	LR: 0.000009	Loss: 0.008	Acc: 100.0000	 Speed: 1750.45 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.013,3502	LR: 0.000009	Loss: 0.016	Acc: 100.0000	 Speed: 1761.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.040,3503	LR: 0.000009	Loss: 0.004	Acc: 100.0000	 Speed: 1824.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.067,3504	LR: 0.000009	Loss: 0.010	Acc: 100.0000	 Speed: 2136.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.094,3505	LR: 0.000009	Loss: 0.005	Acc: 100.0000	 Speed: 1390.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.121,3506	LR: 0.000009	Loss: 0.008	Acc: 100.0000	 Speed: 1596.69 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.148,3507	LR: 0.000008	Loss: 0.008	Acc: 100.0000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.174,3508	LR: 0.000008	Loss: 0.004	Acc: 100.0000	 Speed: 1631.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.201,3509	LR: 0.000008	Loss: 0.006	Acc: 100.0000	 Speed: 1810.13 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.228,3510	LR: 0.000008	Loss: 0.008	Acc: 100.0000	 Speed: 2086.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.255,3511	LR: 0.000008	Loss: 0.008	Acc: 100.0000	 Speed: 1834.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.282,3512	LR: 0.000008	Loss: 0.013	Acc: 100.0000	 Speed: 1683.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.309,3513	LR: 0.000008	Loss: 0.007	Acc: 100.0000	 Speed: 1996.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.336,3514	LR: 0.000008	Loss: 0.010	Acc: 100.0000	 Speed: 2519.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.362,3515	LR: 0.000008	Loss: 0.011	Acc: 100.0000	 Speed: 1340.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.389,3516	LR: 0.000008	Loss: 0.011	Acc: 100.0000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.416,3517	LR: 0.000008	Loss: 0.006	Acc: 100.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.443,3518	LR: 0.000008	Loss: 0.008	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.470,3519	LR: 0.000008	Loss: 0.017	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.497,3520	LR: 0.000007	Loss: 0.012	Acc: 100.0000	 Speed: 1792.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.523,3521	LR: 0.000007	Loss: 0.012	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.550,3522	LR: 0.000007	Loss: 0.008	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.577,3523	LR: 0.000007	Loss: 0.008	Acc: 100.0000	 Speed: 1753.93 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.604,3524	LR: 0.000007	Loss: 0.008	Acc: 100.0000	 Speed: 1143.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.631,3525	LR: 0.000007	Loss: 0.011	Acc: 100.0000	 Speed: 1468.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.658,3526	LR: 0.000007	Loss: 0.006	Acc: 100.0000	 Speed: 1698.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.685,3527	LR: 0.000007	Loss: 0.007	Acc: 100.0000	 Speed: 1895.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.711,3528	LR: 0.000007	Loss: 0.009	Acc: 100.0000	 Speed: 1928.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.738,3529	LR: 0.000007	Loss: 0.012	Acc: 100.0000	 Speed: 1432.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.765,3530	LR: 0.000007	Loss: 0.010	Acc: 100.0000	 Speed: 1609.87 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.792,3531	LR: 0.000007	Loss: 0.006	Acc: 100.0000	 Speed: 2279.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.819,3532	LR: 0.000007	Loss: 0.014	Acc: 100.0000	 Speed: 1997.41 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.846,3533	LR: 0.000007	Loss: 0.011	Acc: 100.0000	 Speed: 1784.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:36 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.872,3534	LR: 0.000006	Loss: 0.023	Acc: 100.0000	 Speed: 666.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3327.9561 samples/s	Time: 0.02s
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.899,3535	LR: 0.000006	Loss: 0.005	Acc: 100.0000	 Speed: 52.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.926,3536	LR: 0.000006	Loss: 0.008	Acc: 100.0000	 Speed: 1803.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.953,3537	LR: 0.000006	Loss: 0.008	Acc: 100.0000	 Speed: 1559.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 94.980,3538	LR: 0.000006	Loss: 0.016	Acc: 100.0000	 Speed: 1554.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.007,3539	LR: 0.000006	Loss: 0.012	Acc: 100.0000	 Speed: 2119.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.034,3540	LR: 0.000006	Loss: 0.009	Acc: 100.0000	 Speed: 1640.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.060,3541	LR: 0.000006	Loss: 0.005	Acc: 100.0000	 Speed: 2112.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.087,3542	LR: 0.000006	Loss: 0.006	Acc: 100.0000	 Speed: 1702.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.114,3543	LR: 0.000006	Loss: 0.010	Acc: 100.0000	 Speed: 1650.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.141,3544	LR: 0.000006	Loss: 0.011	Acc: 100.0000	 Speed: 1503.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.168,3545	LR: 0.000006	Loss: 0.011	Acc: 100.0000	 Speed: 932.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.195,3546	LR: 0.000006	Loss: 0.009	Acc: 100.0000	 Speed: 1965.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.221,3547	LR: 0.000006	Loss: 0.011	Acc: 100.0000	 Speed: 1554.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.248,3548	LR: 0.000006	Loss: 0.007	Acc: 100.0000	 Speed: 1575.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.275,3549	LR: 0.000005	Loss: 0.008	Acc: 100.0000	 Speed: 2032.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.302,3550	LR: 0.000005	Loss: 0.012	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.329,3551	LR: 0.000005	Loss: 0.012	Acc: 100.0000	 Speed: 1717.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.356,3552	LR: 0.000005	Loss: 0.014	Acc: 100.0000	 Speed: 1342.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.383,3553	LR: 0.000005	Loss: 0.010	Acc: 100.0000	 Speed: 1430.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.409,3554	LR: 0.000005	Loss: 0.005	Acc: 100.0000	 Speed: 1862.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.436,3555	LR: 0.000005	Loss: 0.008	Acc: 100.0000	 Speed: 2374.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.463,3556	LR: 0.000005	Loss: 0.009	Acc: 100.0000	 Speed: 1855.37 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.490,3557	LR: 0.000005	Loss: 0.008	Acc: 100.0000	 Speed: 1972.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.517,3558	LR: 0.000005	Loss: 0.014	Acc: 100.0000	 Speed: 2179.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.544,3559	LR: 0.000005	Loss: 0.010	Acc: 100.0000	 Speed: 1795.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.570,3560	LR: 0.000005	Loss: 0.016	Acc: 100.0000	 Speed: 1628.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.597,3561	LR: 0.000005	Loss: 0.005	Acc: 100.0000	 Speed: 1769.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.624,3562	LR: 0.000005	Loss: 0.011	Acc: 100.0000	 Speed: 2145.15 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.651,3563	LR: 0.000005	Loss: 0.006	Acc: 100.0000	 Speed: 2155.07 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.678,3564	LR: 0.000005	Loss: 0.010	Acc: 100.0000	 Speed: 1929.97 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.705,3565	LR: 0.000005	Loss: 0.004	Acc: 100.0000	 Speed: 2083.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.732,3566	LR: 0.000004	Loss: 0.011	Acc: 100.0000	 Speed: 2034.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.758,3567	LR: 0.000004	Loss: 0.010	Acc: 100.0000	 Speed: 1971.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.785,3568	LR: 0.000004	Loss: 0.006	Acc: 100.0000	 Speed: 1995.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.812,3569	LR: 0.000004	Loss: 0.008	Acc: 100.0000	 Speed: 1734.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.839,3570	LR: 0.000004	Loss: 0.008	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.866,3571	LR: 0.000004	Loss: 0.009	Acc: 100.0000	 Speed: 1998.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.893,3572	LR: 0.000004	Loss: 0.004	Acc: 100.0000	 Speed: 598.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3360.6022 samples/s	Time: 0.02s
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.919,3573	LR: 0.000004	Loss: 0.015	Acc: 100.0000	 Speed: 52.68 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.946,3574	LR: 0.000004	Loss: 0.010	Acc: 100.0000	 Speed: 1643.29 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 95.973,3575	LR: 0.000004	Loss: 0.005	Acc: 100.0000	 Speed: 1943.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.000,3576	LR: 0.000004	Loss: 0.003	Acc: 100.0000	 Speed: 2343.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.027,3577	LR: 0.000004	Loss: 0.005	Acc: 100.0000	 Speed: 1498.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.054,3578	LR: 0.000004	Loss: 0.010	Acc: 100.0000	 Speed: 2443.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.081,3579	LR: 0.000004	Loss: 0.011	Acc: 100.0000	 Speed: 1289.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.107,3580	LR: 0.000004	Loss: 0.008	Acc: 100.0000	 Speed: 1939.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.134,3581	LR: 0.000004	Loss: 0.016	Acc: 100.0000	 Speed: 1933.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.161,3582	LR: 0.000004	Loss: 0.009	Acc: 100.0000	 Speed: 2096.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.188,3583	LR: 0.000004	Loss: 0.011	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.215,3584	LR: 0.000004	Loss: 0.005	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.242,3585	LR: 0.000003	Loss: 0.006	Acc: 100.0000	 Speed: 2213.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.268,3586	LR: 0.000003	Loss: 0.005	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.295,3587	LR: 0.000003	Loss: 0.009	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.322,3588	LR: 0.000003	Loss: 0.007	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.349,3589	LR: 0.000003	Loss: 0.012	Acc: 100.0000	 Speed: 1582.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.376,3590	LR: 0.000003	Loss: 0.011	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.403,3591	LR: 0.000003	Loss: 0.006	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.430,3592	LR: 0.000003	Loss: 0.014	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.456,3593	LR: 0.000003	Loss: 0.006	Acc: 100.0000	 Speed: 2419.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.483,3594	LR: 0.000003	Loss: 0.011	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.510,3595	LR: 0.000003	Loss: 0.015	Acc: 100.0000	 Speed: 1120.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.537,3596	LR: 0.000003	Loss: 0.005	Acc: 100.0000	 Speed: 1997.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.564,3597	LR: 0.000003	Loss: 0.006	Acc: 100.0000	 Speed: 1741.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.591,3598	LR: 0.000003	Loss: 0.009	Acc: 100.0000	 Speed: 1492.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.617,3599	LR: 0.000003	Loss: 0.018	Acc: 100.0000	 Speed: 2388.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.644,3600	LR: 0.000003	Loss: 0.006	Acc: 100.0000	 Speed: 1999.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.671,3601	LR: 0.000003	Loss: 0.018	Acc: 100.0000	 Speed: 1599.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.698,3602	LR: 0.000003	Loss: 0.007	Acc: 100.0000	 Speed: 1904.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.725,3603	LR: 0.000003	Loss: 0.007	Acc: 100.0000	 Speed: 1915.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.752,3604	LR: 0.000003	Loss: 0.013	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.779,3605	LR: 0.000003	Loss: 0.011	Acc: 100.0000	 Speed: 1592.75 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.805,3606	LR: 0.000003	Loss: 0.007	Acc: 100.0000	 Speed: 727.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.832,3607	LR: 0.000002	Loss: 0.008	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.859,3608	LR: 0.000002	Loss: 0.009	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.886,3609	LR: 0.000002	Loss: 0.010	Acc: 100.0000	 Speed: 1361.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.913,3610	LR: 0.000002	Loss: 0.017	Acc: 100.0000	 Speed: 617.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3583.5921 samples/s	Time: 0.02s
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.940,3611	LR: 0.000002	Loss: 0.009	Acc: 100.0000	 Speed: 52.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.966,3612	LR: 0.000002	Loss: 0.003	Acc: 100.0000	 Speed: 1490.78 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 96.993,3613	LR: 0.000002	Loss: 0.009	Acc: 100.0000	 Speed: 1565.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.020,3614	LR: 0.000002	Loss: 0.009	Acc: 100.0000	 Speed: 1827.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.047,3615	LR: 0.000002	Loss: 0.012	Acc: 100.0000	 Speed: 1906.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.074,3616	LR: 0.000002	Loss: 0.007	Acc: 100.0000	 Speed: 2130.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.101,3617	LR: 0.000002	Loss: 0.009	Acc: 100.0000	 Speed: 1776.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.128,3618	LR: 0.000002	Loss: 0.011	Acc: 100.0000	 Speed: 1667.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.154,3619	LR: 0.000002	Loss: 0.007	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.181,3620	LR: 0.000002	Loss: 0.006	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.208,3621	LR: 0.000002	Loss: 0.008	Acc: 100.0000	 Speed: 1755.95 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.235,3622	LR: 0.000002	Loss: 0.012	Acc: 100.0000	 Speed: 2082.44 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.262,3623	LR: 0.000002	Loss: 0.013	Acc: 100.0000	 Speed: 2359.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.289,3624	LR: 0.000002	Loss: 0.006	Acc: 100.0000	 Speed: 2045.00 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.315,3625	LR: 0.000002	Loss: 0.008	Acc: 100.0000	 Speed: 1884.02 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.342,3626	LR: 0.000002	Loss: 0.006	Acc: 100.0000	 Speed: 1734.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.369,3627	LR: 0.000002	Loss: 0.007	Acc: 100.0000	 Speed: 1645.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.396,3628	LR: 0.000002	Loss: 0.010	Acc: 100.0000	 Speed: 1511.39 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.423,3629	LR: 0.000002	Loss: 0.018	Acc: 100.0000	 Speed: 1553.30 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.450,3630	LR: 0.000002	Loss: 0.007	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.477,3631	LR: 0.000002	Loss: 0.010	Acc: 100.0000	 Speed: 1964.09 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.503,3632	LR: 0.000002	Loss: 0.007	Acc: 100.0000	 Speed: 1628.54 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.530,3633	LR: 0.000002	Loss: 0.007	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.557,3634	LR: 0.000001	Loss: 0.010	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.584,3635	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2346.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.611,3636	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 1814.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.638,3637	LR: 0.000001	Loss: 0.010	Acc: 100.0000	 Speed: 1792.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.664,3638	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2279.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.691,3639	LR: 0.000001	Loss: 0.009	Acc: 100.0000	 Speed: 2458.92 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.718,3640	LR: 0.000001	Loss: 0.011	Acc: 100.0000	 Speed: 1404.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.745,3641	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.772,3642	LR: 0.000001	Loss: 0.010	Acc: 100.0000	 Speed: 1417.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.799,3643	LR: 0.000001	Loss: 0.005	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:37 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.826,3644	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.852,3645	LR: 0.000001	Loss: 0.013	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.879,3646	LR: 0.000001	Loss: 0.009	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.906,3647	LR: 0.000001	Loss: 0.019	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.933,3648	LR: 0.000001	Loss: 0.006	Acc: 100.0000	 Speed: 499.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3700.3564 samples/s	Time: 0.02s
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.960,3649	LR: 0.000001	Loss: 0.005	Acc: 100.0000	 Speed: 53.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 97.987,3650	LR: 0.000001	Loss: 0.011	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.013,3651	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 1333.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.040,3652	LR: 0.000001	Loss: 0.004	Acc: 100.0000	 Speed: 1998.48 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.067,3653	LR: 0.000001	Loss: 0.009	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.094,3654	LR: 0.000001	Loss: 0.010	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.121,3655	LR: 0.000001	Loss: 0.009	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.148,3656	LR: 0.000001	Loss: 0.015	Acc: 100.0000	 Speed: 1600.34 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.174,3657	LR: 0.000001	Loss: 0.010	Acc: 100.0000	 Speed: 1333.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.201,3658	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2666.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.228,3659	LR: 0.000001	Loss: 0.014	Acc: 100.0000	 Speed: 1998.83 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.255,3660	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.282,3661	LR: 0.000001	Loss: 0.013	Acc: 100.0000	 Speed: 1598.90 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.309,3662	LR: 0.000001	Loss: 0.004	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.336,3663	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2000.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.362,3664	LR: 0.000001	Loss: 0.005	Acc: 100.0000	 Speed: 1599.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.389,3665	LR: 0.000001	Loss: 0.011	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.416,3666	LR: 0.000001	Loss: 0.011	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.443,3667	LR: 0.000001	Loss: 0.015	Acc: 100.0000	 Speed: 1599.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.470,3668	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.497,3669	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.523,3670	LR: 0.000001	Loss: 0.004	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.550,3671	LR: 0.000001	Loss: 0.009	Acc: 100.0000	 Speed: 1599.81 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.577,3672	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 2667.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.604,3673	LR: 0.000000	Loss: 0.012	Acc: 100.0000	 Speed: 2000.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.631,3674	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.658,3675	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 1600.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.685,3676	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.711,3677	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.738,3678	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 1599.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.765,3679	LR: 0.000000	Loss: 0.013	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.792,3680	LR: 0.000000	Loss: 0.017	Acc: 100.0000	 Speed: 666.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.819,3681	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2000.86 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.846,3682	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1999.67 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.872,3683	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 1333.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.899,3684	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.926,3685	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1740.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.953,3686	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 666.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3699.8712 samples/s	Time: 0.02s
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 98.980,3687	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 52.15 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.007,3688	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.034,3689	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1999.91 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.060,3690	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1600.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.087,3691	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1999.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.114,3692	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2001.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.141,3693	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 1758.71 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.168,3694	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1999.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.195,3695	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 2345.64 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.221,3696	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 2666.65 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.248,3697	LR: 0.000000	Loss: 0.015	Acc: 100.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.275,3698	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.302,3699	LR: 0.000000	Loss: 0.015	Acc: 100.0000	 Speed: 1999.43 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.329,3700	LR: 0.000000	Loss: 0.012	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.356,3701	LR: 0.000000	Loss: 0.014	Acc: 100.0000	 Speed: 2000.14 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.383,3702	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1333.38 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.409,3703	LR: 0.000000	Loss: 0.013	Acc: 100.0000	 Speed: 1916.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.436,3704	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1333.27 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.463,3705	LR: 0.000000	Loss: 0.017	Acc: 100.0000	 Speed: 1917.40 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.490,3706	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 2014.56 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.517,3707	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 1487.47 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.544,3708	LR: 0.000000	Loss: 0.015	Acc: 100.0000	 Speed: 2282.61 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.570,3709	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2000.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.597,3710	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1333.32 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.624,3711	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1702.41 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.651,3712	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1510.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.678,3713	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 2489.57 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.705,3714	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2192.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.732,3715	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 1835.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.758,3716	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 2363.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.785,3717	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1749.63 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.812,3718	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1620.28 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.839,3719	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 2664.11 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.866,3720	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.893,3721	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 2000.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.919,3722	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1998.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.946,3723	LR: 0.000000	Loss: 0.013	Acc: 100.0000	 Speed: 1663.17 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 99.973,3724	LR: 0.000000	Loss: 0.004	Acc: 100.0000	 Speed: 483.66 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3648.6357 samples/s	Time: 0.02s
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.000,3725	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 53.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.027,3726	LR: 0.000000	Loss: 0.019	Acc: 100.0000	 Speed: 2330.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.054,3727	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 1993.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.081,3728	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1556.98 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.107,3729	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 2301.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.134,3730	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 1257.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.161,3731	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1778.19 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.188,3732	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 2061.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.215,3733	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.242,3734	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2228.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.268,3735	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1599.12 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.295,3736	LR: 0.000000	Loss: 0.020	Acc: 100.0000	 Speed: 2663.26 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.322,3737	LR: 0.000000	Loss: 0.012	Acc: 100.0000	 Speed: 1752.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.349,3738	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 1969.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.376,3739	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 1563.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.403,3740	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1599.58 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.430,3741	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2000.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.456,3742	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 2030.53 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.483,3743	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 2370.33 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.510,3744	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 2667.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.537,3745	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 1998.60 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.564,3746	LR: 0.000000	Loss: 0.012	Acc: 100.0000	 Speed: 2090.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.591,3747	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 1972.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.617,3748	LR: 0.000000	Loss: 0.012	Acc: 100.0000	 Speed: 1755.77 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.644,3749	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1630.68 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.671,3750	LR: 0.000000	Loss: 0.009	Acc: 100.0000	 Speed: 2295.42 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.698,3751	LR: 0.000000	Loss: 0.013	Acc: 100.0000	 Speed: 1523.06 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.725,3752	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 1598.74 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.752,3753	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 2146.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.779,3754	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 1862.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:38 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.805,3755	LR: 0.000000	Loss: 0.014	Acc: 100.0000	 Speed: 2077.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.832,3756	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1578.59 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.859,3757	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 2114.20 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.886,3758	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 2281.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.913,3759	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 1782.82 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.940,3760	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 2000.50 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.966,3761	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 1465.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 100.993,3762	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 294.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3293.3851 samples/s	Time: 0.02s
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.020,3763	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 51.07 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.047,3764	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1247.52 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.074,3765	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1689.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.101,3766	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 1682.94 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.128,3767	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 1244.28 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.154,3768	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 1449.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.181,3769	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 2001.46 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.208,3770	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 2043.88 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.235,3771	LR: 0.000000	Loss: 0.005	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.262,3772	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 2342.21 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.289,3773	LR: 0.000000	Loss: 0.011	Acc: 100.0000	 Speed: 1998.72 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.315,3774	LR: 0.000000	Loss: 0.008	Acc: 100.0000	 Speed: 2278.89 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.342,3775	LR: 0.000000	Loss: 0.006	Acc: 100.0000	 Speed: 2164.80 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.369,3776	LR: 0.000000	Loss: 0.018	Acc: 100.0000	 Speed: 1854.35 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.396,3777	LR: 0.000000	Loss: 0.010	Acc: 100.0000	 Speed: 1789.76 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.423,3778	LR: 0.000000	Loss: 0.007	Acc: 100.0000	 Speed: 2107.96 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.450,3779	LR: 0.000001	Loss: 0.008	Acc: 100.0000	 Speed: 1993.85 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.477,3780	LR: 0.000001	Loss: 0.016	Acc: 100.0000	 Speed: 1810.52 samples/s	Time: 0hrs:0min

[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.503,3781	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 1923.22 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.530,3782	LR: 0.000001	Loss: 0.008	Acc: 100.0000	 Speed: 2283.55 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.557,3783	LR: 0.000001	Loss: 0.008	Acc: 100.0000	 Speed: 1944.62 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.584,3784	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 1805.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.611,3785	LR: 0.000001	Loss: 0.011	Acc: 100.0000	 Speed: 1803.03 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.638,3786	LR: 0.000001	Loss: 0.010	Acc: 100.0000	 Speed: 1737.31 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.664,3787	LR: 0.000001	Loss: 0.008	Acc: 100.0000	 Speed: 1826.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.691,3788	LR: 0.000001	Loss: 0.018	Acc: 100.0000	 Speed: 2202.02 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.718,3789	LR: 0.000001	Loss: 0.004	Acc: 100.0000	 Speed: 1977.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.745,3790	LR: 0.000001	Loss: 0.008	Acc: 100.0000	 Speed: 1663.25 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.772,3791	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 1622.24 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.799,3792	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 1702.84 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.826,3793	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 1501.79 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.852,3794	LR: 0.000001	Loss: 0.009	Acc: 100.0000	 Speed: 1600.04 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.879,3795	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 1733.36 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.906,3796	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 2150.10 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.933,3797	LR: 0.000001	Loss: 0.014	Acc: 100.0000	 Speed: 1863.51 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.960,3798	LR: 0.000001	Loss: 0.007	Acc: 100.0000	 Speed: 1930.08 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 101.987,3799	LR: 0.000001	Loss: 0.013	Acc: 100.0000	 Speed: 1792.05 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 183]	INFO	Phase: train	Epoch: 102.013,3800	LR: 0.000001	Loss: 0.012	Acc: 100.0000	 Speed: 462.16 samples/s	Time: 0hrs:0min
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 228]	INFO	Phase: valid	acc: 55.405	Speed: 3827.3916 samples/s	Time: 0.02s
[2026-06-18 18:39:39 - <frozen onekey_algo.fusion.MultiTransformer.run_model>: 331]	INFO	Done for training. Best metric is 62.16216216216216@8 epoch. Average for last 5 iters is 55.4054054054054

In [12]:
import os
import pandas as pd
import sys
import builtins
import types

# ==== 第二部分：保存原始sys.exit函数 ====
original_exit = sys.exit

# ==== 第三部分：创建安全的替代函数 ====
def safe_print_only_exit(code=0):
    """
    打印消息但不退出的安全函数
    在IPython中使用这个替代sys.exit
    """
    print("hello")
    # 故意不调用原始的sys.exit，确保在IPython中继续执行
    return

# ==== 第四部分：猴子补丁sys模块 ====
# 直接替换sys.exit函数，这是最关键的部分
sys.exit = safe_print_only_exit

# 同时替换builtins.exit（如果存在）
if hasattr(builtins, 'exit'):
    builtins.exit = safe_print_only_exit
else:
    builtins.exit = safe_print_only_exit
import pandas as pd
import os
import matplotlib.pyplot as plt
from onekey_algo.custom.components import metrics
from onekey_algo.custom.components.comp1 import draw_roc
from onekey_algo import get_param_in_cwd
import numpy as np

def get_log(epoch):
    log_ = pd.concat([pd.read_csv(os.path.join(root, f'../train/Epoch-{epoch}_spec.csv'), dtype={'ID': str}), 
                      pd.read_csv(os.path.join(root, f'../valid/Epoch-{epoch}_spec.csv'), dtype={'ID': str})], axis=0)
    log_.columns = ['ID', 'label-0', 'label-1']
    log_['ID'] = log_['ID'].astype(str)
    return log_

os.makedirs('img', exist_ok=True)
label_data = pd.read_csv(get_param_in_cwd('label_file'), dtype={'ID': str})
ep_map = {bagsize: get_param_in_cwd('sel_epoch')['transformer']}
metrics_df = []
dim = 1024
for dim in ep_map.keys():
    model_root = os.path.join(get_param_in_cwd('model_root'), f'Transformer')
    root = os.path.join(model_root, 'Transformer', 'viz')
    all_gt = []
    all_pred = []
    metric_df = []
    for idx, subset in enumerate(get_param_in_cwd('subsets')):
        sub_group = get_log(ep_map[dim])
        sub_group.columns = ['ID', 'label-0', 'label-1']
        sub_group = pd.merge(sub_group, label_data[label_data['group'] == subset], on='ID', how='inner')
        sub_group[['ID', 'label-0', 'label-1']].to_csv(f'results/Transformer_Transformer_{subset}.csv', index=False)
        all_gt.append(np.array(sub_group['label']))
        all_pred.append(np.array(sub_group['label-1']))
        acc, auc, ci, tpr, tnr, ppv, npv, _, _, _, thres = metrics.analysis_pred_binary(np.array(sub_group['label']), 
                                                                                        np.array(sub_group['label-1']))
        ci = f"{ci[0]:.4f}-{ci[1]:.4f}"
        metric_df.append([acc, auc, ci, tpr, tnr, ppv, npv, thres, subset])
    metric_df = pd.DataFrame(metric_df, columns=['Acc', 'AUC', '95% CI', 'Sensitivity', 'Specificity', 'PPV', 'NPV', 'Youden', 'Cohort'])
    metric_df['Dim'] = dim
    metrics_df.append(metric_df)
    draw_roc(all_gt, all_pred, labels=get_param_in_cwd('subsets'), title=f"Transformer {dim} Dimension CNN Features")
    plt.savefig(f'img/Transformer_Transformer_roc.svg', bbox_inches='tight')
    plt.show()
metrics_df = pd.concat(metrics_df, axis=0)
metric_df.to_csv('results/Transformer_cmp.csv', index=False)
metrics_df

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').